module Audio = Eta_ai.Audio

let qcheck_seed = Random.State.make [| 0xA0D1_0; 0x59_0B |]
let count = 100

let drain source =
  let pull = Audio.open_pull source in
  let buffer = Buffer.create 32 in
  let rec loop () =
    match pull () with
    | None -> Buffer.contents buffer
    | Some chunk ->
        Buffer.add_bytes buffer chunk;
        loop ()
  in
  loop ()

let property_bytes_source =
  QCheck.Test.make
    ~name:
      "oastt-59ol/bvq8 generated byte sources have exact length and replay unchanged"
    ~count QCheck.string_small (fun value ->
      let original = Bytes.of_string value in
      let source = Audio.bytes original in
      let length_known =
        Audio.known_length source = Some (Int64.of_int (String.length value))
      in
      let replayable = Audio.replayability source = Audio.Replayable in
      let first = String.equal (drain source) value in
      (* Mutating the constructor argument must not change what a reader
         yields, and a reader's chunk must not alias stored bytes. *)
      Bytes.iteri (fun index _ -> Bytes.set original index 'X') original;
      let after_argument_mutation = String.equal (drain source) value in
      let chunk = Audio.open_pull source () in
      Option.iter
        (fun chunk -> Bytes.iteri (fun i _ -> Bytes.set chunk i 'Y') chunk)
        chunk;
      let after_chunk_mutation = String.equal (drain source) value in
      length_known && replayable && first && after_argument_mutation
      && after_chunk_mutation)

let property_stream_source =
  let generated =
    QCheck.(triple (list_size (Gen.int_range 0 8) string_small) bool bool)
  in
  QCheck.Test.make
    ~name:
      "oastt-59ol/bvq8 generated pull streams preserve chunks length metadata and replayability"
    ~count generated (fun (chunks, has_length, is_replayable) ->
      let expected = String.concat "" chunks in
      let opens = ref 0 in
      let source =
        Audio.stream
          ?length:
            (if has_length then Some (Int64.of_int (String.length expected))
             else None)
          ~replayability:
            (if is_replayable then Audio.Replayable else Audio.One_shot)
          (fun () ->
            incr opens;
            let chunks = ref (List.map Bytes.of_string chunks) in
            fun () ->
              match !chunks with
              | [] -> None
              | chunk :: rest ->
                  chunks := rest;
                  Some chunk)
      in
      let metadata =
        Audio.known_length source
        =
        if has_length then Some (Int64.of_int (String.length expected)) else None
      in
      let represented =
        Audio.replayability source
        =
        if is_replayable then Audio.Replayable else Audio.One_shot
      in
      let first = String.equal (drain source) expected in
      let replay =
        if is_replayable then String.equal (drain source) expected else true
      in
      let reopen_behaviour =
        if is_replayable then String.equal (drain source) expected
        else
          match Audio.open_pull source () with
          | _ -> false
          | exception Invalid_argument _ -> true
      in
      metadata && represented && first && replay && reopen_behaviour
      && !opens = if is_replayable then 3 else 1)

let property_negative_length =
  let negative =
    QCheck.map (fun value -> Int64.of_int (-1 - value)) QCheck.int_pos
  in
  QCheck.Test.make
    ~name:"oastt-bvq8 rejects every generated negative known length" ~count
    negative (fun length ->
      match
        Audio.stream ~length ~replayability:Audio.One_shot (fun () ->
            fun () -> None)
      with
      | _ -> false
      | exception Invalid_argument _ -> true)

let property_one_shot_domain_safety =
  QCheck.Test.make
    ~name:
      "oastt-bvq8 concurrent one-shot opens admit exactly one reader and reject the other"
    ~count QCheck.unit (fun () ->
      let source =
        Audio.stream ~replayability:Audio.One_shot (fun () -> fun () -> None)
      in
      let ready = Atomic.make 0 in
      let attempt () =
        Atomic.incr ready;
        while Atomic.get ready < 2 do
          Domain.cpu_relax ()
        done;
        match Audio.open_pull source with
        | (_ : Audio.pull) -> `Opened
        | exception Invalid_argument _ -> `Rejected
      in
      let other =
        (Domain.spawn [@alert "-do_not_spawn_domains"]
           [@alert "-unsafe_multidomain"])
          attempt
      in
      let mine = attempt () in
      let theirs = Domain.join other in
      let outcomes = [ mine; theirs ] in
      List.length (List.filter (fun outcome -> outcome = `Opened) outcomes) = 1
      && List.length (List.filter (fun outcome -> outcome = `Rejected) outcomes)
         = 1)

let () =
  let code =
    QCheck_base_runner.run_tests ~colors:false ~verbose:true ~rand:qcheck_seed
      [
        property_bytes_source;
        property_stream_source;
        property_negative_length;
        property_one_shot_domain_safety;
      ]
  in
  exit code
