#!/usr/bin/env bash
set -euo pipefail

SESSION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SESSION_DIR/../.." && pwd)"

export ETA_H2_ECHO_4X4_TRACE_CONNECTIONS="${ETA_H2_ECHO_1X16_TRACE_CONNECTIONS:-1}"
export ETA_H2_ECHO_4X4_TRACE_STREAMS="${ETA_H2_ECHO_1X16_TRACE_STREAMS:-16}"
export ETA_H2_ECHO_4X4_TRACE_REQUESTS="${ETA_H2_ECHO_1X16_TRACE_REQUESTS:-24000}"
export ETA_H2_ECHO_4X4_TRACE_EVENTS="${ETA_H2_ECHO_1X16_TRACE_EVENTS:-0}"
export ETA_H2_ECHO_4X4_TRACE_MODE="${ETA_H2_ECHO_1X16_TRACE_MODE:-plain}"
export ETA_H2_ECHO_4X4_TRACE_METHOD="${ETA_H2_ECHO_1X16_TRACE_METHOD:-POST}"
export ETA_H2_ECHO_4X4_TRACE_BODY_BYTES="${ETA_H2_ECHO_1X16_TRACE_BODY_BYTES:-1024}"
export ETA_H2_ECHO_4X4_TRACE_PATH="${ETA_H2_ECHO_1X16_TRACE_PATH:-/echo}"
export ETA_H2_ECHO_4X4_TRACE_EXPECTED_BYTES="${ETA_H2_ECHO_1X16_TRACE_EXPECTED_BYTES:-1024}"
export ETA_H2_ECHO_4X4_TRACE_RESULT_ROOT="$SESSION_DIR/custom-client-results"

exec "$ROOT/.hill-climbing/h2-echo-4x4-actionable-20260615/trace_echo_4x4_custom_client.sh"
