(test
 (name law_properties)
 (modules law_properties)
 (libraries eta eta_observability eta_test eta_test_backend_eio alcotest qcheck qcheck-core.runner)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name http_law_properties)
 (modules http_law_properties)
 (libraries
  eta
  eta_http
  eta_test
  eta_test_backend_eio
  qcheck
  qcheck-core.runner)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name map_semantic_properties)
 (modules map_semantic_properties)
 (libraries eta_signal_map qcheck qcheck-core.runner))

(test
 (name map_representation_properties)
 (modules map_representation_properties)
 (libraries eta_signal_map_kernel qcheck qcheck-core.runner))

(test
 (name keyed_mapi_properties)
 (modules keyed_mapi_properties)
 (libraries eta eta_signal eta_signal_map eta_eio eta_test qcheck qcheck-core.runner eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name signal_properties)
 (modules signal_properties)
 (libraries eta eta_signal eta_signal_map eta_eio eta_test qcheck qcheck-core.runner eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))
