#!/usr/bin/env bash
set -euo pipefail

SESSION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export ETA_H2_ECHO_4X4_TRACE_REQUESTS="${ETA_H2_ECHO_4X4_TRACE_REQUESTS:-1024}"
export ETA_H2_ECHO_4X4_TRACE_EVENTS="${ETA_H2_ECHO_4X4_TRACE_EVENTS:-0}"
export ETA_H2_ECHO_4X4_STRACE_SERVER="${ETA_H2_ECHO_4X4_STRACE_SERVER:-true}"
export ETA_H2_ECHO_4X4_TRACE_DROP_INITIAL_PER_CLIENT="${ETA_H2_ECHO_4X4_TRACE_DROP_INITIAL_PER_CLIENT:-8}"
export ETA_H2_SLOW_WRITE_TRACE_THRESHOLD_US="${ETA_H2_SLOW_WRITE_TRACE_THRESHOLD_US:-0}"

exec "$SESSION_DIR/trace_echo_4x4_custom_client.sh"
