// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=exe, use-js-string=false, version=6.3.2
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(d){"use strict";function
al(f,e){var
g=f.l>=0?f.l:f.l=f.length,d=e.length,a=g-d;if(a===0)return f(...e);else if(a<0){var
h=e.slice(g-1),c=e[d-1];e=e.slice(0,g);e[g-1]=function(a){if(typeof
a!=="function")return c(a);var
b=h.slice();b[b.length-1]=c;return al(a,b)};return f(...e)}else{d--;var
c=e[d];switch(a){case
1:{var
b=function(a,b){var
g=new
Array(d+2);for(var
c=0;c<d;c++)g[c]=e[c];g[d]=a;g[d+1]=b;return f(...g)};break}case
2:{var
b=function(a,b,c){var
g=new
Array(d+3);for(var
h=0;h<d;h++)g[h]=e[h];g[d]=a;g[d+1]=b;g[d+2]=c;return f(...g)};break}default:{e.length=d;var
b=function(...a){if(a.length===0)a=[undefined];return al(f,e.concat(a))}}}b.l=a+1;return c(b)}}var
g6=al,j={k:0,x:0,h:0,e:0};function
b_(){var
a=j.e;j.e=0;j=a;return a.k}var
bl=0;function
P(){return--bl>0}function
S(a,b,c){return{joo_tramp:a,joo_args:b,joo_direct:c}}function
dB(a,b){var
c=[b,b_()];return P()?g6(a,c):S(a,c,0)}function
gY(a){var
b=j.h[1];return dB(b,a)}function
gX(a){var
b=j.h[2];return dB(b,a)}function
gW(a,b,c){var
d=[0,a,b,c];return{k:gY,x:{h:gX,t:0},h:d,e:0}}function
gZ(a,b,c,d){if(a[b+1]===c){a[b+1]=d;return 1}return 0}var
f="";function
bn(a,b,c){var
e=String.fromCharCode;if(b===0&&c<=4096&&c===a.length)return e.apply(null,a);var
g=f,d=1024;for(;0<c;b+=d,c-=d)g+=e.apply(null,a.subarray(b,b+Math.min(c,d)));return g}function
bc(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
ak(a,b,c,d,e){if(e===0)return 0;if(d===0&&(e>=c.l||c.t===2&&e>=c.c.length)){c.c=a.t===4?bn(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else if(c.t===2&&d===c.c.length){c.c+=a.t===4?bn(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else{if(c.t!==4)bc(c);var
g=a.c,h=c.c;if(a.t===4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
ar(a){return a}function
ba(a,b,c,d,e){ak(ar(a),b,c,d,e);return 0}var
d_={};function
hS(a){if(d_[a])return d_[a];var
b=d.process;if(b&&b.env&&b.env[a]!==undefined)return b.env[a];if(d.jsoo_env&&typeof
d.jsoo_env[a]==="string")return d.jsoo_env[a]}var
bj=0;(function(){var
c=hS("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]==="b"){bj=1;break}else if(b[a].startsWith("b="))bj=+b[a].slice(2);else
continue}}());var
hJ=bj,A=[0],n=248;function
ha(a,b){if(!a.js_error||b||a[0]===n)a.js_error=new
d.Error("Js exception containing backtrace");return a}function
g(a,b){return bj&&hJ?ha(a,b):a}function
d2(a,b){throw g([0,a,b])}var
hT=new
TextDecoder();function
cc(a){if(a.t!==4)bc(a);return a.c}function
an(a,b){return b.repeat(a)}function
aB(a){if(a.t===2)a.c+=an(a.l-a.c.length,"\0");else
a.c=bn(a.c,0,a.c.length);a.t=0}var
a8=127;function
d9(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>a8)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}class
${constructor(a,b,c){this.t=a;this.c=b;this.l=c}toString(){switch(this.t){case
9:case
8:return this.c;case
4:case
2:aB(this);case
0:if(d9(this.c))this.t=9;else
this.t=8;return this.c}}toUtf16(){if(this.t===9)return this.c;var
a=cc(this);return hT.decode(a)}slice(){var
a=this.t===4?this.c.slice():this.c;return new
$(this.t,a,this.l)}}function
dJ(a){return new
$(0,a,a.length)}function
c(a){return dJ(a)}function
d4(a,b){d2(a,c(b))}function
v(a){d4(A.Invalid_argument,a)}var
bI="index out of bounds";function
g3(){v(bI)}var
T=0xff;function
s(a,b,c){c&=T;if(a.t!==4){if(b===a.c.length){a.c+=String.fromCharCode(c);if(b+1===a.l)a.t=0;return 0}bc(a)}a.c[b]=c;return 0}function
as(a,b,c){if(b>>>0>=a.l)g3();return s(a,b,c)}function
bb(a,b){switch(a.t&6){case
0:return a.c.charCodeAt(b);case
2:if(b>=a.c.length)return 0;return a.c.charCodeAt(b);case
4:return a.c[b]}}var
hU=new
TextEncoder();function
g5(a){if(d9(a))return new
$(9,a,a.length);else{var
b=hU.encode(a);return new
$(4,b,b.length)}}function
R(a){return g5(a)}var
d0={};function
am(a){return d0[a]}var
bQ="jsError";function
d7(a){{if(Array.isArray(a))return a;var
b;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=A.Stack_overflow;else if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))b=A.Stack_overflow;else if(a
instanceof
d.Error&&am(bQ))b=[0,am(bQ),a];else
b=[0,A.Failure,R(String(a))];if(a
instanceof
d.Error)b.js_error=a;return b}}function
aA(a,b){var
f=bl,e=j;try{j={k:0,x:0,h:0,e:0};var
c={joo_tramp:a,joo_args:b.concat(function(a){return a})};do{bl=40;try{c=al(c.joo_tramp,c.joo_args)}catch(f){if(!j.x)throw f;var
d=j.x.h;j.x=j.x.t;c={joo_tramp:d,joo_args:[d7(f)]}}}while(c?.joo_args)}finally{bl=f;j=e}return c}function
a$(){v(bI)}function
dL(a,b){if(b>>>0>=a.length-1)a$();return a}function
g7(a){if(Number.isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!==0)return 1;return 2}return Number.isNaN(a)?4:3}function
g_(){return[0]}function
D(a){if(a<0)v("Bytes.create");return new
$(a?2:9,f,a)}function
hb(a,b,c,d){if(c>0)if(b===0&&(c>=a.l||a.t===2&&c>=a.c.length))if(d===0){a.c=f;a.t=2}else{a.c=an(c,String.fromCharCode(d));a.t=c===a.l?0:2}else{if(a.t!==4)bc(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
aR(a){a.t&6&&aB(a);return a.c}var
ap="-",az="+",ad=" ",L="0";function
b9(a){a=aR(a);var
e=a.length;if(e>31)v("format_int: format too long");var
b={justify:az,signstyle:ap,filler:ad,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=ap;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=L;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;break;case"d":case"i":b.signedconv=true;b.base=10;break;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}var
c0="0x";function
bZ(a,b){if(a.uppercase)b=b.toUpperCase();var
g=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!==ap))g++;if(a.alternate){if(a.base===8)g+=1;if(a.base===16)g+=2}var
d=f;if(a.justify===az&&a.filler===ad)for(var
e=g;e<a.width;e++)d+=ad;if(a.signedconv)if(a.sign<0)d+=ap;else if(a.signstyle!==ap)d+=a.signstyle;if(a.alternate&&a.base===8)d+=L;if(a.alternate&&a.base===16)d+=a.uppercase?"0X":c0;if(a.justify===az&&a.filler===L)for(var
e=g;e<a.width;e++)d+=L;d+=b;if(a.justify===ap)for(var
e=g;e<a.width;e++)d+=ad;return c(d)}var
aq=".",bT="nan";function
b0(a,b){function
k(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=Number.parseInt(a.toString().split(az)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=an(c,L);if(b>0)a=a+aq+an(b,L);return a}else
return a.toFixed(b)}}var
c,f=b9(a),e=f.prec<0?6:f.prec;if(b<0||b===0&&1/b===Number.NEGATIVE_INFINITY){f.sign=-1;b=-b}if(Number.isNaN(b)){c=bT;f.filler=ad}else if(!Number.isFinite(b)){c="inf";f.filler=ad}else{var
h="e";switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+L+c.slice(d-1);break;case"f":c=k(b,e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
j=c.indexOf(h),i=+c.slice(j+1);if(i<-4||b>=1e21||b.toFixed(0).length>e){var
d=j-1;while(c.charAt(d)===L)d--;if(c.charAt(d)===aq)d--;c=c.slice(0,d+1)+c.slice(j);d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+L+c.slice(d-1);break}else{var
g=e;if(i<0){g-=i+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)===L)d--;if(c.charAt(d)===aq)d--;c=c.slice(0,d+1)}}break}}return bZ(f,c)}var
bL="%d";function
bd(a,b){if(aR(a)===bL)return c(f+b);var
d=b9(a);if(b<0)if(d.signedconv){d.sign=-1;b=-b}else
b>>>=0;var
e=b.toString(d.base);if(d.prec>=0){d.filler=ad;var
g=d.prec-e.length;if(g>0)e=an(g,L)+e}return bZ(d,e)}var
hH=0;function
au(){return hH++}var
bH="Failure";function
at(a){if(!A.Failure)A.Failure=[n,c(bH),-3];d4(A.Failure,a)}function
b7(a){return a.toUtf16()}var
cd=d.Deno?.build?.os==="windows"||d.process?.platform==="win32";function
bp(){return d.process?.versions?.node!==undefined}var
X="/";function
hV(){function
a(a){if(a.charAt(0)===X)return[f,a.slice(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||f,e=c.length>0&&c.charAt(1)!==":";if(b[2]||e){var
d=b[1]||f,g=b[2]||f;return[d,a.slice(d.length+g.length)]}return}return cd?b:a}var
cf=hV();function
d6(a){return a.slice(-1)!==X?a+X:a}if(bp()&&d.process&&d.process.cwd)var
aN=d.process.cwd().replace(/\\/g,X);else
var
aN="/static";aN=d6(aN);function
hz(a){a=b7(a);if(!cf(a))a=aN+a;var
e=cf(a),d=e[1].split(/[/\\]/),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
B(a){d2(A.Sys_error,R(a))}function
d3(a,b){throw g([0,a].concat(b))}var
ax="EINVAL",bJ="EISDIR",bO="ESPIPE",ay="EBADF",db="ENOTEMPTY",a7="ENOTDIR",aJ="ENOENT",bS="EEXIST",hW=["E2BIG","EACCES","EAGAIN",ay,"EBUSY","ECHILD","EDEADLK","EDOM",bS,"EFAULT","EFBIG","EINTR",ax,"EIO",bJ,"EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",aJ,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",a7,db,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS",bO,"ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
ea(a,b,c,d){var
e=hW.indexOf(a);if(e<0){if(d==null)d=-9999;e=[0,-d]}var
g=[e,R(b||f),R(c||f)];return g}var
dh="Unix.Unix_error",c5=": ",bK=", ";function
q(a,b,c,d,e){var
f=am(dh);if(a&&f)d3(f,ea(b,c,e));else{var
d=b+c5+d+bK+c;if(e!==undefined)d+=" '"+e+"'";B(d)}}function
bg(a){return a
instanceof
$}function
b6(a){return bg(a)}function
g4(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
$(4,a,a.length)}var
a5="no such file or directory";function
b$(a,b){q(b,aJ,a5,a)}function
dK(a){return new
$(4,a,a.length)}function
U(a){return a.l}function
dx(){}class
aj
extends
dx{constructor(a){super();this.data=a}truncate(a){var
b=this.data,c=U(b);this.data=D(a|0);ak(b,0,this.data,0,Math.min(a,c))}length(){return U(this.data)}write(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=D(a+d),g=this.data;this.data=f;ak(g,0,this.data,0,e)}ak(dK(b),c,this.data,a,d);return d}read(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d>0){var
f=D(d|0);ak(this.data,a,f,0,d);b.set(cc(f),c);return d}return 0}}var
aK="bad file descriptor",dt="write",cQ="read",a6="lseek",aM="invalid argument";class
gT{constructor(a,b,c){this.file=b;this.name=a;this.flags=c;this.offset=0;this.seeked=false}err_closed(a,b){q(b,ay,a,aK)}length(){if(this.file)return this.file.length();this.err_closed("length")}truncate(a,b){var
c="truncate";if(this.file){if(!(this.flags.wronly||this.flags.rdwr))q(b,ax,c,aM);return this.file.truncate(a)}this.err_closed(c,b)}write(a,b,c,d){if(this.file&&(this.flags.wronly||this.flags.rdwr)){var
e=this.offset;c=this.file.write(e,a,b,c);this.offset+=c;return c}this.err_closed(dt,d)}read(a,b,c,d){if(this.file&&!this.flags.wronly){var
e=this.offset;c=this.file.read(e,a,b,c);this.offset+=c;return c}this.err_closed(cQ,d)}seek(a,b,c){switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)q(c,ax,a6,aM);this.offset=a;this.seeked=true;return a}pos(){return this.offset}close(){if(!this.file)this.err_closed("close");this.file=undefined}check_stream_semantics(a){if(!this.file)return this.err_closed(a,1)}}var
cY="illegal operation on a directory",c6="file already exists",bR="open",cH="not a directory";class
dw{constructor(a,b){this.content={};this.root=a;this.lookupFun=b}nm(a){return this.root+a}create_dir_if_needed(a){var
d=a.split(X),c=f;for(var
b=0;b<d.length-1;b++){c+=d[b]+X;if(this.content[c])continue;this.content[c]=Symbol("directory")}}slash(a){return/\/$/.test(a)?a:a+X}lookup(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(R(this.root),R(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
aj(ar(b[1]))}}}exists(a,b){if(a===f)return 1;var
c=this.slash(a);if(this.content[c])return 1;if(!b)this.lookup(a);return this.content[a]?1:0}isFile(a){return this.exists(a)&&!this.is_dir(a)?1:0}rename_dir(a,b){if(this.exists(b)){if(!this.is_dir(b))B(this.nm(b)+" : file already exists and is not a directory");if(this.readdir(b).length>0)B(this.nm(b)+" : directory not empty")}var
d=this.slash(a),c=this.slash(b);this.create_dir_if_needed(c);for(const
b
of
this.readdir(a))this.rename(d+b,c+b);delete
this.content[d]}rename(a,b){if(!this.exists(a))B(this.nm(a)+" : no such file or directory");if(this.is_dir(a))this.rename_dir(a,b);else{if(this.exists(b)&&this.is_dir(b))B(this.nm(b)+" : file already exists and is a directory");this.content[b]=this.content[a];delete
this.content[a]}}mkdir(a,b,c){var
e="mkdir";if(this.exists(a))q(c,bS,e,c6,this.nm(a));var
d=/^(.*)\/[^/]+/.exec(a);d=d?.[1]||f;if(!this.exists(d))q(c,aJ,e,a5,this.nm(a));if(!this.is_dir(d))q(c,a7,e,cH,this.nm(a));this.create_dir_if_needed(this.slash(a))}rmdir(a,b){var
d=a===f?f:this.slash(a),c="rmdir";if(!this.exists(a))q(b,aJ,c,a5,this.nm(a));if(!this.is_dir(a))q(b,a7,c,cH,this.nm(a));for(var
e
in
this.content)if(e.startsWith(d)&&e!==d)q(b,db,c,"directory not empty",this.nm(a));delete
this.content[d]}readdir(a){var
d=a===f?f:this.slash(a);if(!this.exists(a))B(a+": No such file or directory");if(!this.is_dir(a))B(a+": Not a directory");var
h={},g=[];for(var
c
in
this.content)if(c.startsWith(d)&&c!==d){var
e=c.indexOf(X,d.length);if(e<0)e=undefined;var
b=c.slice(d.length,e);if(b&&!h[b]){h[b]=true;g.push(b)}}return g}opendir(a,b){var
c=this.readdir(a),d=false,e=0,f="readdir";return{readSync:function(){if(d)q(b,ay,f,aK);if(e===c.length)return null;var
a=c[e];e++;return{name:a}},closeSync:function(){if(d)q(b,ay,f,aK);d=true;c=[]}}}is_dir(a){if(a===f)return true;var
b=this.slash(a);return this.content[b]?1:0}unlink(a,b){if(!this.exists(a,true))q(b,aJ,"unlink",a5,a);delete
this.content[a];return 0}access(a,b,c){this.lookup(a);if(this.content[a]){if(this.is_dir(a))q(c,"EACCESS","access","permission denied,",this.nm(a))}else
b$(this.nm(a),c);return 0}open(a,b,c,d){var
e;this.lookup(a);if(this.content[a]){if(this.is_dir(a))q(d,bJ,bR,cY,this.nm(a));if(b.create&&b.excl)q(d,bS,bR,c6,this.nm(a));e=this.content[a];if(b.truncate)e.truncate(0)}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
aj(D(0));e=this.content[a]}else
b$(this.nm(a),d);return new
gT(this.nm(a),e,b)}truncate(a,b,c){var
d;this.lookup(a);if(this.content[a]){if(this.is_dir(a))q(c,bJ,bR,cY,this.nm(a));d=this.content[a];d.truncate(b)}else
b$(this.nm(a),c)}register(a,b){var
c;if(this.content[a])B(this.nm(a)+" : file already exists");if(bg(b))c=new
aj(b);if(b6(b))c=new
aj(ar(b));else if(Array.isArray(b))c=new
aj(g4(b));else if(typeof
b==="string")c=new
aj(dJ(b));else if(b.toString){var
d=ar(R(b.toString()));c=new
aj(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
B(this.nm(a)+" : registering file with invalid content type")}}function
o(a,b,c){var
d=am(dh);if(b&&d){var
e=ea(a.code,c||a.syscall,a.path,a.errno);d3(d,e)}else
B(a.toString())}var
aP=Math.pow(2,-24);function
d1(a){throw a}function
d5(){d1(A.Division_by_zero)}var
O=0xffff,Y=0x8000,C=0xffffff,c8=0x000000;class
m{constructor(a,b,c){this.lo=a&C;this.mi=b&C;this.hi=c&O;this.caml_custom="_j"}static
UNSIGNED_MAX=new
m(C,C,O);static
SIGNED_MAX=new
m(C,C,0x7fff);static
SIGNED_MIN=new
m(c8,c8,Y);slice(){return new
m(this.lo,this.mi,this.hi)}ucompare(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}compare(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}neg(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
m(a,b,c)}add(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),d=this.hi+a.hi+(c>>24);return new
m(b,c,d)}sub(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),d=this.hi-a.hi+(c>>24);return new
m(b,c,d)}mul(a){var
b=this.lo*a.lo,c=(b*aP|0)+this.mi*a.lo+this.lo*a.mi,d=(c*aP|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
m(b,c,d)}isZero(){return(this.lo|this.mi|this.hi)===0}isNeg(){return this.hi<<16<0}and(a){return new
m(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)}or(a){return new
m(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)}xor(a){return new
m(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)}shift_left(a){a=a&63;if(a===0)return this;if(a<24)return new
m(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
m(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
m(0,0,this.lo<<a-48)}shift_right_unsigned(a){a=a&63;if(a===0)return this;if(a<24)return new
m(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
m(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
m(this.hi>>a-48,0,0)}shift_right(a){a=a&63;if(a===0)return this;var
c=this.hi<<16>>16;if(a<24)return new
m(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
m(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,b&O);return new
m(this.hi<<16>>a-32,b,b)}lsl1(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&C;this.lo=this.lo<<1&C}lsr1(){this.lo=(this.lo>>>1|this.mi<<23)&C;this.mi=(this.mi>>>1|this.hi<<23)&C;this.hi=this.hi>>>1}udivmod(a){var
d=0,c=this.slice(),b=a.slice(),e=new
m(0,0,0);while(c.ucompare(b)>0){d++;b.lsl1()}while(d>=0){d--;e.lsl1();if(c.ucompare(b)>=0){e.lo++;c=c.sub(b)}b.lsr1()}return{quotient:e,modulus:c}}div(a){var
b=this;if(a.isZero())d5();var
d=b.hi^a.hi;if(b.hi&Y)b=b.neg();if(a.hi&Y)a=a.neg();var
c=b.udivmod(a).quotient;if(d&Y)c=c.neg();return c}mod(a){var
b=this;if(a.isZero())d5();var
d=b.hi;if(b.hi&Y)b=b.neg();if(a.hi&Y)a=a.neg();var
c=b.udivmod(a).modulus;if(d&Y)c=c.neg();return c}toInt(){return this.lo|this.mi<<24}toFloat(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo}toArray(){return[this.hi>>8,this.hi&T,this.mi>>16,this.mi>>8&T,this.mi&T,this.lo>>16,this.lo>>8&T,this.lo&T]}lo32(){return this.lo|(this.mi&T)<<24}hi32(){return this.mi>>>8&O|this.hi<<16}}function
hs(a){if(a<0)a=Math.ceil(a);return new
m(a&C,Math.floor(a*aP)&C,Math.floor(a*aP*aP)&O)}var
ae=1000;function
ce(a,b){var
c;if(a.isFile())c=0;else if(a.isDirectory())c=1;else if(a.isCharacterDevice())c=2;else if(a.isBlockDevice())c=3;else if(a.isSymbolicLink())c=4;else if(a.isFIFO())c=5;else if(a.isSocket())c=6;return[0,a.dev,a.ino|0,c,a.mode,a.nlink,a.uid,a.gid,a.rdev,b?hs(a.size):a.size|0,a.atimeMs/ae,a.mtimeMs/ae,a.ctimeMs/ae]}function
H(a){return U(a)}function
bm(a,b){return bb(a,b)}function
hZ(a){var
d=H(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=bm(a,b);return c}var
c1="illegal seek",bN="node:fs";class
bV
extends
dx{constructor(a,b){super();this.fs=require(bN);this.fd=a;this.flags=b;try{var
c=this.fs.fstatSync(a);b.noSeek=c.isCharacterDevice()||c.isFIFO()||c.isSocket();this.offset=this.flags.append?c.size:0}catch(f){b.noSeek=true;this.offset=0}this.seeked=false}truncate(a,b){try{this.fs.ftruncateSync(this.fd,a|0);if(this.offset>a)this.offset=a}catch(f){o(f,b)}}isatty(){var
a=require("node:tty");return a.isatty(this.fd)?1:0}length(){try{return this.fs.fstatSync(this.fd).size}catch(f){B(f.toString())}}write(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.writeSync(this.fd,a,b,c);else
var
e=this.fs.writeSync(this.fd,a,b,c,this.offset);this.offset+=e}catch(f){o(f,d)}return e}read(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.readSync(this.fd,a,b,c);else
var
e=this.fs.readSync(this.fd,a,b,c,this.offset);this.offset+=e;return e}catch(f){o(f,d)}}seek(a,b,c){if(this.flags.noSeek)q(c,bO,a6,c1);switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)q(c,ax,a6,aM);this.offset=a;this.seeked=true;return this.offset}pos(){return this.offset}stat(a){try{var
b=this.fs.fstatSync(this.fd);return ce(b,a)}catch(f){o(f,1)}}chmod(a){try{this.fs.fchmodSync(this.fd,a);return 0}catch(f){o(f,1)}}sync(){try{this.fs.fsyncSync(this.fd);return 0}catch(f){o(f,1)}}close(a){try{this.fs.closeSync(this.fd);return 0}catch(f){o(f,a)}}check_stream_semantics(a){try{var
b=this.fs.fstatSync(this.fd)}catch(f){o(f,1,a)}if(!(b.isFile()||b.isCharacterDevice()||b.isFIFO()||b.isSocket()))q(1,ax,a,aM)}}class
dy{constructor(a){this.fs=require(bN);this.root=a}nm(a){return this.root+a}exists(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}}isFile(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){B(f.toString())}}mkdir(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){o(f,c)}}rmdir(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){o(f,b)}}readdir(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){o(f,b)}}is_dir(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){B(f.toString())}}unlink(a,b){try{this.fs.unlinkSync(this.nm(a));return 0}catch(f){o(f,b)}}utimes(a,b,c,d){try{if(b===0&&c===0){b=new
Date().getTime()/ae;c=b}this.fs.utimesSync(this.nm(a),b,c);return 0}catch(f){o(f,d)}}truncate(a,b,c){try{this.fs.truncateSync(this.nm(a),b|0);return 0}catch(f){o(f,c)}}access(a,b,c){var
d=this.fs.constants,e=0;for(var
f
in
b)switch(f){case"r":e|=d.R_OK;break;case"w":e|=d.W_OK;break;case"x":e|=cd?d.R_OK:d.X_OK;break;case"f":e|=d.F_OK;break}try{this.fs.accessSync(this.nm(a),e);return 0}catch(f){o(f,c)}}open(a,b,c,d){var
f=this.fs.constants,e=0;for(var
h
in
b)switch(h){case"rdonly":e|=f.O_RDONLY;break;case"wronly":e|=f.O_WRONLY;break;case"rdwr":e|=f.O_RDWR;break;case"append":e|=f.O_APPEND;break;case"create":e|=f.O_CREAT;break;case"truncate":e|=f.O_TRUNC;break;case"excl":e|=f.O_EXCL;break;case"binary":e|=f.O_BINARY;break;case"text":e|=f.O_TEXT;break;case"nonblock":e|=f.O_NONBLOCK;break;case"noctty":e|=f.O_NOCTTY;break;case"dsync":e|=f.O_DSYNC;break;case"sync":e|=f.O_SYNC;break}try{var
g=this.fs.openSync(this.nm(a),e,c);return new
bV(g,b)}catch(f){o(f,d)}}slash(a){return/\/$/.test(a)?a:a+X}rename(a,b,c){if(cd)try{var
d=this.nm(b),e=this.nm(a),h,g;if((h=this.fs.statSync(d,{throwIfNoEntry:false}))&&(g=this.fs.statSync(e,{throwIfNoEntry:false}))&&g.isDirectory())if(h.isDirectory()){if(!this.slash(d).startsWith(this.slash(e)))try{this.fs.rmdirSync(d)}catch{}}else{var
f=new
Error(`ENOTDIR: not a directory, rename '${e}' -> '${d}'`);throw Object.assign(f,{errno:-20,code:a7,syscall:"rename",path:d})}this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){o(f,c)}else
try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){o(f,c)}}stat(a,b,c){try{var
d=this.fs.statSync(this.nm(a));return ce(d,b)}catch(f){o(f,c)}}lstat(a,b,c){try{var
d=this.fs.lstatSync(this.nm(a));return ce(d,b)}catch(f){o(f,c)}}chmod(a,b,c){try{this.fs.chmodSync(this.nm(a),b);return 0}catch(f){o(f,c)}}link(a,b,c){try{this.fs.linkSync(this.nm(a),this.nm(b));return 0}catch(f){o(f,c)}}symlink(a,b,c,d){try{this.fs.symlinkSync(b,this.nm(c),a===0?null:a[1]?"dir":"file");return 0}catch(f){o(f,d)}}readlink(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return R(c)}catch(f){o(f,b)}}opendir(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){o(f,b)}}}function
dT(a){var
b=cf(a);if(!b)return;return b[0]+X}var
bk=dT(aN)||at("unable to compute caml_root"),aD=[];if(bp())aD.push({path:bk,device:new
dy(bk)});else
aD.push({path:bk,device:new
dw(bk)});var
cL="/static/";aD.push({path:cL,device:new
dw(cL)});function
eb(a){var
g=hz(a),a=g.join(X),f=d6(a),c;for(var
d=0;d<aD.length;d++){var
b=aD[d];if(f.search(b.path)===0&&(!c||c.path.length<b.path.length))c={path:b.path,device:b.device,rest:a.slice(b.path.length,a.length)}}if(!c&&bp()){var
e=dT(a);if(e?.match(/^[a-zA-Z]:\/$/)){var
b={path:e,device:new
dy(e)};aD.push(b);c={path:b.path,device:b.device,rest:a.slice(b.path.length,a.length)}}}if(c)return c;B("no device found for "+f)}function
g$(a,b){var
c=eb(a);if(!c.device.register)at("cannot register file");c.device.register(c.rest,b);return 0}function
d8(a,b){var
a=R(a),b=c(b);return g$(a,b)}function
hd(){var
b=[].concat(d.jsoo_fs_tmp||[],d.caml_fs_tmp||[]);if(b)for(var
a=0;a<b.length;a++)d8(b[a].name,b[a].content);d.jsoo_create_file=d8;d.jsoo_fs_tmp=[];d.caml_fs_tmp=[];return 0}function
dS(a){return[0]}var
cK="infinity";function
hh(a,b,c){if(!Number.isFinite(a)){if(Number.isNaN(a))return R(bT);return R(a>0?cK:"-infinity")}var
k=a===0&&1/a===Number.NEGATIVE_INFINITY?1:a>=0?0:1;if(k)a=-a;var
e=0;if(a===0);else if(a<1)while(a<1&&e>-1022){a*=2;e--}else
while(a>=2){a/=2;e++}var
l=e<0?f:az,g=f;if(k)g=ap;else
switch(c){case
43:g=az;break;case
32:g=ad;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(aq);if(j<0)d+=aq+an(b,L);else{var
h=j+1+b;if(d.length<h)d+=an(h-d.length,L);else
d=d.slice(0,h)}}return R(g+c0+d+"p"+l+e.toString(10))}function
hp(a){return+a.isZero()}function
ht(a){return new
m(a&C,a>>24&C,a>>31&O)}function
hu(a){return a.toInt()}function
ho(a){return+a.isNeg()}function
hr(a){return a.neg()}function
hm(a,b){var
c=b9(a);if(c.signedconv&&ho(b)){c.sign=-1;b=hr(b)}var
d=f,i=ht(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(hu(g.modulus))+d}while(!hp(b));if(c.prec>=0){c.filler=ad;var
e=c.prec-d.length;if(e>0)d=an(e,L)+d}return bZ(c,d)}function
dU(c){return function(...a){if(a.length===0)a=[undefined];var
b=aA(c,a);return b
instanceof
Function?dU(b):b}}function
hB(){return 0}function
dv(a){this.id=a}class
hA{constructor(){this.map=new
d.WeakMap();this.opened=new
d.Set()}close(a){this.opened.delete(a)}get(a){return this.map.get(a)}set(a,b){if(b.opened)this.opened.add(a);return this.map.set(a,b)}all(){return this.opened.values()}}var
bh=new
hA();function
b8(a){return bh.get(a)}function
af(a){var
b=b8(a);if(!b.opened)B("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr===0)return 0;if(b.output)b.output(bn(b.buffer,0,b.buffer_curr));else
for(var
c=0;c<b.buffer_curr;)c+=b.file.write(b.buffer,c,b.buffer_curr-c,false);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}var
b5=65536;function
hR(a,b){if(b.altname)try{var
d=require(bN),c=d.openSync(b.altname,"rs");return new
bV(c,b)}catch(f){}return new
bV(a,b)}var
aC=new
Array(3);class
gU
extends
aj{constructor(a,b){super(D(0));this.log=function(a){return 0};if(a===1&&typeof
console.log==="function")this.log=console.log;else if(a===2&&typeof
console.error==="function")this.log=console.error;else if(typeof
console.log==="function")this.log=console.log;this.flags=b}length(){return 0}truncate(a,b){q(b,ax,"ftruncate",aM)}write(a,b,c,d){var
f=c;if(this.log){if(c>0&&b>=0&&b+c<=a.length&&a[b+c-1]===10)c--;var
e=D(c);ak(dK(a),b,e,0,c);this.log(e.toUtf16());return f}q(d,ay,dt,aK)}read(a,b,c,d){q(d,ay,cQ,aK)}seek(a,b,c){q(c,bO,a6,c1)}pos(){return-1}close(){this.log=undefined}check_stream_semantics(a){}}function
bo(a,b){var
c;if(b===undefined){b=aC.length;c=new
dv(b)}else if(aC[b])c=aC[b].chanid;else
c=new
dv(b);aC[b]={file:a,chanid:c};return b|0}function
hY(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;d.writeonly=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
e=eb(a),f=e.device.open(e.rest,d,c);return bo(f,undefined)}(function(){var
c=bp();function
a(a,b){return c?hR(a,b):new
gU(a,b)}bo(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);bo(a(1,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),1);bo(a(2,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),2)}());var
dp=" doesn't exist",cJ="fd ";function
hC(a){var
b=aC[a];if(b===undefined)B(cJ+a+dp);var
d=b.file,c=b.chanid,f=null,e={file:d,offset:d.pos(),fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(b5),refill:f};bh.set(c,e);return c}function
dW(a){var
c=aC[a];if(c===undefined)B(cJ+a+dp);var
b=c.file,d=c.chanid,e=b.flags.buffered!==undefined?b.flags.buffered:1,f={file:b,offset:b.pos(),fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(b5),buffered:e};bh.set(d,f);return d}function
hD(){var
a=0,d=bh.all();for(var
c
of
d){var
b=b8(c);if(b.opened&&b.out)a=[0,c,a]}return a}function
hF(a,b,c,d){var
e=b8(a);if(!e.opened)B("Cannot output to a closed channel");b=b.subarray(c,c+d);if(e.buffer_curr+b.length>e.buffer.length){var
g=new
Uint8Array(e.buffer_curr+b.length);g.set(e.buffer);e.buffer=g}switch(e.buffered){case
0:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;af(a);break;case
1:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)af(a);break;case
2:var
f=b.lastIndexOf(10);if(f<0){e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)af(a)}else{e.buffer.set(b.subarray(0,f+1),e.buffer_curr);e.buffer_curr+=f+1;af(a);e.buffer.set(b.subarray(f+1),e.buffer_curr);e.buffer_curr+=b.length-f-1}break}return 0}function
hE(a,b,c,d){var
b=cc(b);return hF(a,b,c,d)}function
dX(a,b,c,d){return hE(a,ar(b),c,d)}function
dY(a,b){var
d=c(String.fromCharCode(b));dX(a,d,0,1);return 0}var
c4=245;function
hx(a){return a===c4?1:0}var
a_=0x7c00,aL=128,bG=256,c7=0.0009765625,dQ=function(){const
e=1/Number.EPSILON;function
o(a){return a+e-e}const
j=6.103515625e-5,m=65504,h=c7,i=h*j,l=h*e;function
p(a){const
b=+a;if(!Number.isFinite(b)||b===0)return b;const
e=b>0?1:-1,c=Math.abs(b);if(c<j)return e*o(c/i)*i;const
f=(1+l)*c,d=f-(f-c);if(d>m||Number.isNaN(d))return e*Number.POSITIVE_INFINITY;return e*d}var
a=512;const
b=new
Uint16Array(a),c=new
Uint8Array(a);for(let
a=0;a<bG;++a){const
e=a-a8;var
d=0x100;if(e<-24){b[a]=0x0000;b[a|d]=Y;c[a]=24;c[a|d]=24}else if(e<-14){var
f=0x0400;b[a]=f>>-e-14;b[a|d]=f>>-e-14|Y;c[a]=-e-1;c[a|d]=-e-1}else if(e<=15){b[a]=e+15<<10;b[a|d]=e+15<<10|Y;c[a]=13;c[a|d]=13}else{var
g=0xfc00;if(e<aL){b[a]=a_;b[a|d]=g;c[a]=24;c[a|d]=24}else{b[a]=a_;b[a|d]=g;c[a]=13;c[a|d]=13}}}const
k=new
ArrayBuffer(4),n=new
Float32Array(k),q=new
Uint32Array(k);return function(a){n[0]=p(a);const
e=q[0],d=e>>23&0x1ff;return b[d]+((e&0x007fffff)>>c[d])}}(),aa=new
DataView(new
ArrayBuffer(8));function
be(a){aa.setFloat32(0,a,true);return aa.getUint32(0,true)|0}function
hl(a,b,c){return new
m(a,b,c)}var
dr=0xf,dn=0x7ff8,dm=0x7ff0;function
bf(a){aa.setFloat64(0,a,true);var
e=aa.getUint32(0,true),c=aa.getUint32(4,true),d=e&C,f=e>>>24|c<<8&C,b=c>>>16&O;if((b&dn)===dm&&(f|d|b&dr)!==0)b|=8;return hl(d,f,b)}function
aQ(a){return a.toArray()}var
a4="_bigarr02";function
dH(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom===a4)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<O)a.write(16,b.dims[d]);else{a.write(16,O);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=aQ(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=aQ(bf(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
13:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
0:for(var
d=0;d<b.data.length;d++){var
f=be(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,be(e[1]));a.write(32,be(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=aQ(bf(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=aQ(bf(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}var
bY=function(){var
h=Math.pow,e=31,i=1023,f=h(2,-24),g=c7;return function(a){var
d=a>>>15,c=a>>>10&e,b=a&i;if(c===e)return b===0?d===0?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:Number.NaN;if(c===0)return b*(d===0?f:-f);var
j=h(2,c-15)*(d===0?1+b*g:-1-b*g);return j}}();function
dF(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
g0(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break;case
13:c=Uint16Array;break}if(!c)v("Bigarray.create: unsupported kind");var
d=new
c(b*dF(a));return d}function
b1(a){aa.setUint32(0,a,true);return aa.getFloat32(0,true)}function
aO(a){return new
m(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
b2(a){var
d=a.lo,c=a.mi,b=a.hi;if((b&dn)===dm&&(c|d|b&dr)!==0)b|=8;aa.setUint32(0,d|c<<24,true);aa.setUint32(4,c>>>8|b<<16,true);return aa.getFloat64(0,true)}function
bW(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)v("Bigarray.create: negative dimension");c=c*a[b]}return c}function
hk(a,b){return new
m(a&C,a>>>24&T|(b&O)<<8,b>>>16&O)}function
b3(a){return a.hi32()}function
b4(a){return a.lo32()}var
g1=a4,a9=254;class
dz{constructor(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d;this.caml_custom=g1}offset(a){var
c=0;if(typeof
a==="number")a=[a];if(!Array.isArray(a))v("bigarray.js: invalid offset");if(this.dims.length!==a.length)v("Bigarray.get/set: bad number of dimensions");if(this.layout===0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])a$();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])a$();c=c*this.dims[b]+(a[b]-1)}return c}get(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return hk(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[a9,e,c];case
13:return bY(this.data[a]);default:return this.data[a]}}set(a,b){switch(this.kind){case
7:this.data[a*2+0]=b4(b);this.data[a*2+1]=b3(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;case
13:this.data[a]=dQ(b);break;default:this.data[a]=b;break}return 0}fill(a){switch(this.kind){case
7:var
c=b4(a),e=b3(a);if(c===e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d===f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?d:f;break;case
13:this.data.fill(dQ(a));break;default:this.data.fill(a);break}}compare(a,b){if(this.layout!==a.layout||this.kind!==a.kind){var
h=this.kind|this.layout<<8,i=a.kind|a.layout<<8;return i-h}if(this.dims.length!==a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!==a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!==e){if(!b)return Number.NaN;if(!Number.isNaN(d))return 1;if(!Number.isNaN(e))return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
13:for(var
c=0;c<this.data.length;c++){var
f=bY(this.data[c]),g=bY(a.data[c]);if(f<g)return-1;if(f>g)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0}}class
gV
extends
dz{offset(a){if(typeof
a!=="number")if(Array.isArray(a)&&a.length===1)a=a[0];else
v("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])a$();return a}get(a){return this.data[a]}set(a,b){this.data[a]=b;return 0}fill(a){this.data.fill(a);return 0}}function
dD(a,b,c,d){var
e=dF(a);if(bW(c)*e!==d.length)v("length doesn't match dims");if(b===0&&c.length===1&&e===1&&a!==13)return new
gV(a,b,c,d);return new
dz(a,b,c,d)}function
dE(a,b,c){var
k=a.read32s();if(k<0||k>16)at("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&T,q=r>>8&1,j=[];if(c===a4)for(var
d=0;d<k;d++){var
p=a.read16u();if(p===O){var
u=a.read32u(),v=a.read32u();if(u!==0)at("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=bW(j),h=g0(l,f),i=dD(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)at("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=aO(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=b2(aO(g));i.set(d,m)}break;case
13:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
0:for(var
d=0;d<f;d++){var
m=b1(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=b1(a.read32s()),n=b1(a.read32s());i.set(d,[a9,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=b2(aO(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=b2(aO(g));i.set(d,[a9,o,n])}break}b[0]=(4+k)*4;return dD(l,q,j,h)}function
dC(a,b,c){return a.compare(b,c)}function
dZ(a,b){return Math.imul(a,b)}function
Z(a,b){b=dZ(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=dZ(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
hf(a,b){if((b&a_)===a_&&(b&0x03ff)!==0)b=0x7c01;else if(b===Y)b=0;return Z(a,b)}var
dg=0x80000000;function
hg(a,b){var
c=be(b),d=0x7f800000;if((c&d)===d&&(c&0x7fffff)!==0)c=0x7f800001;else if(c===(dg|0))c=0;a=Z(a,c);return a}function
he(a,b){var
f=bf(b),d=b4(f),c=b3(f),e=0x7ff00000;if((c&e)===e&&(d|c&0xfffff)!==0){c=e;d=0x00000001}else if(c===(dg|0)&&d===0)c=0;a=Z(a,d);a=Z(a,c);return a}function
dG(a){var
c=bW(a.dims),d=0;switch(a.kind){case
2:case
3:case
12:if(c>bG)c=bG;var
e=0,b=0;for(b=0;b+4<=c;b+=4){e=a.data[b+0]&T|(a.data[b+1]&T)<<8|(a.data[b+2]&T)<<16|a.data[b+3]<<24;d=Z(d,e)}e=0;switch(c&3){case
3:e=a.data[b+2]<<16;case
2:e|=a.data[b+1]<<8;case
1:e|=a.data[b+0];d=Z(d,e)}break;case
4:case
5:if(c>aL)c=aL;var
e=0,b=0;for(b=0;b+2<=c;b+=2){e=a.data[b+0]&O|a.data[b+1]<<16;d=Z(d,e)}if((c&1)!==0)d=Z(d,a.data[b]);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=Z(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=Z(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=Z(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=hg(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=he(d,a.data[b]);break;case
13:if(c>aL)c=aL;for(var
b=0;b<c;b++)d=hf(d,a.data[b]);break}return d}function
hi(a,b){b[0]=4;return a.read32s()}function
hG(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:at("input_value: native integer value too large");break;default:at("input_value: ill-formed native integer")}}function
hv(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return aO(d)}function
hq(a,b,c){var
e=aQ(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
hj(a,b,c){return a.compare(b)}function
hn(a){return a.lo32()^a.hi32()}var
dO={_j:{deserialize:hv,serialize:hq,fixed_length:8,compare:hj,hash:hn},_i:{deserialize:hi,fixed_length:4},_n:{deserialize:hG,fixed_length:4},_bigarray:{deserialize:function(a,b){return dE(a,b,"_bigarray")},serialize:dH,compare:dC,hash:dG},_bigarr02:{deserialize:function(a,b){return dE(a,b,a4)},serialize:dH,compare:dC,hash:dG}};function
bX(a){return dO[a.caml_custom]&&dO[a.caml_custom].compare}function
dM(a,b,c,d){var
f=bX(b);if(f){var
e=c>0?f(b,a,d):f(a,b,d);if(d&&Number.isNaN(e))return c;if(Number.isNaN(+e))return+e;if((e|0)!==0)return e|0}return c}var
c3=255,a3=252,bF=1255,a2=1010;function
dN(a){if(a===null)return a2;if(typeof
a==="number")return ae;else if(bg(a))return a3;else if(b6(a))return 1252;else if(Array.isArray(a)&&a[0]===a[0]>>>0&&a[0]<=c3){var
c=a[0]|0;return c===a9?0:c}else{var
b=12520;if(a
instanceof
String)return b;else if(typeof
a==="string")return b;else if(a
instanceof
Number)return ae;else if(a?.caml_custom)return bF;else if(a?.compare)return 1256;else if(typeof
a==="function")return 1247;else if(typeof
a==="symbol")return 1251}return 1001}function
hw(a,b){if(a<b)return-1;if(a===b)return 0;return 1}function
dI(a,b){a.t&6&&aB(a);b.t&6&&aB(b);return a.c<b.c?-1:a.c>b.c?1:0}function
hX(a,b){return dI(a,b)}function
g8(a,b,c){var
f=[];for(;;){if(!(c&&a===b)){var
e=dN(a),k=250;if(e===k){a=a[1];continue}var
g=dN(b);if(g===k){b=b[1];continue}if(e!==g){if(e===a2)return-1;if(g===a2)return 1;if(e===ae){if(g===bF)return dM(a,b,-1,c);return-1}if(g===ae){if(e===bF)return dM(b,a,1,c);return 1}return e<g?-1:1}var
i="compare: functional value";switch(e){case
247:v(i);break;case
248:var
d=hw(a[2],b[2])|0;if(d!==0)return d;break;case
249:v(i);break;case
250:v("equal: got Forward_tag, should not happen");break;case
251:v("equal: abstract value");break;case
252:if(a!==b){var
d=dI(a,b)|0;if(d!==0)return d}break;case
253:v("equal: got Double_tag, should not happen");break;case
254:v("equal: got Double_array_tag, should not happen");break;case
255:v("equal: got Custom_tag, should not happen");break;case
1247:v(i);break;case
1255:var
j=bX(a);if(j!==bX(b))return a.caml_custom<b.caml_custom?-1:1;if(!j)v("compare: abstract value");var
d=j(a,b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1256:var
d=a.compare(b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!==b){if(!c)return Number.NaN;if(!Number.isNaN(a))return 1;if(!Number.isNaN(b))return-1}break;case
1010:return 0;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!==b)return c?1:Number.NaN;break;case
1251:if(a!==b)return c?1:Number.NaN;break;case
1252:var
a=aR(a),b=aR(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;default:if(hx(e)){v("compare: continuation value");break}if(a.length!==b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1);break}}if(f.length===0)return 0;var
h=f.pop();b=f.pop();a=f.pop();if(h+1<a.length)f.push(a,b,h+1);a=a[h];b=b[h]}}function
aS(a,b){return+(g8(a,b,false)!==0)}function
bi(a){if(a===null)return a2;else if(Array.isArray(a)&&a[0]===a[0]>>>0)return a[0];else if(bg(a))return a3;else if(b6(a))return a3;else if(a
instanceof
Function||typeof
a==="function")return 247;else if(a?.caml_custom)return c3;else
return ae}function
dR(a){return a}var
bU="Effect.Unhandled";function
dV(a){var
b=am(bU);if(b)b=[0,b,a];else
b=[n,c(bU),au(0)];return b}function
hI(a,b){if(j.e===0){var
g=dV(a);throw g}var
e=j.h[3],c=j;c.k=b;var
d=[c4,c,c],f=b_();return P()?dR(e)(a,d,c,f):S(e,[a,d,c,f])}function
V(){if(!j.x)return function(a){throw a};var
a=j.x.h;j.x=j.x.t;return a}function
aT(a){j.x={h:a,t:j.x}}var
d$=undefined;function
g2(a){var
d={},c=-1;if(a)for(var
b=1;b<a.length;b++){var
e=a[b][2];c=Math.max(c,e);d[b7(a[b][1])]=e}d.next_idx=c+1;return d}function
b(a,b,c){if(c){var
d=c;if(d$)a=aA(d$,[d]);else if(A.symbols){if(!A.symidx)A.symidx=g2(A.symbols);var
e=A.symidx[d];if(e>=0)a=e;else{var
a=A.symidx.next_idx++;A.symidx[d]=a}}}A[a+1]=b;if(c)A[c]=b}function
ca(a,b){d0[aR(a)]=b;return 0}var
dk="Effect.Continuation_already_resumed";function
cb(a,b,c){if(!a)d1(am(dk));if(b===0){b=a;while(b.e!==0)b=b.e}j.k=c;b.e=j;j=a;return a.k}function
g9(a){var
b=a[1];a[1]=0;return b}function
hK(a,b,c,d){if(j.e===0){var
h=dV(a),i=g9(b);cb(i,c,d);throw h}var
f=j.h[3],e=j;e.k=d;c.e=e;b[2]=e;var
g=b_();return P()?dR(f)(a,b,e,g):S(f,[a,b,e,g])}function
aU(a,b){a.t&6&&aB(a);b.t&6&&aB(b);return new
$(0,a.c+b.c,a.l+b.l)}function
hM(){v(bI)}function
M(a,b){if(b>>>0>=H(a))hM();return bm(a,b)}function
Q(a){return a}var
bP="arm64",cZ="amd64",dA=d.process?.arch===bP?bP:cZ;function
hN(a){return dA===cZ?1:0}function
hO(a){return dA===bP?1:0}function
hP(){return 0x7fffffff/4|0}function
hQ(a){return b5}function
hy(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}var
c2="_";function
hc(a){var
b=f;if(a[0]===0){b+=a[1][1];if(a.length===3&&a[2][0]===0&&hy(a[1]))var
g=a[2],h=1;else
var
h=2,g=a;b+="(";for(var
e=h;e<g.length;e++){if(e>h)b+=bK;var
c=g[e];if(typeof
c==="number")b+=c.toString();else{var
d='"';if(c
instanceof
$)b+=d+c.toString()+d;else if(typeof
c==="string")b+=d+c.toString()+d;else
b+=c2}}b+=")"}else if(a[0]===n)b+=a[1];return b}var
bM="Fatal error: exception ",da="Pervasives.do_at_exit",cM="Printexc.handle_uncaught_exception";function
dP(a){if(Array.isArray(a)&&(a[0]===0||a[0]===n)){var
c=am(cM);if(c)aA(c,[a,false]);else{var
d=hc(a),b=am(da);if(b)aA(b,[0]);console.error(bM+d);if(a.js_error)throw a.js_error}}else
throw a}function
hL(){var
c=d.process;if(c?.on)c.on("uncaughtException",function(a,b){dP(a);c.exit(2)});else if(d.addEventListener)d.addEventListener("error",function(a){if(a.error)dP(a.error)})}hL();function
ai(a,b){return P()?a(b):S(a,[b],1)}function
G(a,b,c){return P()?(a.l>=0?a.l:a.l=a.length)===2?a(b,c):al(a,[b,c]):S(a,[b,c],0)}function
r(a,b,c){return P()?a(b,c):S(a,[b,c],0)}function
a1(a,b,c,d){return P()?(a.l>=0?a.l:a.l=a.length)===3?a(b,c,d):al(a,[b,c,d]):S(a,[b,c,d],0)}function
e(a,b,c,d){return P()?a(b,c,d):S(a,[b,c,d],0)}function
h(a,b,c,d,e){return P()?a(b,c,d,e):S(a,[b,c,d,e],0)}function
K(a,b,c,d,e,f){return P()?a(b,c,d,e,f):S(a,[b,c,d,e,f],0)}function
bE(a,b,c,d,e,f,g){return P()?(a.l>=0?a.l:a.l=a.length)===6?a(b,c,d,e,f,g):al(a,[b,c,d,e,f,g]):S(a,[b,c,d,e,f,g],0)}function
cF(a,b,c,d,e,f,g){return P()?a(b,c,d,e,f,g):S(a,[b,c,d,e,f,g],0)}function
gS(a,b,c,d,e,f,g,h,i){return P()?(a.l>=0?a.l:a.l=a.length)===8?a(b,c,d,e,f,g,h,i):al(a,[b,c,d,e,f,g,h,i]):S(a,[b,c,d,e,f,g,h,i],0)}hd();var
cN="Out_of_fibers";b(12,[n,c(cN),-13],cN);var
df="Undefined_recursive_module",cl=[n,c(df),-12];b(11,cl,df);var
cW="Assert_failure",t=[n,c(cW),-11];b(10,t,cW);var
c9="Sys_blocked_io";b(9,[n,c(c9),-10],c9);var
cT="Stack_overflow",cj=[n,c(cT),-9];b(8,cj,cT);var
du="Match_failure",ci=[n,c(du),-8];b(7,ci,du);var
dl="Not_found";b(6,[n,c(dl),-7],dl);var
dj="Division_by_zero";b(5,[n,c(dj),-6],dj);var
cR="End_of_file";b(4,[n,c(cR),-5],cR);var
cU="Invalid_argument",cg=[n,c(cU),-4];b(3,cg,cU);var
ch=[n,c(bH),-3];b(2,ch,bH);var
de="Sys_error",ck=[n,c(de),-2];b(1,ck,de);var
cO="Out_of_memory",br=[n,c(cO),-1];b(0,br,cO);function
p(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,p(a[1])];case
1:return[1,p(a[1])];case
2:return[2,p(a[1])];case
3:return[3,p(a[1])];case
4:return[4,p(a[1])];case
5:return[5,p(a[1])];case
6:return[6,p(a[1])];case
7:return[7,p(a[1])];case
8:var
c=a[1];return[8,c,p(a[2])];case
9:var
b=a[1];return[9,b,b,p(a[3])];case
10:return[10,p(a[1])];case
11:return[11,p(a[1])];case
12:return[12,p(a[1])];case
13:return[13,p(a[1])];default:return[14,p(a[1])]}}function
E(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,E(a[1],b)];case
1:return[1,E(a[1],b)];case
2:return[2,E(a[1],b)];case
3:return[3,E(a[1],b)];case
4:return[4,E(a[1],b)];case
5:return[5,E(a[1],b)];case
6:return[6,E(a[1],b)];case
7:return[7,E(a[1],b)];case
8:var
c=a[1];return[8,c,E(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,E(a[3],b)];case
10:return[10,E(a[1],b)];case
11:return[11,E(a[1],b)];case
12:return[12,E(a[1],b)];case
13:return[13,E(a[1],b)];default:return[14,E(a[1],b)]}}function
l(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,l(a[1],b)];case
1:return[1,l(a[1],b)];case
2:var
c=a[1];return[2,c,l(a[2],b)];case
3:var
d=a[1];return[3,d,l(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,l(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,l(a[4],b)];case
6:var
k=a[3],m=a[2],n=a[1];return[6,n,m,k,l(a[4],b)];case
7:var
o=a[3],p=a[2],q=a[1];return[7,q,p,o,l(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,l(a[4],b)];case
9:var
u=a[1];return[9,u,l(a[2],b)];case
10:return[10,l(a[1],b)];case
11:var
v=a[1];return[11,v,l(a[2],b)];case
12:var
w=a[1];return[12,w,l(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,l(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,l(a[3],b)];case
15:return[15,l(a[1],b)];case
16:return[16,l(a[1],b)];case
17:var
B=a[1];return[17,B,l(a[2],b)];case
18:var
C=a[1];return[18,C,l(a[2],b)];case
19:return[19,l(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,l(a[3],b)];case
21:var
F=a[1];return[21,F,l(a[2],b)];case
22:return[22,l(a[1],b)];case
23:var
G=a[1];return[23,G,l(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,l(a[3],b)]}}function
bq(a){throw g([0,ch,a],0)}function
aE(a){throw g([0,cg,a],0)}function
aV(a){return 0<=a?a:-a|0}hC(0);dW(1);var
W=dW(2);function
aF(a,b){dX(a,b,0,H(b))}function
cm(a){aF(W,a);dY(W,10);return af(W)}function
bs(a,b){var
c=hD(0);for(;;){if(!c)return b(0);var
d=c[2],f=c[1];try{af(f);c=d}catch(f){var
e=d7(f);if(e[1]!==ck){var
h=V();return h(g(e,0))}c=d}}}ca(c(da),bs);var
aG=(4*hP(0)|0)-1|0;hQ(0);var
cn=hO(0),ed=c("true"),ee=c("false");function
ec(a){return a?ed:ee}if(hN(0)){if(cn)bq(c("Cannot determine architecture: both amd64 and arm64 detected"))}else if(!cn)bq(c("Cannot determine architecture: must be amd64 or arm64"));function
ao(a,b){var
c=D(a);hb(c,0,a,b);return c}var
en=c("String.sub / Bytes.sub");function
co(a,b,c){a:{if(0<=b&&0<=c&&(U(a)-c|0)>=b){var
d=D(c);ak(a,b,d,0,c);var
e=d;break a}var
e=aE(en)}return Q(e)}var
eo=c("Bytes.blit");function
cp(a,b,c,d,e){if(0<=e&&0<=b&&(U(a)-e|0)>=b&&0<=d&&(U(c)-e|0)>=d){ak(a,b,c,d,e);return}return aE(eo)}var
ep=c("String.blit / Bytes.blit_string");function
_(a,b,c,d,e){if(0<=e&&0<=b&&(H(a)-e|0)>=b&&0<=d&&(U(c)-e|0)>=d){ba(a,b,c,d,e);return}return aE(ep)}var
eq=c("Buffer.add: cannot grow buffer");function
cq(a,b){var
d=a[2],c=[0,a[1][2]];for(;;){if(c[1]>=(d+b|0))break;c[1]=2*c[1]|0}if(aG<c[1])if((d+b|0)<=aG)c[1]=aG;else
bq(eq);var
e=D(c[1]);cp(a[1][1],0,e,0,a[2]);a[1]=[0,e,c[1]]}function
aH(a,b){var
c=H(b),d=a[2],e=a[1],f=d+c|0,g=e[1];if(e[2]<f){cq(a,c);_(b,0,a[1][1],a[2],c)}else
ba(b,0,g,d,c);a[2]=f}function
bt(a){return 5===a[2]?12:-6}function
cr(a){return[0,0,D(a)]}function
cs(a,b){var
c=U(a[2]),d=a[1]+b|0;if(c<d){var
e=c*2|0,g=d<=e?e:d,f=D(g);cp(a[2],0,f,0,c);a[2]=f}}function
av(a,b){cs(a,1);as(a[2],a[1],b);a[1]=a[1]+1|0}function
y(a,b){var
c=H(b);cs(a,c);_(b,0,a[2],a[1],c);a[1]=a[1]+c|0}function
ct(a){return co(a[2],0,a[1])}var
er=c("@]"),es=c("@}"),et=c("@?"),eu=c("@\n"),ev=c("@."),ew=c("@@"),ex=c("@%"),ey=c("@");function
cu(a){if(typeof
a==="number")switch(a){case
0:return er;case
1:return es;case
2:return et;case
3:return eu;case
4:return ev;case
5:return ew;default:return ex}return 2===a[0]?aU(ey,Q(ao(1,a[1]))):a[1]}var
cX="%li",ds="%ni",c_="%Li",cG="%i",ez=c("%c"),eA=c("%s"),eB=c(cG),eC=c(cX),eD=c(ds),eE=c(c_),eF=c("%f"),eG=c("%B"),eH=c("%{"),eI=c("%}"),eJ=c("%("),eK=c("%)"),eL=c("%a"),eM=c("%t"),eN=c("%?"),eO=c("%r"),eP=c("%_r");function
bu(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
d=c[1];y(a,ez);c=d;break;case
1:var
e=c[1];y(a,eA);c=e;break;case
2:var
f=c[1];y(a,eB);c=f;break;case
3:var
g=c[1];y(a,eC);c=g;break;case
4:var
h=c[1];y(a,eD);c=h;break;case
5:var
i=c[1];y(a,eE);c=i;break;case
6:var
j=c[1];y(a,eF);c=j;break;case
7:var
k=c[1];y(a,eG);c=k;break;case
8:var
l=c[2],m=c[1];y(a,eH);bu(a,m);y(a,eI);c=l;break;case
9:var
n=c[3],o=c[1];y(a,eJ);bu(a,o);y(a,eK);c=n;break;case
10:var
p=c[1];y(a,eL);c=p;break;case
11:var
q=c[1];y(a,eM);c=q;break;case
12:var
r=c[1];y(a,eN);c=r;break;case
13:var
s=c[1];y(a,eO);c=s;break;default:var
t=c[1];y(a,eP);c=t}}}function
u(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,u(a[1])];case
1:return[1,u(a[1])];case
2:return[2,u(a[1])];case
3:return[3,u(a[1])];case
4:return[4,u(a[1])];case
5:return[5,u(a[1])];case
6:return[6,u(a[1])];case
7:return[7,u(a[1])];case
8:var
b=a[1];return[8,b,u(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,u(a[3])];case
10:return[10,u(a[1])];case
11:return[11,u(a[1])];case
12:return[12,u(a[1])];case
13:return[13,u(a[1])];default:return[14,u(a[1])]}}function
z(a){if(typeof
a==="number")return[0,,function(a){},,function(a){}];switch(a[0]){case
0:var
b=z(a[1]),r=b[2];return[0,,function(a){r()},,b[4]];case
1:var
c=z(a[1]),s=c[2];return[0,,function(a){s()},,c[4]];case
2:var
d=z(a[1]),t=d[2];return[0,,function(a){t()},,d[4]];case
3:var
e=z(a[1]),v=e[2];return[0,,function(a){v()},,e[4]];case
4:var
f=z(a[1]),x=f[2];return[0,,function(a){x()},,f[4]];case
5:var
g=z(a[1]),y=g[2];return[0,,function(a){y()},,g[4]];case
6:var
h=z(a[1]),A=h[2];return[0,,function(a){A()},,h[4]];case
7:var
i=z(a[1]),B=i[2];return[0,,function(a){B()},,i[4]];case
8:var
j=z(a[2]),C=j[2];return[0,,function(a){C()},,j[4]];case
9:var
D=a[2],E=a[1],k=z(a[3]),F=k[4],G=k[2],l=z(w(u(E),D)),H=l[4],I=l[2];return[0,,function(a){I();G()},,function(a){H();F()}];case
10:var
m=z(a[1]),J=m[2];return[0,,function(a){J()},,m[4]];case
11:var
n=z(a[1]),K=n[2];return[0,,function(a){K()},,n[4]];case
12:var
o=z(a[1]),L=o[2];return[0,,function(a){L()},,o[4]];case
13:var
p=z(a[1]),M=p[4],N=p[2];return[0,,function(a){N()},,function(a){M()}];default:var
q=z(a[1]),O=q[4],P=q[2];return[0,,function(a){P()},,function(a){O()}]}}var
a="camlinternalFormat.ml",eQ=[0,c(a),857,23],e1=[0,c(a),821,21],eT=[0,c(a),822,21],e2=[0,c(a),825,21],eU=[0,c(a),826,21],e3=[0,c(a),829,19],eV=[0,c(a),830,19],e4=[0,c(a),833,22],eW=[0,c(a),834,22],e5=[0,c(a),838,30],eX=[0,c(a),839,30],eZ=[0,c(a),843,26],eR=[0,c(a),844,26],e0=[0,c(a),853,28],eS=[0,c(a),854,28],eY=[0,c(a),858,23];function
w(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:var
d=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,w(d,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
1:var
e=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,w(e,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
2:var
f=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,w(f,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
3:var
h=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,w(h,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
4:var
i=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,w(i,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
5:var
j=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,w(j,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
6:var
k=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,w(k,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
7:var
l=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,w(l,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
8:var
m=a[2],n=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
o=b[1],p=w(m,b[2]);return[8,w(n,o),p];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw g([0,t,eZ],1);case
9:var
q=a[3],r=a[2],s=a[1];if(typeof
b!=="number")switch(b[0]){case
9:var
v=b[3],x=b[2],y=b[1],c=z(w(u(r),y)),A=c[4];c[2].call(null);A();return[9,s,x,w(q,v)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f}throw g([0,t,e0],1);case
10:var
B=a[1];if(typeof
b!=="number"&&10===b[0])return[10,w(B,b[1])];throw g([0,t,e1],1);case
11:var
C=a[1];if(typeof
b!=="number")switch(b[0]){case
11:return[11,w(C,b[1])];case
10:break a}throw g([0,t,e2],1);case
12:var
D=a[1];if(typeof
b!=="number")switch(b[0]){case
12:return[12,w(D,b[1])];case
10:break a;case
11:break b}throw g([0,t,e3],1);case
13:var
E=a[1];if(typeof
b!=="number")switch(b[0]){case
13:return[13,w(E,b[1])];case
10:break a;case
11:break b;case
12:break c}throw g([0,t,e4],1);default:var
F=a[1];if(typeof
b!=="number")switch(b[0]){case
14:return[14,w(F,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d}throw g([0,t,e5],1)}throw g([0,t,eY],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw g([0,t,eQ],1)}}throw g([0,t,eS],1)}throw g([0,t,eR],1)}throw g([0,t,eX],1)}throw g([0,t,eW],1)}throw g([0,t,eV],1)}throw g([0,t,eU],1)}throw g([0,t,eT],1)}var
x=[n,c("CamlinternalFormat.Type_mismatch"),au(0)];function
aW(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw g(x,0)}function
aI(a,b,c){var
d=aW(a,c);if(typeof
b!=="number")return[0,d[1],[0,b[1]],d[2]];if(!b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw g(x,0)}function
k(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){var
v=k(a[1],b[1]);return[0,[0,v[1]],v[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){var
w=k(a[1],b[1]);return[0,[1,w[1]],w[2]]}break;case
2:var
af=a[2],y=aW(a[1],b),e=y[2],ag=y[1];if(typeof
e!=="number"&&1===e[0]){var
z=k(af,e[1]);return[0,[2,ag,z[1]],z[2]]}throw g(x,0);case
3:var
ah=a[2],A=aW(a[1],b),f=A[2],ai=A[1];if(typeof
f!=="number"&&1===f[0]){var
B=k(ah,f[1]);return[0,[3,ai,B[1]],B[2]]}throw g(x,0);case
4:var
aj=a[4],ak=a[1],h=aI(a[2],a[3],b),i=h[3],al=h[1];if(typeof
i!=="number"&&2===i[0]){var
am=h[2],C=k(aj,i[1]);return[0,[4,ak,al,am,C[1]],C[2]]}throw g(x,0);case
5:var
an=a[4],ao=a[1],j=aI(a[2],a[3],b),l=j[3],ap=j[1];if(typeof
l!=="number"&&3===l[0]){var
aq=j[2],D=k(an,l[1]);return[0,[5,ao,ap,aq,D[1]],D[2]]}throw g(x,0);case
6:var
ar=a[4],as=a[1],m=aI(a[2],a[3],b),n=m[3],at=m[1];if(typeof
n!=="number"&&4===n[0]){var
au=m[2],E=k(ar,n[1]);return[0,[6,as,at,au,E[1]],E[2]]}throw g(x,0);case
7:var
av=a[4],aw=a[1],o=aI(a[2],a[3],b),q=o[3],ax=o[1];if(typeof
q!=="number"&&5===q[0]){var
ay=o[2],G=k(av,q[1]);return[0,[7,aw,ax,ay,G[1]],G[2]]}throw g(x,0);case
8:var
az=a[4],aA=a[1],r=aI(a[2],a[3],b),s=r[3],aB=r[1];if(typeof
s!=="number"&&6===s[0]){var
aC=r[2],H=k(az,s[1]);return[0,[8,aA,aB,aC,H[1]],H[2]]}throw g(x,0);case
9:var
aD=a[2],I=aW(a[1],b),t=I[2],aE=I[1];if(typeof
t!=="number"&&7===t[0]){var
J=k(aD,t[1]);return[0,[9,aE,J[1]],J[2]]}throw g(x,0);case
10:var
K=k(a[1],b);return[0,[10,K[1]],K[2]];case
11:var
aF=a[1],L=k(a[2],b);return[0,[11,aF,L[1]],L[2]];case
12:var
aG=a[1],M=k(a[2],b);return[0,[12,aG,M[1]],M[2]];case
13:if(typeof
b!=="number"&&8===b[0]){var
N=b[1],aH=b[2],aJ=a[3],aK=a[1];if(aS([0,a[2]],[0,N]))throw g(x,0);var
O=k(aJ,aH);return[0,[13,aK,N,O[1]],O[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){var
P=b[1],aL=b[3],aM=a[3],aN=a[2],aO=a[1],aP=[0,p(P)];if(aS([0,p(aN)],aP))throw g(x,0);var
Q=k(aM,p(aL));return[0,[14,aO,P,Q[1]],Q[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){var
R=k(a[1],b[1]);return[0,[15,R[1]],R[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){var
S=k(a[1],b[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aQ=a[1],T=k(a[2],b);return[0,[17,aQ,T[1]],T[2]];case
18:var
U=a[2],u=a[1];if(0===u[0]){var
Y=u[1],aV=Y[2],Z=k(Y[1],b),aX=Z[1],_=k(U,Z[2]);return[0,[18,[0,[0,aX,aV]],_[1]],_[2]]}var
$=u[1],aY=$[2],aa=k($[1],b),aZ=aa[1],ab=k(U,aa[2]);return[0,[18,[1,[0,aZ,aY]],ab[1]],ab[2]];case
19:if(typeof
b!=="number"&&13===b[0]){var
V=k(a[1],b[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){var
aR=a[2],aT=a[1],W=k(a[3],b[1]);return[0,[20,aT,aR,W[1]],W[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){var
aU=a[1],X=k(a[2],b[1]);return[0,[21,aU,X[1]],X[2]]}break;case
23:var
d=a[2],c=a[1];if(typeof
c!=="number")switch(c[0]){case
8:return bv([8,c[1],c[2]],d,b);case
9:var
a0=c[1],ad=F(c[2],d,b),ae=ad[2];return[0,[23,[9,a0,ad[1]],ae[1]],ae[2]];default:return bv(c,d,b)}if(2!==c)return bv(c,d,b);if(typeof
b!=="number"&&14===b[0]){var
ac=k(d,b[1]);return[0,[23,2,ac[1]],ac[2]]}throw g(x,0)}throw g(x,0)}function
bv(a,b,c){var
d=k(b,c);return[0,[23,a,d[1]],d[2]]}function
F(a,b,c){if(typeof
a==="number")return[0,0,k(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=F(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
h=F(a[1],b,c[1]);return[0,[1,h[1]],h[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
i=F(a[1],b,c[1]);return[0,[2,i[1]],i[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
j=F(a[1],b,c[1]);return[0,[3,j[1]],j[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
l=F(a[1],b,c[1]);return[0,[4,l[1]],l[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
m=F(a[1],b,c[1]);return[0,[5,m[1]],m[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
n=F(a[1],b,c[1]);return[0,[6,n[1]],n[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
o=F(a[1],b,c[1]);return[0,[7,o[1]],o[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
q=c[1],C=c[2],D=a[2];if(aS([0,a[1]],[0,q]))throw g(x,0);var
r=F(D,b,C);return[0,[8,q,r[1]],r[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],E=c[3],G=a[3],H=a[2],I=a[1],J=[0,p(e)];if(aS([0,p(I)],J))throw g(x,0);var
K=[0,p(d)];if(aS([0,p(H)],K))throw g(x,0);var
s=z(w(u(e),d)),L=s[4];s[2].call(null);L();var
t=F(p(G),b,E),M=t[2];return[0,[9,e,d,u(t[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
v=F(a[1],b,c[1]);return[0,[10,v[1]],v[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
y=F(a[1],b,c[1]);return[0,[11,y[1]],y[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
A=F(a[1],b,c[1]);return[0,[13,A[1]],A[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
B=F(a[1],b,c[1]);return[0,[14,B[1]],B[2]]}break}throw g(x,0)}var
cV=120;function
I(a,b,c){var
d=H(c),g=0<=b?a:0,f=aV(b);if(f<=d)return c;var
h=2===g?48:32,e=ao(f,h);switch(g){case
0:_(c,0,e,0,d);break;case
1:_(c,0,e,f-d|0,d);break;default:a:if(0<d){if(M(c,0)!==43&&M(c,0)!==45&&M(c,0)!==32)break a;as(e,0,M(c,0));_(c,1,e,(f-d|0)+1|0,d-1|0);break}a:if(1<d&&M(c,0)===48){if(M(c,1)!==cV&&M(c,1)!==88)break a;as(e,1,M(c,1));_(c,2,e,(f-d|0)+2|0,d-2|0);break}_(c,0,e,f-d|0,d)}return Q(e)}var
cP=-97;function
aw(a,b){var
d=aV(a),c=H(b),e=M(b,0);a:{b:{if(58>e){if(32!==e){if(43>e)break a;switch(e-43|0){case
5:if(c>=(d+2|0))break b;if(1>=c)break b;if(M(b,1)!==cV&&M(b,1)!==88)break b;var
g=ao(d+2|0,48);as(g,1,M(b,1));_(b,2,g,(d-c|0)+4|0,c-2|0);return Q(g);case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(c>=(d+1|0))break a;var
f=ao(d+1|0,48);as(f,0,e);_(b,1,f,(d-c|0)+2|0,c-1|0);return Q(f)}if(71<=e){if(5<e+cP>>>0)break a}else if(65>e)break a}if(c<d){var
h=ao(d,48);_(b,0,h,d-c|0,c);return Q(h)}}return b}var
dc=100;function
e6(a){var
e=ar(a),l=U(e)-1|0,b=[0,0];if(l>=0){var
h=0;for(;;){var
f=bb(e,h);a:{b:{c:{if(32<=f){var
i=f-34|0;if(58<i>>>0){if(93<=i)break c}else if(56<i-1>>>0)break b;var
j=1;break a}if(11<=f){if(13===f)break b}else if(8<=f)break b}var
j=4;break a}var
j=2}b[1]=b[1]+j|0;var
r=h+1|0;if(l===h)break;h=r}}if(b[1]===U(e))var
k=e;else{var
c=D(b[1]);b[1]=0;var
m=U(e)-1|0;if(m<0)var
k=c;else{var
g=0;for(;;){var
d=bb(e,g);a:{b:{c:{if(35<=d){if(92!==d){if(a8<=d)break b;break c}}else{if(32>d){if(14<=d)break b;switch(d){case
8:s(c,b[1],92);b[1]++;s(c,b[1],98);break a;case
9:s(c,b[1],92);b[1]++;s(c,b[1],116);break a;case
10:s(c,b[1],92);b[1]++;s(c,b[1],110);break a;case
13:s(c,b[1],92);b[1]++;s(c,b[1],114);break a;default:break b}}if(34>d)break c}s(c,b[1],92);b[1]++;s(c,b[1],d);break a}s(c,b[1],d);break a}s(c,b[1],92);b[1]++;s(c,b[1],48+(d/dc|0)|0);b[1]++;s(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;s(c,b[1],48+(d%10|0)|0)}b[1]++;var
q=g+1|0;if(m===g){var
k=c;break}g=q}}}var
p=Q(k),n=H(p),o=ao(n+2|0,34);ba(p,0,o,1,n);return Q(o)}var
dd=103,fV=[0,dd];function
cv(a,b){var
h=aV(b),g=fV[1];switch(a[2]){case
0:var
d=102;break;case
1:var
d=101;break;case
2:var
d=69;break;case
3:var
d=dd;break;case
4:var
d=71;break;case
6:var
d=104;break;case
7:var
d=72;break;case
8:var
d=70;break;default:var
d=g}var
e=cr(16);av(e,37);switch(a[1]){case
1:av(e,43);break;case
2:av(e,32);break}if(8<=a[2])av(e,35);av(e,46);y(e,c(f+h));av(e,d);return ct(e)}function
aX(a,b){if(13>a)return b;var
i=H(b)-1|0,n=-48,h=[0,0];if(i>=0){var
d=0;for(;;){if(9>=bm(b,d)+n>>>0)h[1]++;var
p=d+1|0;if(i===d)break;d=p}}var
j=h[1],k=D(H(b)+((j-1|0)/3|0)|0),l=[0,0];function
e(a){as(k,l[1],a);l[1]++}var
f=[0,((j-1|0)%3|0)+1|0],m=H(b)-1|0;if(m>=0){var
c=0;for(;;){var
g=bm(b,c);if(9<g+n>>>0)e(g);else{if(0===f[1]){e(95);f[1]=3}f[1]--;e(g)}var
o=c+1|0;if(m===c)break;c=o}}return Q(k)}var
c$="%u",e7=c(bL),e_=c(cG),fh=c(c$),e8=c("%+d"),e9=c("% d"),e$=c("%+i"),fa=c("% i"),fb=c("%x"),fc=c("%#x"),fd=c("%X"),fe=c("%#X"),ff=c("%o"),fg=c("%#o");function
fW(a,b){switch(a){case
1:var
c=e8;break;case
2:var
c=e9;break;case
4:var
c=e$;break;case
5:var
c=fa;break;case
6:var
c=fb;break;case
7:var
c=fc;break;case
8:var
c=fd;break;case
9:var
c=fe;break;case
10:var
c=ff;break;case
11:var
c=fg;break;case
0:case
13:var
c=e7;break;case
3:case
14:var
c=e_;break;default:var
c=fh}return aX(a,bd(c,b))}var
fv=c("%ld"),fy=c(cX),fH=c("%lu"),fw=c("%+ld"),fx=c("% ld"),fz=c("%+li"),fA=c("% li"),fB=c("%lx"),fC=c("%#lx"),fD=c("%lX"),fE=c("%#lX"),fF=c("%lo"),fG=c("%#lo");function
fX(a,b){switch(a){case
1:var
c=fw;break;case
2:var
c=fx;break;case
4:var
c=fz;break;case
5:var
c=fA;break;case
6:var
c=fB;break;case
7:var
c=fC;break;case
8:var
c=fD;break;case
9:var
c=fE;break;case
10:var
c=fF;break;case
11:var
c=fG;break;case
0:case
13:var
c=fv;break;case
3:case
14:var
c=fy;break;default:var
c=fH}return aX(a,bd(c,b))}var
fI=c("%nd"),fL=c(ds),fU=c("%nu"),fJ=c("%+nd"),fK=c("% nd"),fM=c("%+ni"),fN=c("% ni"),fO=c("%nx"),fP=c("%#nx"),fQ=c("%nX"),fR=c("%#nX"),fS=c("%no"),fT=c("%#no");function
fY(a,b){switch(a){case
1:var
c=fJ;break;case
2:var
c=fK;break;case
4:var
c=fM;break;case
5:var
c=fN;break;case
6:var
c=fO;break;case
7:var
c=fP;break;case
8:var
c=fQ;break;case
9:var
c=fR;break;case
10:var
c=fS;break;case
11:var
c=fT;break;case
0:case
13:var
c=fI;break;case
3:case
14:var
c=fL;break;default:var
c=fU}return aX(a,bd(c,b))}var
fi=c("%Ld"),fl=c(c_),fu=c("%Lu"),fj=c("%+Ld"),fk=c("% Ld"),fm=c("%+Li"),fn=c("% Li"),fo=c("%Lx"),fp=c("%#Lx"),fq=c("%LX"),fr=c("%#LX"),fs=c("%Lo"),ft=c("%#Lo");function
fZ(a,b){switch(a){case
1:var
c=fj;break;case
2:var
c=fk;break;case
4:var
c=fm;break;case
5:var
c=fn;break;case
6:var
c=fo;break;case
7:var
c=fp;break;case
8:var
c=fq;break;case
9:var
c=fr;break;case
10:var
c=fs;break;case
11:var
c=ft;break;case
0:case
13:var
c=fi;break;case
3:case
14:var
c=fl;break;default:var
c=fu}return aX(a,hm(c,b))}var
f3=c(bT),f1=c("neg_infinity"),f2=c(cK),f0=c(aq);function
ab(k,b,c){function
l(a){switch(k[1]){case
0:var
d=45;break;case
1:var
d=43;break;default:var
d=32}return hh(c,b,d)}function
p(a){var
b=g7(c);return 3===b?c<0.?f1:f2:4<=b?f3:a}switch(k[2]){case
5:var
e=b0(cv(k,b),c),d=0,t=H(e);for(;;){a:{if(d!==t){var
m=M(e,d)-46|0;b:{if(23<m>>>0){if(55!==m)break b}else if(21>=m-1>>>0)break b;var
o=1;break a}d=d+1|0;continue}var
o=0}var
u=o?e:aU(e,f0);return p(u)}case
6:return l();case
7:var
i=ar(l()),f=U(i);if(0===f)var
j=i;else{var
g=D(f),n=f-1|0;if(n<0)var
j=g;else{var
a=0;for(;;){var
h=bb(i,a),q=25<h+cP>>>0?h:h-32|0;s(g,a,q);var
r=a+1|0;if(n===a){var
j=g;break}a=r}}}return Q(j);case
8:return p(l());default:return b0(cv(k,b),c)}}var
eh=c("\\\\"),ei=c("\\'"),ej=c("\\b"),ek=c("\\t"),el=c("\\n"),em=c("\\r"),f6=c(c$),f4=[0,c(a),1565,4],f5=c("Printf: bad conversion %["),f7=[0,c(a),1633,39];function
i(a,b,c,d){a:{b:{c:{d:{e:{f:{g:{h:{i:{j:{k:{var
j=a,f=b,e=c;l:for(;;){if(typeof
e==="number")return r(j,f,d);switch(e[0]){case
0:break a;case
1:break b;case
2:break c;case
3:return d(bx(j,f,e[2],e[1],e6));case
4:return d(aY(j,f,e[4],e[2],e[3],fW,e[1]));case
5:return d(aY(j,f,e[4],e[2],e[3],fX,e[1]));case
6:return d(aY(j,f,e[4],e[2],e[3],fY,e[1]));case
7:return d(aY(j,f,e[4],e[2],e[3],fZ,e[1]));case
8:break d;case
9:return d(bx(j,f,e[2],e[1],ec));case
10:f=[7,f];e=e[1];break;case
11:f=[2,f,e[1]];e=e[2];break;case
12:f=[3,f,e[1]];e=e[2];break;case
13:break e;case
14:break f;case
15:break g;case
16:break h;case
17:f=[0,f,e[1]];e=e[2];break;case
18:var
w=e[1];if(0===w[0]){let
c=f,d=j,g=e[2];j=function(a,b){return h(i,d,[1,c,[0,a]],g,b)};f=0;e=w[1][1]}else{let
c=f,d=j,g=e[2];j=function(a,b){return h(i,d,[1,c,[1,a]],g,b)};f=0;e=w[1][1]}break;case
19:var
ad=V();return ad(g([0,t,f4],1));case
20:break i;case
21:break j;case
22:break k;case
23:var
y=e[2],v=e[1];if(typeof
v!=="number")return 9===v[0]?K(J,j,f,v[2],y,d):h(bw,j,f,y,d);if(2!==v)return h(bw,j,f,y,d);var
ac=V();return ac(g([0,t,f7],1));default:break l}}var
Y=e[3],Z=e[1];return G(e[2],0,function(a){return cF(cw,j,f,Y,Z,a,d)})}var
X=e[1];return d(function(a,b){return h(i,j,[5,f,a],X,b)})}var
W=e[2];return d(function(a,b){return h(i,j,[4,f,bd(f6,a)],W,b)})}var
T=e[3],U=[8,f,f5];return d(function(a,b){return h(i,j,U,T,b)})}var
S=e[1];return d(function(a,b){return h(i,j,[6,f,a],S,b)})}var
R=e[1];return d(function(e,d,c){return h(i,j,[6,f,function(a,b){return a1(e,a,d,b)}],R,c)})}var
O=e[3],P=e[2];return d(function(a,b){var
d=a[1],c=k(d,p(u(P)));if(typeof
c[2]==="number")return h(i,j,f,l(c[1],O),b);var
e=V();return e(g(x,0))})}var
M=e[3],N=e[2],C=cr(16);bu(C,N);var
E=ct(C);return d(function(a,b){return h(i,j,[4,f,E],M,b)})}var
n=e[4],o=e[3],q=e[2],m=e[1];if(typeof
q==="number"){if(typeof
o==="number")return o?d(function(a,b,c){return h(i,j,[4,f,ab(m,a,b)],n,c)}):d(function(a,b){return h(i,j,[4,f,ab(m,bt(m),a)],n,b)});var
_=o[1];return d(function(a,b){return h(i,j,[4,f,ab(m,_,a)],n,b)})}if(0===q[0]){var
z=q[2],A=q[1];if(typeof
o==="number")return o?d(function(a,b,c){return h(i,j,[4,f,I(A,z,ab(m,a,b))],n,c)}):d(function(a,b){return h(i,j,[4,f,I(A,z,ab(m,bt(m),a))],n,b)});var
$=o[1];return d(function(a,b){return h(i,j,[4,f,I(A,z,ab(m,$,a))],n,b)})}var
B=q[1];if(typeof
o==="number")return o?d(function(a,b,c,d){return h(i,j,[4,f,I(B,a,ab(m,b,c))],n,d)}):d(function(a,b,c){return h(i,j,[4,f,I(B,a,ab(m,bt(m),b))],n,c)});var
aa=o[1];return d(function(a,b,c){return h(i,j,[4,f,I(B,a,ab(m,aa,b))],n,c)})}return d(bx(j,f,e[2],e[1],function(a){return a}))}var
L=e[1];return d(function(a,b){a:{b:{if(40<=a){if(92===a){var
c=eh;break a}if(a8<=a)break b}else{if(32>a){if(14<=a)break b;switch(a){case
8:var
c=ej;break a;case
9:var
c=ek;break a;case
10:var
c=el;break a;case
13:var
c=em;break a;default:break b}}if(39<=a){var
c=ei;break a}}var
e=D(1);s(e,0,a);var
c=Q(e);break a}var
d=D(4);s(d,0,92);s(d,1,48+(a/dc|0)|0);s(d,2,48+((a/10|0)%10|0)|0);s(d,3,48+(a%10|0)|0);var
c=Q(d)}var
g=H(c),k=ao(g+2|0,39);ba(c,0,k,1,g);return h(i,j,[4,f,Q(k)],L,b)})}var
F=e[1];return d(function(a,b){return h(i,j,[5,f,a],F,b)})}var
f8=[0,c(a),1656,31],f9=[0,c(a),1657,31];function
J(i,f,c,d,e){if(typeof
c==="number")return h(bw,i,f,d,e);switch(c[0]){case
0:var
j=c[1];return e(function(a,b){return K(J,i,f,j,d,b)});case
1:var
k=c[1];return e(function(a,b){return K(J,i,f,k,d,b)});case
2:var
l=c[1];return e(function(a,b){return K(J,i,f,l,d,b)});case
3:var
m=c[1];return e(function(a,b){return K(J,i,f,m,d,b)});case
4:var
n=c[1];return e(function(a,b){return K(J,i,f,n,d,b)});case
5:var
o=c[1];return e(function(a,b){return K(J,i,f,o,d,b)});case
6:var
p=c[1];return e(function(a,b){return K(J,i,f,p,d,b)});case
7:var
q=c[1];return e(function(a,b){return K(J,i,f,q,d,b)});case
8:var
r=c[2];return e(function(a,b){return K(J,i,f,r,d,b)});case
9:var
s=c[3],a=c[2],v=w(u(c[1]),a);return e(function(a,b){return K(J,i,f,E(v,s),d,b)});case
10:var
x=c[1];return e(function(a,b,c){return K(J,i,f,x,d,c)});case
11:var
y=c[1];return e(function(a,b){return K(J,i,f,y,d,b)});case
12:var
z=c[1];return e(function(a,b){return K(J,i,f,z,d,b)});case
13:var
A=V();return A(g([0,t,f8],1));default:var
b=V();return b(g([0,t,f9],1))}}var
f_=c("Printf: bad conversion %_");function
bw(a,b,c,d){return h(i,a,[8,b,f_],c,d)}function
bx(j,g,f,d,e){if(typeof
d==="number")return function(a,b){return h(i,j,[4,g,e(a)],f,b)};if(0===d[0]){var
c=d[2],k=d[1];return function(a,b){return h(i,j,[4,g,I(k,c,e(a))],f,b)}}var
l=d[1];return function(a,b,c){return h(i,j,[4,g,I(l,a,e(b))],f,c)}}function
aY(l,k,j,d,e,f,g){if(typeof
d==="number"){if(typeof
e==="number")return e?function(a,b,c){return h(i,l,[4,k,aw(a,f(g,b))],j,c)}:function(a,b){return h(i,l,[4,k,f(g,a)],j,b)};var
c=e[1];return function(a,b){return h(i,l,[4,k,aw(c,f(g,a))],j,b)}}if(0===d[0]){var
m=d[2],n=d[1];if(typeof
e==="number")return e?function(a,b,c){return h(i,l,[4,k,I(n,m,aw(a,f(g,b)))],j,c)}:function(a,b){return h(i,l,[4,k,I(n,m,f(g,a))],j,b)};var
p=e[1];return function(a,b){return h(i,l,[4,k,I(n,m,aw(p,f(g,a)))],j,b)}}var
o=d[1];if(typeof
e==="number")return e?function(a,b,c,d){return h(i,l,[4,k,I(o,a,aw(b,f(g,c)))],j,d)}:function(a,b,c){return h(i,l,[4,k,I(o,a,f(g,b))],j,c)};var
q=e[1];return function(a,b,c){return h(i,l,[4,k,I(o,a,aw(q,f(g,b)))],j,c)}}function
cw(j,g,c,d,e,f){if(!d)return h(i,j,[4,g,e],c,f);var
k=d[1];return f(function(a,b){return G(e,a,function(a){return cF(cw,j,g,c,k,a,b)})})}var
cS="@[",di="@{",f$=c(di),ga=c(cS);function
ac(d,b,c){function
f(a){if(typeof
a==="number")return c();switch(a[0]){case
0:var
h=a[1],i=cu(a[2]);return e(ac,d,h,function(a){return c(aF(d,i))});case
1:var
b=a[2],g=a[1];if(0===b[0]){var
j=b[1];return e(ac,d,g,function(a){aF(d,f$);return ai(f,j)})}var
k=b[1];return e(ac,d,g,function(a){aF(d,ga);return ai(f,k)});case
6:var
n=a[2];return e(ac,d,a[1],function(a){return G(n,d,c)});case
7:return e(ac,d,a[1],function(a){af(d);return c()});case
8:var
o=a[2];return e(ac,d,a[1],function(a){return c(aE(o))});case
2:case
4:var
l=a[2];return e(ac,d,a[1],function(a){return c(aF(d,l))});default:var
m=a[2];return e(ac,d,a[1],function(a){dY(d,m);return c()})}}return f(b)}var
gb=c(di),gc=c(cS);function
ag(d,b,c){function
f(a){if(typeof
a==="number")return c();switch(a[0]){case
0:var
i=a[1],j=cu(a[2]);return e(ag,d,i,function(a){return c(aH(d,j))});case
1:var
b=a[2],g=a[1];if(0===b[0]){var
k=b[1];return e(ag,d,g,function(a){aH(d,gb);return ai(f,k)})}var
l=b[1];return e(ag,d,g,function(a){aH(d,gc);return ai(f,l)});case
6:var
n=a[2];return e(ag,d,a[1],function(a){return G(n,0,function(a){return c(aH(d,a))})});case
7:return ai(f,a[1]);case
8:var
o=a[2];return e(ag,d,a[1],function(a){return c(aE(o))});case
2:case
4:var
m=a[2];return e(ag,d,a[1],function(a){return c(aH(d,m))});default:var
h=a[2];return e(ag,d,a[1],function(a){var
b=d[2],e=d[1],f=e[1];if(e[2]<=b){cq(d,1);as(d[1][1],d[2],h)}else
s(f,b,h);d[2]=b+1|0;return c()})}}return f(b)}function
aZ(d,b,c){return h(i,function(a,b){return e(ac,d,a,function(a){return b(0)})},0,b[1],c)}function
N(a,b){return h(i,function(a,b){var
d=aG<64?aG:64,c=[0,[0,D(d),d],0];return e(ag,c,a,function(a){return b(co(c[1][1],0,c[2]))})},0,a[1],b)}var
eg=c("%.12g"),ef=c(aq),gf=[0,[4,0,0,0,0],c(bL)],gd=[0,[3,0,0],c("%S")],ge=c(c2);function
bA(a,b,c){var
d=a[b+1];if(!(1-(typeof
d==="number")))return r(N,gf,function(a){return G(a,d,c)});if(bi(d)===a3)return r(N,gd,function(a){return G(a,d,c)});if(bi(d)!==253)return c(ge);var
f=b0(eg,d),e=0,h=H(f);for(;;){if(h<=e)return c(aU(f,ef));var
g=M(f,e);a:{if(48<=g){if(58<=g)break a}else if(45!==g)break a;e=e+1|0;continue}return c(f)}}var
gg=c(f),gh=[0,[11,c(bK),[2,0,[2,0,0]]],c(", %s%s")];function
cx(a,b,c){return a.length-1<=b?c(gg):e(cx,a,b+1|0,function(d){return e(bA,a,b,function(b){return r(N,gh,function(a){return a1(a,b,d,c)})})})}var
gi=[0,[12,40,[2,0,[2,0,[12,41,0]]]],c("(%s%s)")],gj=c(f),gk=c(f),gl=[0,[12,40,[2,0,[12,41,0]]],c("(%s)")];function
cy(a,b){function
f(a){var
c=a[2],d=a[1];return c?b(aU(d,c[1])):b(d)}if(0!==bi(a))return f([0,a[1],0]);var
d=a.length-1,g=a[1][1];function
c(a){return f([0,g,[0,a]])}if(2<d>>>0)return e(cx,a,2,function(b){return e(bA,a,1,function(d){return r(N,gi,function(a){return a1(a,d,b,c)})})});switch(d){case
2:return e(bA,a,1,function(b){return r(N,gl,function(a){return G(a,b,c)})});case
0:return c(gj);default:return c(gk)}}var
dq=", characters ",bz=[0,[11,c('File "'),[2,0,[11,c('", line '),[4,0,0,0,[11,c(dq),[4,0,0,0,[12,45,[4,0,0,0,[11,c(c5),[2,0,0]]]]]]]]]],c('File "%s", line %d, characters %d-%d: %s')],gm=c("Out of memory"),gn=c("Stack overflow"),go=c("Pattern matching failed"),gp=c("Assertion failed"),gq=c("Undefined recursive module"),by=[0,0];function
a0(c,b){function
d(a){function
f(a){if(a)return b(a[1]);if(c===br)return b(gm);if(c===cj)return b(gn);if(c[1]===ci){var
d=c[2],g=d[3],j=d[2],k=d[1],l=g+5|0;return r(N,bz,function(a){return bE(a,k,j,g,l,go,b)})}if(c[1]===t){var
e=c[2],h=e[3],m=e[2],n=e[1],o=h+6|0;return r(N,bz,function(a){return bE(a,n,m,h,o,gp,b)})}if(c[1]!==cl)return r(cy,c,b);var
f=c[2],i=f[3],p=f[2],q=f[1],s=i+6|0;return r(N,bz,function(a){return bE(a,q,p,i,s,gq,b)})}if(!a)return f(0);var
e=a[2],g=a[1];aT(function(a){return ai(d,e)});return G(g,c,function(a){V();return a?f([0,a[1]]):ai(d,e)})}return d(by[1])}var
gB=[0,[2,0,[12,10,0]],c("%s\n")],gr=c("Raised at"),gs=c("Re-raised at"),gt=c("Raised by primitive operation at"),gu=c("Called from"),gv=[0,[12,32,[4,0,0,0,0]],c(" %d")],gz=[0,[11,c("s "),[4,0,0,0,[12,45,[4,0,0,0,0]]]],c("s %d-%d")],gw=c(" (inlined)"),gy=c(f),gx=[0,[2,0,[12,32,[2,0,[11,c(' in file "'),[2,0,[12,34,[2,0,[11,c(", line"),[2,0,[11,c(dq),[4,0,0,0,[12,45,[4,0,0,0,0]]]]]]]]]]]]],c('%s %s in file "%s"%s, line%s, characters %d-%d')],gA=[0,[2,0,[11,c(" unknown location"),0]],c("%s unknown location")];function
bB(o,b,c){var
d=g_(b),g=d.length-2|0;function
j(){return c()}function
i(b){var
a=dL(d,b)[b+1];function
f(a){return a?0===b?gr:gs:0===b?gt:gu}function
c(a){function
c(a){var
c=b+1|0;return g!==b?ai(i,c):j()}if(!a)return c(0);var
d=a[1];return e(aZ,o,gB,function(a){return G(a,d,c)})}if(0!==a[0]){if(a[1])return c(0);var
n=f(0);return r(N,gA,function(a){return G(a,n,function(a){return c([0,a])})})}function
h(j){var
b=a[5],d=a[4],e=a[8]?gw:gy,g=a[2],h=a[9],i=f(a[1]);return r(N,gx,function(a){return gS(a,i,h,g,e,j,d,b,function(a){return c([0,a])})})}if(a[3]===a[6]){var
k=a[3];return r(N,gv,function(a){return G(a,k,h)})}var
l=a[6],m=a[3];return r(N,gz,function(a){return a1(a,m,l,h)})}return g<0?j():i(0)}function
cz(a){for(;;){var
b=by[1],c=1-gZ(by,0,b,[0,a,b]);if(!c)return c}}var
cI="Fatal error: exception %s\n",cE=0,gG=[0,[11,c(bM),[2,0,[12,10,0]]],c(cI)],gH=[0,[11,c("Fatal error in uncaught exception handler: exception "),[2,0,[12,10,0]]],c("Fatal error in uncaught exception handler: exception %s\n")],gF=c("Fatal error: out of memory in uncaught exception handler"),gD=[0,[11,c(bM),[2,0,[12,10,0]]],c(cI)],gC=[0,c(f),c("(Cannot print locations:\n bytecode executable program file not found)"),c("(Cannot print locations:\n bytecode executable program file appears to be corrupt)"),c("(Cannot print locations:\n bytecode executable program file has wrong magic number)"),c("(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)")],gE=[0];ca(c(cM),function(i,b,c){aT(function(a){return c(0)});function
h(a){V();return c(a)}aT(function(a){if(a===br)return h(cm(gF));var
b=V();return b(g(a,0))});var
d=b?gE:dS(0);function
f(a){function
f(a){V();return h(a)}aT(function(c){var
b=dS(0);return r(a0,i,function(g){return e(aZ,W,gG,function(a){return G(a,g,function(a){return e(bB,W,d,function(a){return r(a0,c,function(c){return e(aZ,W,gH,function(a){return G(a,c,function(a){return e(bB,W,b,function(a){return f(af(W))})})})})})})})})});return r(a0,i,function(b){return e(aZ,W,gD,function(a){return G(a,b,function(a){return e(bB,W,d,function(a){var
b=hB(0);if(b<0){var
c=aV(b);cm(dL(gC,c)[c+1])}var
d=af(W);V();return f(d)})})})})}aT(f);return r(bs,cE,function(a){V();return f(0)})});function
bC(a,b){var
c=bi(b)===n?b:b[1];ca(a,c)}var
cA=[n,c("Stdlib__Effect.Unhandled"),au(0)],gI=[0,[11,c("Stdlib.Effect.Unhandled("),[2,0,[12,41,0]]],c("Stdlib.Effect.Unhandled(%s)")];cz(function(a,b){return a[1]===cA?r(cy,a[2],function(c){return r(N,gI,function(a){return G(a,c,function(a){return b([0,a])})})}):b(0)});bC(c(bU),[0,cA,[n,c("Stdlib__Effect.Should_not_see_this__"),au(0)]]);bC(c(dk),[n,c("Stdlib__Effect.Continuation_already_resumed"),au(0)]);var
cB=[n,c("Jsoo_runtime.Error.Exn"),au(0)];bC(c(bQ),[0,cB,[0]]);var
ah=d;ah.String;ah.RegExp;ah.Object;ah.Array;ah.Date;ah.Math;function
cC(a){return R(a.toString())}ah.JSON;var
gL=ah.Error;cz(function(a,b){return a
instanceof
gL?b([0,cC(a)]):a[1]===cB?b([0,cC(a[2])]):b(0)});var
cD=[n,c("Repro.Await"),au(0)];function
bD(a){console.log(b7(a));return 0}var
gP=c("returned"),gN=c("exception: ");function
gJ(a,b,c){return r(function(a,b){return b(a)},b,cb(a,a,c))}function
gM(a,b){return r(a0,a,function(a){return b(bD(aU(gN,a)))})}function
gO(a,b){return b(bD(gP))}var
gR=c("continued");function
gQ(a,b){return hI(cD,function(a){return b(bD(gR))})}function
gK(a,b,c,d){var
f=a===cD?1:0,g=f?[0,function(c){setTimeout(dU(function(a,b){return e(gJ,c,0,b)}),0.);return 0}]:f;if(!g)return hK(a,b,c,d);var
h=g[1];b[2]=c;return d(h(b))}aA(function(a){var
b=gW(gO,gM,gK);return r(gQ,0,cb(b,b,a))},[]);aA(bs,[cE]);return}(globalThis));
