// Generated by js_of_ocaml
//# buildInfo:effects=double-translation, kind=exe, use-js-string=false, version=6.3.2
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(n){"use strict";function
a(a,b){a.cps=b;return a}var
fr=function(){function
d(c,b){var
h=c.l>=0?c.l:c.l=c.length,j=b.length,e=h-j;if(e===0)return c.apply(null,b);else if(e<0){var
f=c(...b.slice(0,h));if(typeof
f!=="function")return f;return d(f,b.slice(h))}else{var
k=b.slice();k.length=j;var
i=a(function(...a){if(a.length===0)a=[undefined];return d(c,b.concat(a))},function(...a){if(a.length===0)a=[undefined];return g(c,k.concat(a))});i.l=e;i.cps.l=e+1;return i}}function
g(c,b){if(!c.cps){var
f=b.pop();return f(d(c,b))}var
i=c.cps.l>=0?c.cps.l:c.cps.l=c.cps.length,e=b.length,h=i-e;if(h===0)return c.cps.apply(null,b);else if(h<0){var
l=b.slice(i-1),f=b[e-1];b=b.slice(0,i);b[i-1]=function(a){var
b=l.slice();b[b.length-1]=f;return g(a,b)};return c.cps.apply(null,b)}else{e--;var
j=b.slice();j.length=e;var
k=a(function(...a){if(a.length===0)a=[undefined];return d(c,j.concat(a))},function(...a){if(a.length===0)a=[undefined];return g(c,j.concat(a))}),f=b[e];k.l=h;k.cps.l=h+1;return f(k)}}return[d,g]}(),aT=fr[1],q={k:0,x:0,h:0,e:0};function
cy(){var
a=q.e;q.e=0;q=a;return a.k}var
ao=fr[0],bK=0;function
Y(){return--bK>0}function
_(a,b,c){return{joo_tramp:a,joo_args:b,joo_direct:c}}function
fh(a,b){var
c=[b,cy()];return Y()?aT(a,c):_(a,c,0)}function
hY(a){var
b=q.h[1];return fh(b,a)}function
hX(a){var
b=q.h[2];return fh(b,a)}function
hW(a,b,c){var
d=[0,a,b,c];return{k:hY,x:{h:hX,t:0},h:d,e:0}}function
hZ(a,b,c,d){if(a[b+1]===c){a[b+1]=d;return 1}return 0}var
f="";function
bM(a,b,c){var
e=String.fromCharCode;if(b===0&&c<=4096&&c===a.length)return e.apply(null,a);var
g=f,d=1024;for(;0<c;b+=d,c-=d)g+=e.apply(null,a.subarray(b,b+Math.min(c,d)));return g}function
bA(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aw(a,b,c,d,e){if(e===0)return 0;if(d===0&&(e>=c.l||c.t===2&&e>=c.c.length)){c.c=a.t===4?bM(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else if(c.t===2&&d===c.c.length){c.c+=a.t===4?bM(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else{if(c.t!==4)bA(c);var
g=a.c,h=c.c;if(a.t===4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aF(a){return a}function
a7(a,b,c,d,e){aw(aF(a),b,c,d,e);return 0}var
fQ={};function
iR(a){if(fQ[a])return fQ[a];var
b=n.process;if(b&&b.env&&b.env[a]!==undefined)return b.env[a];if(n.jsoo_env&&typeof
n.jsoo_env[a]==="string")return n.jsoo_env[a]}var
bI=0;(function(){var
c=iR("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]==="b"){bI=1;break}else if(b[a].startsWith("b="))bI=+b[a].slice(2);else
continue}}());var
iI=bI,K=[0],u=248;function
h_(a,b){if(!a.js_error||b||a[0]===u)a.js_error=new
n.Error("Js exception containing backtrace");return a}function
g(a,b){return bI&&iI?h_(a,b):a}function
fI(a,b){throw g([0,a,b])}var
iS=new
TextDecoder();function
cC(a){if(a.t!==4)bA(a);return a.c}function
az(a,b){return b.repeat(a)}function
aU(a){if(a.t===2)a.c+=az(a.l-a.c.length,"\0");else
a.c=bM(a.c,0,a.c.length);a.t=0}var
a5=127;function
fP(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>a5)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}class
ai{constructor(a,b,c){this.t=a;this.c=b;this.l=c}toString(){switch(this.t){case
9:case
8:return this.c;case
4:case
2:aU(this);case
0:if(fP(this.c))this.t=9;else
this.t=8;return this.c}}toUtf16(){if(this.t===9)return this.c;var
a=cC(this);return iS.decode(a)}slice(){var
a=this.t===4?this.c.slice():this.c;return new
ai(this.t,a,this.l)}}function
fp(a){return new
ai(0,a,a.length)}function
c(a){return fp(a)}function
fK(a,b){fI(a,c(b))}function
C(a){fK(K.Invalid_argument,a)}var
b6="index out of bounds";function
h3(){C(b6)}var
aa=0xff;function
k(a,b,c){c&=aa;if(a.t!==4){if(b===a.c.length){a.c+=String.fromCharCode(c);if(b+1===a.l)a.t=0;return 0}bA(a)}a.c[b]=c;return 0}function
ax(a,b,c){if(b>>>0>=a.l)h3();return k(a,b,c)}function
bx(a,b){switch(a.t&6){case
0:return a.c.charCodeAt(b);case
2:if(b>=a.c.length)return 0;return a.c.charCodeAt(b);case
4:return a.c[b]}}function
bw(){C(b6)}function
bz(a,b){if(b>>>0>=a.length-1)bw();return a}function
h6(a){if(Number.isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!==0)return 1;return 2}return Number.isNaN(a)?4:3}function
fu(){return[0]}function
E(a){if(a<0)C("Bytes.create");return new
ai(a?2:9,f,a)}function
h$(a,b,c,d){if(c>0)if(b===0&&(c>=a.l||a.t===2&&c>=a.c.length))if(d===0){a.c=f;a.t=2}else{a.c=az(c,String.fromCharCode(d));a.t=c===a.l?0:2}else{if(a.t!==4)bA(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
bb(a){a.t&6&&aU(a);return a.c}var
aD="-",aS="+",am=" ",V="0";function
cx(a){a=bb(a);var
e=a.length;if(e>31)C("format_int: format too long");var
b={justify:aS,signstyle:aD,filler:am,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=aD;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=V;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;break;case"d":case"i":b.signedconv=true;b.base=10;break;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}var
eH="0x";function
cm(a,b){if(a.uppercase)b=b.toUpperCase();var
g=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!==aD))g++;if(a.alternate){if(a.base===8)g+=1;if(a.base===16)g+=2}var
d=f;if(a.justify===aS&&a.filler===am)for(var
e=g;e<a.width;e++)d+=am;if(a.signedconv)if(a.sign<0)d+=aD;else if(a.signstyle!==aD)d+=a.signstyle;if(a.alternate&&a.base===8)d+=V;if(a.alternate&&a.base===16)d+=a.uppercase?"0X":eH;if(a.justify===aS&&a.filler===V)for(var
e=g;e<a.width;e++)d+=V;d+=b;if(a.justify===aD)for(var
e=g;e<a.width;e++)d+=am;return c(d)}var
aE=".",cg="nan";function
bB(a,b){function
k(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=Number.parseInt(a.toString().split(aS)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=az(c,V);if(b>0)a=a+aE+az(b,V);return a}else
return a.toFixed(b)}}var
c,f=cx(a),e=f.prec<0?6:f.prec;if(b<0||b===0&&1/b===Number.NEGATIVE_INFINITY){f.sign=-1;b=-b}if(Number.isNaN(b)){c=cg;f.filler=am}else if(!Number.isFinite(b)){c="inf";f.filler=am}else{var
h="e";switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+V+c.slice(d-1);break;case"f":c=k(b,e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
j=c.indexOf(h),i=+c.slice(j+1);if(i<-4||b>=1e21||b.toFixed(0).length>e){var
d=j-1;while(c.charAt(d)===V)d--;if(c.charAt(d)===aE)d--;c=c.slice(0,d+1)+c.slice(j);d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+V+c.slice(d-1);break}else{var
g=e;if(i<0){g-=i+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)===V)d--;if(c.charAt(d)===aE)d--;c=c.slice(0,d+1)}}break}}return cm(f,c)}var
b9="%d";function
a9(a,b){if(bb(a)===b9)return c(f+b);var
d=cx(a);if(b<0)if(d.signedconv){d.sign=-1;b=-b}else
b>>>=0;var
e=b.toString(d.base);if(d.prec>=0){d.filler=am;var
g=d.prec-e.length;if(g>0)e=az(g,V)+e}return cm(d,e)}var
iG=0;function
aH(){return iG++}var
b5="Failure";function
aG(a){if(!K.Failure)K.Failure=[u,c(b5),-3];fK(K.Failure,a)}function
ct(a){return a.toUtf16()}var
cD=n.Deno?.build?.os==="windows"||n.process?.platform==="win32";function
bP(){return n.process?.versions?.node!==undefined}var
ad="/";function
iU(){function
a(a){if(a.charAt(0)===ad)return[f,a.slice(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||f,e=c.length>0&&c.charAt(1)!==":";if(b[2]||e){var
d=b[1]||f,g=b[2]||f;return[d,a.slice(d.length+g.length)]}return}return cD?b:a}var
cF=iU();function
fN(a){return a.slice(-1)!==ad?a+ad:a}if(bP()&&n.process&&n.process.cwd)var
a8=n.process.cwd().replace(/\\/g,ad);else
var
a8="/static";a8=fN(a8);function
iz(a){a=ct(a);if(!cF(a))a=a8+a;var
e=cF(a),d=e[1].split(/[/\\]/),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}var
iT=new
TextEncoder();function
h5(a){if(fP(a))return new
ai(9,a,a.length);else{var
b=iT.encode(a);return new
ai(4,b,b.length)}}function
Z(a){return h5(a)}function
L(a){fI(K.Sys_error,Z(a))}function
fJ(a,b){throw g([0,a].concat(b))}var
aQ="EINVAL",b7="EISDIR",cb="ESPIPE",aR="EBADF",eU="ENOTEMPTY",bt="ENOTDIR",a2="ENOENT",cf="EEXIST",iV=["E2BIG","EACCES","EAGAIN",aR,"EBUSY","ECHILD","EDEADLK","EDOM",cf,"EFAULT","EFBIG","EINTR",aQ,"EIO",b7,"EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",a2,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",bt,eU,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS",cb,"ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
fS(a,b,c,d){var
e=iV.indexOf(a);if(e<0){if(d==null)d=-9999;e=[0,-d]}var
g=[e,Z(b||f),Z(c||f)];return g}var
fF={};function
ay(a){return fF[a]}var
e0="Unix.Unix_error",eM=": ",b8=", ";function
x(a,b,c,d,e){var
f=ay(e0);if(a&&f)fJ(f,fS(b,c,e));else{var
d=b+eM+d+b8+c;if(e!==undefined)d+=" '"+e+"'";L(d)}}function
bF(a){return a
instanceof
ai}function
cs(a){return bF(a)}function
h4(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
ai(4,a,a.length)}var
br="no such file or directory";function
cz(a,b){x(b,a2,br,a)}function
fq(a){return new
ai(4,a,a.length)}function
ab(a){return a.l}function
fd(){}class
av
extends
fd{constructor(a){super();this.data=a}truncate(a){var
b=this.data,c=ab(b);this.data=E(a|0);aw(b,0,this.data,0,Math.min(a,c))}length(){return ab(this.data)}write(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=E(a+d),g=this.data;this.data=f;aw(g,0,this.data,0,e)}aw(fq(b),c,this.data,a,d);return d}read(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d>0){var
f=E(d|0);aw(this.data,a,f,0,d);b.set(cC(f),c);return d}return 0}}var
a3="bad file descriptor",e$="write",ex="read",bs="lseek",a6="invalid argument";class
hT{constructor(a,b,c){this.file=b;this.name=a;this.flags=c;this.offset=0;this.seeked=false}err_closed(a,b){x(b,aR,a,a3)}length(){if(this.file)return this.file.length();this.err_closed("length")}truncate(a,b){var
c="truncate";if(this.file){if(!(this.flags.wronly||this.flags.rdwr))x(b,aQ,c,a6);return this.file.truncate(a)}this.err_closed(c,b)}write(a,b,c,d){if(this.file&&(this.flags.wronly||this.flags.rdwr)){var
e=this.offset;c=this.file.write(e,a,b,c);this.offset+=c;return c}this.err_closed(e$,d)}read(a,b,c,d){if(this.file&&!this.flags.wronly){var
e=this.offset;c=this.file.read(e,a,b,c);this.offset+=c;return c}this.err_closed(ex,d)}seek(a,b,c){switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)x(c,aQ,bs,a6);this.offset=a;this.seeked=true;return a}pos(){return this.offset}close(){if(!this.file)this.err_closed("close");this.file=undefined}check_stream_semantics(a){if(!this.file)return this.err_closed(a,1)}}var
eF="illegal operation on a directory",eN="file already exists",ce="open",eo="not a directory";class
fc{constructor(a,b){this.content={};this.root=a;this.lookupFun=b}nm(a){return this.root+a}create_dir_if_needed(a){var
d=a.split(ad),c=f;for(var
b=0;b<d.length-1;b++){c+=d[b]+ad;if(this.content[c])continue;this.content[c]=Symbol("directory")}}slash(a){return/\/$/.test(a)?a:a+ad}lookup(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(Z(this.root),Z(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
av(aF(b[1]))}}}exists(a,b){if(a===f)return 1;var
c=this.slash(a);if(this.content[c])return 1;if(!b)this.lookup(a);return this.content[a]?1:0}isFile(a){return this.exists(a)&&!this.is_dir(a)?1:0}rename_dir(a,b){if(this.exists(b)){if(!this.is_dir(b))L(this.nm(b)+" : file already exists and is not a directory");if(this.readdir(b).length>0)L(this.nm(b)+" : directory not empty")}var
d=this.slash(a),c=this.slash(b);this.create_dir_if_needed(c);for(const
b
of
this.readdir(a))this.rename(d+b,c+b);delete
this.content[d]}rename(a,b){if(!this.exists(a))L(this.nm(a)+" : no such file or directory");if(this.is_dir(a))this.rename_dir(a,b);else{if(this.exists(b)&&this.is_dir(b))L(this.nm(b)+" : file already exists and is a directory");this.content[b]=this.content[a];delete
this.content[a]}}mkdir(a,b,c){var
e="mkdir";if(this.exists(a))x(c,cf,e,eN,this.nm(a));var
d=/^(.*)\/[^/]+/.exec(a);d=d?.[1]||f;if(!this.exists(d))x(c,a2,e,br,this.nm(a));if(!this.is_dir(d))x(c,bt,e,eo,this.nm(a));this.create_dir_if_needed(this.slash(a))}rmdir(a,b){var
d=a===f?f:this.slash(a),c="rmdir";if(!this.exists(a))x(b,a2,c,br,this.nm(a));if(!this.is_dir(a))x(b,bt,c,eo,this.nm(a));for(var
e
in
this.content)if(e.startsWith(d)&&e!==d)x(b,eU,c,"directory not empty",this.nm(a));delete
this.content[d]}readdir(a){var
d=a===f?f:this.slash(a);if(!this.exists(a))L(a+": No such file or directory");if(!this.is_dir(a))L(a+": Not a directory");var
h={},g=[];for(var
c
in
this.content)if(c.startsWith(d)&&c!==d){var
e=c.indexOf(ad,d.length);if(e<0)e=undefined;var
b=c.slice(d.length,e);if(b&&!h[b]){h[b]=true;g.push(b)}}return g}opendir(a,b){var
c=this.readdir(a),d=false,e=0,f="readdir";return{readSync:function(){if(d)x(b,aR,f,a3);if(e===c.length)return null;var
a=c[e];e++;return{name:a}},closeSync:function(){if(d)x(b,aR,f,a3);d=true;c=[]}}}is_dir(a){if(a===f)return true;var
b=this.slash(a);return this.content[b]?1:0}unlink(a,b){if(!this.exists(a,true))x(b,a2,"unlink",br,a);delete
this.content[a];return 0}access(a,b,c){this.lookup(a);if(this.content[a]){if(this.is_dir(a))x(c,"EACCESS","access","permission denied,",this.nm(a))}else
cz(this.nm(a),c);return 0}open(a,b,c,d){var
e;this.lookup(a);if(this.content[a]){if(this.is_dir(a))x(d,b7,ce,eF,this.nm(a));if(b.create&&b.excl)x(d,cf,ce,eN,this.nm(a));e=this.content[a];if(b.truncate)e.truncate(0)}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
av(E(0));e=this.content[a]}else
cz(this.nm(a),d);return new
hT(this.nm(a),e,b)}truncate(a,b,c){var
d;this.lookup(a);if(this.content[a]){if(this.is_dir(a))x(c,b7,ce,eF,this.nm(a));d=this.content[a];d.truncate(b)}else
cz(this.nm(a),c)}register(a,b){var
c;if(this.content[a])L(this.nm(a)+" : file already exists");if(bF(b))c=new
av(b);if(cs(b))c=new
av(aF(b));else if(Array.isArray(b))c=new
av(h4(b));else if(typeof
b==="string")c=new
av(fp(b));else if(b.toString){var
d=aF(Z(b.toString()));c=new
av(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
L(this.nm(a)+" : registering file with invalid content type")}}function
v(a,b,c){var
d=ay(e0);if(b&&d){var
e=fS(a.code,c||a.syscall,a.path,a.errno);fJ(d,e)}else
L(a.toString())}var
a$=Math.pow(2,-24);function
fG(a){throw a}function
fL(){fG(K.Division_by_zero)}var
W=0xffff,ae=0x8000,N=0xffffff,eP=0x000000;class
s{constructor(a,b,c){this.lo=a&N;this.mi=b&N;this.hi=c&W;this.caml_custom="_j"}static
UNSIGNED_MAX=new
s(N,N,W);static
SIGNED_MAX=new
s(N,N,0x7fff);static
SIGNED_MIN=new
s(eP,eP,ae);slice(){return new
s(this.lo,this.mi,this.hi)}ucompare(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}compare(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}neg(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
s(a,b,c)}add(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),d=this.hi+a.hi+(c>>24);return new
s(b,c,d)}sub(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),d=this.hi-a.hi+(c>>24);return new
s(b,c,d)}mul(a){var
b=this.lo*a.lo,c=(b*a$|0)+this.mi*a.lo+this.lo*a.mi,d=(c*a$|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
s(b,c,d)}isZero(){return(this.lo|this.mi|this.hi)===0}isNeg(){return this.hi<<16<0}and(a){return new
s(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)}or(a){return new
s(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)}xor(a){return new
s(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)}shift_left(a){a=a&63;if(a===0)return this;if(a<24)return new
s(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
s(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
s(0,0,this.lo<<a-48)}shift_right_unsigned(a){a=a&63;if(a===0)return this;if(a<24)return new
s(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
s(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
s(this.hi>>a-48,0,0)}shift_right(a){a=a&63;if(a===0)return this;var
c=this.hi<<16>>16;if(a<24)return new
s(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
s(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,b&W);return new
s(this.hi<<16>>a-32,b,b)}lsl1(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&N;this.lo=this.lo<<1&N}lsr1(){this.lo=(this.lo>>>1|this.mi<<23)&N;this.mi=(this.mi>>>1|this.hi<<23)&N;this.hi=this.hi>>>1}udivmod(a){var
d=0,c=this.slice(),b=a.slice(),e=new
s(0,0,0);while(c.ucompare(b)>0){d++;b.lsl1()}while(d>=0){d--;e.lsl1();if(c.ucompare(b)>=0){e.lo++;c=c.sub(b)}b.lsr1()}return{quotient:e,modulus:c}}div(a){var
b=this;if(a.isZero())fL();var
d=b.hi^a.hi;if(b.hi&ae)b=b.neg();if(a.hi&ae)a=a.neg();var
c=b.udivmod(a).quotient;if(d&ae)c=c.neg();return c}mod(a){var
b=this;if(a.isZero())fL();var
d=b.hi;if(b.hi&ae)b=b.neg();if(a.hi&ae)a=a.neg();var
c=b.udivmod(a).modulus;if(d&ae)c=c.neg();return c}toInt(){return this.lo|this.mi<<24}toFloat(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo}toArray(){return[this.hi>>8,this.hi&aa,this.mi>>16,this.mi>>8&aa,this.mi&aa,this.lo>>16,this.lo>>8&aa,this.lo&aa]}lo32(){return this.lo|(this.mi&aa)<<24}hi32(){return this.mi>>>8&W|this.hi<<16}}function
is(a){if(a<0)a=Math.ceil(a);return new
s(a&N,Math.floor(a*a$)&N,Math.floor(a*a$*a$)&W)}var
an=1000;function
cE(a,b){var
c;if(a.isFile())c=0;else if(a.isDirectory())c=1;else if(a.isCharacterDevice())c=2;else if(a.isBlockDevice())c=3;else if(a.isSymbolicLink())c=4;else if(a.isFIFO())c=5;else if(a.isSocket())c=6;return[0,a.dev,a.ino|0,c,a.mode,a.nlink,a.uid,a.gid,a.rdev,b?is(a.size):a.size|0,a.atimeMs/an,a.mtimeMs/an,a.ctimeMs/an]}function
O(a){return ab(a)}function
bL(a,b){return bx(a,b)}function
iY(a){var
d=O(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=bL(a,b);return c}var
eI="illegal seek",b$="node:fs";class
ci
extends
fd{constructor(a,b){super();this.fs=require(b$);this.fd=a;this.flags=b;try{var
c=this.fs.fstatSync(a);b.noSeek=c.isCharacterDevice()||c.isFIFO()||c.isSocket();this.offset=this.flags.append?c.size:0}catch(f){b.noSeek=true;this.offset=0}this.seeked=false}truncate(a,b){try{this.fs.ftruncateSync(this.fd,a|0);if(this.offset>a)this.offset=a}catch(f){v(f,b)}}isatty(){var
a=require("node:tty");return a.isatty(this.fd)?1:0}length(){try{return this.fs.fstatSync(this.fd).size}catch(f){L(f.toString())}}write(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.writeSync(this.fd,a,b,c);else
var
e=this.fs.writeSync(this.fd,a,b,c,this.offset);this.offset+=e}catch(f){v(f,d)}return e}read(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.readSync(this.fd,a,b,c);else
var
e=this.fs.readSync(this.fd,a,b,c,this.offset);this.offset+=e;return e}catch(f){v(f,d)}}seek(a,b,c){if(this.flags.noSeek)x(c,cb,bs,eI);switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)x(c,aQ,bs,a6);this.offset=a;this.seeked=true;return this.offset}pos(){return this.offset}stat(a){try{var
b=this.fs.fstatSync(this.fd);return cE(b,a)}catch(f){v(f,1)}}chmod(a){try{this.fs.fchmodSync(this.fd,a);return 0}catch(f){v(f,1)}}sync(){try{this.fs.fsyncSync(this.fd);return 0}catch(f){v(f,1)}}close(a){try{this.fs.closeSync(this.fd);return 0}catch(f){v(f,a)}}check_stream_semantics(a){try{var
b=this.fs.fstatSync(this.fd)}catch(f){v(f,1,a)}if(!(b.isFile()||b.isCharacterDevice()||b.isFIFO()||b.isSocket()))x(1,aQ,a,a6)}}class
fe{constructor(a){this.fs=require(b$);this.root=a}nm(a){return this.root+a}exists(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}}isFile(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){L(f.toString())}}mkdir(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){v(f,c)}}rmdir(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){v(f,b)}}readdir(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){v(f,b)}}is_dir(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){L(f.toString())}}unlink(a,b){try{this.fs.unlinkSync(this.nm(a));return 0}catch(f){v(f,b)}}utimes(a,b,c,d){try{if(b===0&&c===0){b=new
Date().getTime()/an;c=b}this.fs.utimesSync(this.nm(a),b,c);return 0}catch(f){v(f,d)}}truncate(a,b,c){try{this.fs.truncateSync(this.nm(a),b|0);return 0}catch(f){v(f,c)}}access(a,b,c){var
d=this.fs.constants,e=0;for(var
f
in
b)switch(f){case"r":e|=d.R_OK;break;case"w":e|=d.W_OK;break;case"x":e|=cD?d.R_OK:d.X_OK;break;case"f":e|=d.F_OK;break}try{this.fs.accessSync(this.nm(a),e);return 0}catch(f){v(f,c)}}open(a,b,c,d){var
f=this.fs.constants,e=0;for(var
h
in
b)switch(h){case"rdonly":e|=f.O_RDONLY;break;case"wronly":e|=f.O_WRONLY;break;case"rdwr":e|=f.O_RDWR;break;case"append":e|=f.O_APPEND;break;case"create":e|=f.O_CREAT;break;case"truncate":e|=f.O_TRUNC;break;case"excl":e|=f.O_EXCL;break;case"binary":e|=f.O_BINARY;break;case"text":e|=f.O_TEXT;break;case"nonblock":e|=f.O_NONBLOCK;break;case"noctty":e|=f.O_NOCTTY;break;case"dsync":e|=f.O_DSYNC;break;case"sync":e|=f.O_SYNC;break}try{var
g=this.fs.openSync(this.nm(a),e,c);return new
ci(g,b)}catch(f){v(f,d)}}slash(a){return/\/$/.test(a)?a:a+ad}rename(a,b,c){if(cD)try{var
d=this.nm(b),e=this.nm(a),h,g;if((h=this.fs.statSync(d,{throwIfNoEntry:false}))&&(g=this.fs.statSync(e,{throwIfNoEntry:false}))&&g.isDirectory())if(h.isDirectory()){if(!this.slash(d).startsWith(this.slash(e)))try{this.fs.rmdirSync(d)}catch{}}else{var
f=new
Error(`ENOTDIR: not a directory, rename '${e}' -> '${d}'`);throw Object.assign(f,{errno:-20,code:bt,syscall:"rename",path:d})}this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){v(f,c)}else
try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){v(f,c)}}stat(a,b,c){try{var
d=this.fs.statSync(this.nm(a));return cE(d,b)}catch(f){v(f,c)}}lstat(a,b,c){try{var
d=this.fs.lstatSync(this.nm(a));return cE(d,b)}catch(f){v(f,c)}}chmod(a,b,c){try{this.fs.chmodSync(this.nm(a),b);return 0}catch(f){v(f,c)}}link(a,b,c){try{this.fs.linkSync(this.nm(a),this.nm(b));return 0}catch(f){v(f,c)}}symlink(a,b,c,d){try{this.fs.symlinkSync(b,this.nm(c),a===0?null:a[1]?"dir":"file");return 0}catch(f){v(f,d)}}readlink(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return Z(c)}catch(f){v(f,b)}}opendir(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){v(f,b)}}}function
fz(a){var
b=cF(a);if(!b)return;return b[0]+ad}var
bJ=fz(a8)||aG("unable to compute caml_root"),aW=[];if(bP())aW.push({path:bJ,device:new
fe(bJ)});else
aW.push({path:bJ,device:new
fc(bJ)});var
es="/static/";aW.push({path:es,device:new
fc(es)});function
fT(a){var
g=iz(a),a=g.join(ad),f=fN(a),c;for(var
d=0;d<aW.length;d++){var
b=aW[d];if(f.search(b.path)===0&&(!c||c.path.length<b.path.length))c={path:b.path,device:b.device,rest:a.slice(b.path.length,a.length)}}if(!c&&bP()){var
e=fz(a);if(e?.match(/^[a-zA-Z]:\/$/)){var
b={path:e,device:new
fe(e)};aW.push(b);c={path:b.path,device:b.device,rest:a.slice(b.path.length,a.length)}}}if(c)return c;L("no device found for "+f)}function
h9(a,b){var
c=fT(a);if(!c.device.register)aG("cannot register file");c.device.register(c.rest,b);return 0}function
fO(a,b){var
a=Z(a),b=c(b);return h9(a,b)}function
ib(){var
b=[].concat(n.jsoo_fs_tmp||[],n.caml_fs_tmp||[]);if(b)for(var
a=0;a<b.length;a++)fO(b[a].name,b[a].content);n.jsoo_create_file=fO;n.jsoo_fs_tmp=[];n.caml_fs_tmp=[];return 0}function
bC(a){return[0]}var
er="infinity";function
ig(a,b,c){if(!Number.isFinite(a)){if(Number.isNaN(a))return Z(cg);return Z(a>0?er:"-infinity")}var
k=a===0&&1/a===Number.NEGATIVE_INFINITY?1:a>=0?0:1;if(k)a=-a;var
e=0;if(a===0);else if(a<1)while(a<1&&e>-1022){a*=2;e--}else
while(a>=2){a/=2;e++}var
l=e<0?f:aS,g=f;if(k)g=aD;else
switch(c){case
43:g=aS;break;case
32:g=am;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(aE);if(j<0)d+=aE+az(b,V);else{var
h=j+1+b;if(d.length<h)d+=az(h-d.length,V);else
d=d.slice(0,h)}}return Z(g+eH+d+"p"+l+e.toString(10))}function
ip(a){return+a.isZero()}function
it(a){return new
s(a&N,a>>24&N,a>>31&W)}function
iu(a){return a.toInt()}function
io(a){return+a.isNeg()}function
ir(a){return a.neg()}function
il(a,b){var
c=cx(a);if(c.signedconv&&io(b)){c.sign=-1;b=ir(b)}var
d=f,i=it(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(iu(g.modulus))+d}while(!ip(b));if(c.prec>=0){c.filler=am;var
e=c.prec-d.length;if(e>0)d=az(e,V)+d}return cm(c,d)}var
by=ao;function
fA(c){return function(...a){if(a.length===0)a=[undefined];var
b=by(c,a);return b
instanceof
Function?fA(b):b}}function
fB(){return 0}function
fb(a){this.id=a}class
iA{constructor(){this.map=new
n.WeakMap();this.opened=new
n.Set()}close(a){this.opened.delete(a)}get(a){return this.map.get(a)}set(a,b){if(b.opened)this.opened.add(a);return this.map.set(a,b)}all(){return this.opened.values()}}var
bG=new
iA();function
cv(a){return bG.get(a)}function
ac(a){var
b=cv(a);if(!b.opened)L("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr===0)return 0;if(b.output)b.output(bM(b.buffer,0,b.buffer_curr));else
for(var
c=0;c<b.buffer_curr;)c+=b.file.write(b.buffer,c,b.buffer_curr-c,false);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}var
cr=65536;function
iQ(a,b){if(b.altname)try{var
d=require(b$),c=d.openSync(b.altname,"rs");return new
ci(c,b)}catch(f){}return new
ci(a,b)}var
aV=new
Array(3);class
hU
extends
av{constructor(a,b){super(E(0));this.log=function(a){return 0};if(a===1&&typeof
console.log==="function")this.log=console.log;else if(a===2&&typeof
console.error==="function")this.log=console.error;else if(typeof
console.log==="function")this.log=console.log;this.flags=b}length(){return 0}truncate(a,b){x(b,aQ,"ftruncate",a6)}write(a,b,c,d){var
f=c;if(this.log){if(c>0&&b>=0&&b+c<=a.length&&a[b+c-1]===10)c--;var
e=E(c);aw(fq(a),b,e,0,c);this.log(e.toUtf16());return f}x(d,aR,e$,a3)}read(a,b,c,d){x(d,aR,ex,a3)}seek(a,b,c){x(c,cb,bs,eI)}pos(){return-1}close(){this.log=undefined}check_stream_semantics(a){}}function
bN(a,b){var
c;if(b===undefined){b=aV.length;c=new
fb(b)}else if(aV[b])c=aV[b].chanid;else
c=new
fb(b);aV[b]={file:a,chanid:c};return b|0}function
iX(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;d.writeonly=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
e=fT(a),f=e.device.open(e.rest,d,c);return bN(f,undefined)}(function(){var
c=bP();function
a(a,b){return c?iQ(a,b):new
hU(a,b)}bN(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);bN(a(1,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),1);bN(a(2,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),2)}());var
e7=" doesn't exist",eq="fd ";function
iB(a){var
b=aV[a];if(b===undefined)L(eq+a+e7);var
d=b.file,c=b.chanid,f=null,e={file:d,offset:d.pos(),fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(cr),refill:f};bG.set(c,e);return c}function
fC(a){var
c=aV[a];if(c===undefined)L(eq+a+e7);var
b=c.file,d=c.chanid,e=b.flags.buffered!==undefined?b.flags.buffered:1,f={file:b,offset:b.pos(),fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(cr),buffered:e};bG.set(d,f);return d}function
iC(){var
a=0,d=bG.all();for(var
c
of
d){var
b=cv(c);if(b.opened&&b.out)a=[0,c,a]}return a}function
iE(a,b,c,d){var
e=cv(a);if(!e.opened)L("Cannot output to a closed channel");b=b.subarray(c,c+d);if(e.buffer_curr+b.length>e.buffer.length){var
g=new
Uint8Array(e.buffer_curr+b.length);g.set(e.buffer);e.buffer=g}switch(e.buffered){case
0:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;ac(a);break;case
1:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)ac(a);break;case
2:var
f=b.lastIndexOf(10);if(f<0){e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)ac(a)}else{e.buffer.set(b.subarray(0,f+1),e.buffer_curr);e.buffer_curr+=f+1;ac(a);e.buffer.set(b.subarray(f+1),e.buffer_curr);e.buffer_curr+=b.length-f-1}break}return 0}function
iD(a,b,c,d){var
b=cC(b);return iE(a,b,c,d)}function
fD(a,b,c,d){return iD(a,aF(b),c,d)}function
cw(a,b){var
d=c(String.fromCharCode(b));fD(a,d,0,1);return 0}var
eL=245;function
ix(a){return a===eL?1:0}var
bv=0x7c00,a4=128,b4=256,eO=0.0009765625,fx=function(){const
e=1/Number.EPSILON;function
o(a){return a+e-e}const
j=6.103515625e-5,m=65504,h=eO,i=h*j,l=h*e;function
p(a){const
b=+a;if(!Number.isFinite(b)||b===0)return b;const
e=b>0?1:-1,c=Math.abs(b);if(c<j)return e*o(c/i)*i;const
f=(1+l)*c,d=f-(f-c);if(d>m||Number.isNaN(d))return e*Number.POSITIVE_INFINITY;return e*d}var
a=512;const
b=new
Uint16Array(a),c=new
Uint8Array(a);for(let
a=0;a<b4;++a){const
e=a-a5;var
d=0x100;if(e<-24){b[a]=0x0000;b[a|d]=ae;c[a]=24;c[a|d]=24}else if(e<-14){var
f=0x0400;b[a]=f>>-e-14;b[a|d]=f>>-e-14|ae;c[a]=-e-1;c[a|d]=-e-1}else if(e<=15){b[a]=e+15<<10;b[a|d]=e+15<<10|ae;c[a]=13;c[a|d]=13}else{var
g=0xfc00;if(e<a4){b[a]=bv;b[a|d]=g;c[a]=24;c[a|d]=24}else{b[a]=bv;b[a|d]=g;c[a]=13;c[a|d]=13}}}const
k=new
ArrayBuffer(4),n=new
Float32Array(k),q=new
Uint32Array(k);return function(a){n[0]=p(a);const
e=q[0],d=e>>23&0x1ff;return b[d]+((e&0x007fffff)>>c[d])}}(),ak=new
DataView(new
ArrayBuffer(8));function
bD(a){ak.setFloat32(0,a,true);return ak.getUint32(0,true)|0}function
ik(a,b,c){return new
s(a,b,c)}var
e9=0xf,e6=0x7ff8,e5=0x7ff0;function
bE(a){ak.setFloat64(0,a,true);var
e=ak.getUint32(0,true),c=ak.getUint32(4,true),d=e&N,f=e>>>24|c<<8&N,b=c>>>16&W;if((b&e6)===e5&&(f|d|b&e9)!==0)b|=8;return ik(d,f,b)}function
ba(a){return a.toArray()}var
bq="_bigarr02";function
fn(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom===bq)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<W)a.write(16,b.dims[d]);else{a.write(16,W);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=ba(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=ba(bE(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
13:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
0:for(var
d=0;d<b.data.length;d++){var
f=bD(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,bD(e[1]));a.write(32,bD(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=ba(bE(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=ba(bE(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}var
cl=function(){var
h=Math.pow,e=31,i=1023,f=h(2,-24),g=eO;return function(a){var
d=a>>>15,c=a>>>10&e,b=a&i;if(c===e)return b===0?d===0?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:Number.NaN;if(c===0)return b*(d===0?f:-f);var
j=h(2,c-15)*(d===0?1+b*g:-1-b*g);return j}}();function
fl(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
h0(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break;case
13:c=Uint16Array;break}if(!c)C("Bigarray.create: unsupported kind");var
d=new
c(b*fl(a));return d}function
cn(a){ak.setUint32(0,a,true);return ak.getFloat32(0,true)}function
a_(a){return new
s(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
co(a){var
d=a.lo,c=a.mi,b=a.hi;if((b&e6)===e5&&(c|d|b&e9)!==0)b|=8;ak.setUint32(0,d|c<<24,true);ak.setUint32(4,c>>>8|b<<16,true);return ak.getFloat64(0,true)}function
cj(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)C("Bigarray.create: negative dimension");c=c*a[b]}return c}function
ij(a,b){return new
s(a&N,a>>>24&aa|(b&W)<<8,b>>>16&W)}function
cp(a){return a.hi32()}function
cq(a){return a.lo32()}var
h1=bq,bu=254;class
ff{constructor(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d;this.caml_custom=h1}offset(a){var
c=0;if(typeof
a==="number")a=[a];if(!Array.isArray(a))C("bigarray.js: invalid offset");if(this.dims.length!==a.length)C("Bigarray.get/set: bad number of dimensions");if(this.layout===0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])bw();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])bw();c=c*this.dims[b]+(a[b]-1)}return c}get(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return ij(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[bu,e,c];case
13:return cl(this.data[a]);default:return this.data[a]}}set(a,b){switch(this.kind){case
7:this.data[a*2+0]=cq(b);this.data[a*2+1]=cp(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;case
13:this.data[a]=fx(b);break;default:this.data[a]=b;break}return 0}fill(a){switch(this.kind){case
7:var
c=cq(a),e=cp(a);if(c===e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d===f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?d:f;break;case
13:this.data.fill(fx(a));break;default:this.data.fill(a);break}}compare(a,b){if(this.layout!==a.layout||this.kind!==a.kind){var
h=this.kind|this.layout<<8,i=a.kind|a.layout<<8;return i-h}if(this.dims.length!==a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!==a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!==e){if(!b)return Number.NaN;if(!Number.isNaN(d))return 1;if(!Number.isNaN(e))return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
13:for(var
c=0;c<this.data.length;c++){var
f=cl(this.data[c]),g=cl(a.data[c]);if(f<g)return-1;if(f>g)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0}}class
hV
extends
ff{offset(a){if(typeof
a!=="number")if(Array.isArray(a)&&a.length===1)a=a[0];else
C("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])bw();return a}get(a){return this.data[a]}set(a,b){this.data[a]=b;return 0}fill(a){this.data.fill(a);return 0}}function
fj(a,b,c,d){var
e=fl(a);if(cj(c)*e!==d.length)C("length doesn't match dims");if(b===0&&c.length===1&&e===1&&a!==13)return new
hV(a,b,c,d);return new
ff(a,b,c,d)}function
fk(a,b,c){var
k=a.read32s();if(k<0||k>16)aG("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&aa,q=r>>8&1,j=[];if(c===bq)for(var
d=0;d<k;d++){var
p=a.read16u();if(p===W){var
u=a.read32u(),v=a.read32u();if(u!==0)aG("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=cj(j),h=h0(l,f),i=fj(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)aG("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=a_(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=co(a_(g));i.set(d,m)}break;case
13:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
0:for(var
d=0;d<f;d++){var
m=cn(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=cn(a.read32s()),n=cn(a.read32s());i.set(d,[bu,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=co(a_(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=co(a_(g));i.set(d,[bu,o,n])}break}b[0]=(4+k)*4;return fj(l,q,j,h)}function
fi(a,b,c){return a.compare(b,c)}function
fE(a,b){return Math.imul(a,b)}function
af(a,b){b=fE(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=fE(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
id(a,b){if((b&bv)===bv&&(b&0x03ff)!==0)b=0x7c01;else if(b===ae)b=0;return af(a,b)}var
eY=0x80000000;function
ie(a,b){var
c=bD(b),d=0x7f800000;if((c&d)===d&&(c&0x7fffff)!==0)c=0x7f800001;else if(c===(eY|0))c=0;a=af(a,c);return a}function
ic(a,b){var
f=bE(b),d=cq(f),c=cp(f),e=0x7ff00000;if((c&e)===e&&(d|c&0xfffff)!==0){c=e;d=0x00000001}else if(c===(eY|0)&&d===0)c=0;a=af(a,d);a=af(a,c);return a}function
fm(a){var
c=cj(a.dims),d=0;switch(a.kind){case
2:case
3:case
12:if(c>b4)c=b4;var
e=0,b=0;for(b=0;b+4<=c;b+=4){e=a.data[b+0]&aa|(a.data[b+1]&aa)<<8|(a.data[b+2]&aa)<<16|a.data[b+3]<<24;d=af(d,e)}e=0;switch(c&3){case
3:e=a.data[b+2]<<16;case
2:e|=a.data[b+1]<<8;case
1:e|=a.data[b+0];d=af(d,e)}break;case
4:case
5:if(c>a4)c=a4;var
e=0,b=0;for(b=0;b+2<=c;b+=2){e=a.data[b+0]&W|a.data[b+1]<<16;d=af(d,e)}if((c&1)!==0)d=af(d,a.data[b]);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=af(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=af(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=af(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=ie(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=ic(d,a.data[b]);break;case
13:if(c>a4)c=a4;for(var
b=0;b<c;b++)d=id(d,a.data[b]);break}return d}function
ih(a,b){b[0]=4;return a.read32s()}function
iF(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:aG("input_value: native integer value too large");break;default:aG("input_value: ill-formed native integer")}}function
iv(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return a_(d)}function
iq(a,b,c){var
e=ba(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
ii(a,b,c){return a.compare(b)}function
im(a){return a.lo32()^a.hi32()}var
fv={_j:{deserialize:iv,serialize:iq,fixed_length:8,compare:ii,hash:im},_i:{deserialize:ih,fixed_length:4},_n:{deserialize:iF,fixed_length:4},_bigarray:{deserialize:function(a,b){return fk(a,b,"_bigarray")},serialize:fn,compare:fi,hash:fm},_bigarr02:{deserialize:function(a,b){return fk(a,b,bq)},serialize:fn,compare:fi,hash:fm}};function
ck(a){return fv[a.caml_custom]&&fv[a.caml_custom].compare}function
fs(a,b,c,d){var
f=ck(b);if(f){var
e=c>0?f(b,a,d):f(a,b,d);if(d&&Number.isNaN(e))return c;if(Number.isNaN(+e))return+e;if((e|0)!==0)return e|0}return c}var
eK=255,a1=252,b3=1255,bp=1010;function
ft(a){if(a===null)return bp;if(typeof
a==="number")return an;else if(bF(a))return a1;else if(cs(a))return 1252;else if(Array.isArray(a)&&a[0]===a[0]>>>0&&a[0]<=eK){var
c=a[0]|0;return c===bu?0:c}else{var
b=12520;if(a
instanceof
String)return b;else if(typeof
a==="string")return b;else if(a
instanceof
Number)return an;else if(a?.caml_custom)return b3;else if(a?.compare)return 1256;else if(typeof
a==="function")return 1247;else if(typeof
a==="symbol")return 1251}return 1001}function
iw(a,b){if(a<b)return-1;if(a===b)return 0;return 1}function
fo(a,b){a.t&6&&aU(a);b.t&6&&aU(b);return a.c<b.c?-1:a.c>b.c?1:0}function
iW(a,b){return fo(a,b)}function
h7(a,b,c){var
f=[];for(;;){if(!(c&&a===b)){var
e=ft(a),k=250;if(e===k){a=a[1];continue}var
g=ft(b);if(g===k){b=b[1];continue}if(e!==g){if(e===bp)return-1;if(g===bp)return 1;if(e===an){if(g===b3)return fs(a,b,-1,c);return-1}if(g===an){if(e===b3)return fs(b,a,1,c);return 1}return e<g?-1:1}var
i="compare: functional value";switch(e){case
247:C(i);break;case
248:var
d=iw(a[2],b[2])|0;if(d!==0)return d;break;case
249:C(i);break;case
250:C("equal: got Forward_tag, should not happen");break;case
251:C("equal: abstract value");break;case
252:if(a!==b){var
d=fo(a,b)|0;if(d!==0)return d}break;case
253:C("equal: got Double_tag, should not happen");break;case
254:C("equal: got Double_array_tag, should not happen");break;case
255:C("equal: got Custom_tag, should not happen");break;case
1247:C(i);break;case
1255:var
j=ck(a);if(j!==ck(b))return a.caml_custom<b.caml_custom?-1:1;if(!j)C("compare: abstract value");var
d=j(a,b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1256:var
d=a.compare(b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!==b){if(!c)return Number.NaN;if(!Number.isNaN(a))return 1;if(!Number.isNaN(b))return-1}break;case
1010:return 0;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!==b)return c?1:Number.NaN;break;case
1251:if(a!==b)return c?1:Number.NaN;break;case
1252:var
a=bb(a),b=bb(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;default:if(ix(e)){C("compare: continuation value");break}if(a.length!==b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1);break}}if(f.length===0)return 0;var
h=f.pop();b=f.pop();a=f.pop();if(h+1<a.length)f.push(a,b,h+1);a=a[h];b=b[h]}}function
bc(a,b){return+(h7(a,b,false)!==0)}function
aI(a){if(a===null)return bp;else if(Array.isArray(a)&&a[0]===a[0]>>>0)return a[0];else if(bF(a))return a1;else if(cs(a))return a1;else if(a
instanceof
Function||typeof
a==="function")return 247;else if(a?.caml_custom)return eK;else
return an}function
fy(a){return a.cps?a.cps:a}var
ch="Effect.Unhandled";function
cu(a){var
b=ay(ch);if(b)b=[0,b,a];else
b=[u,c(ch),aH(0)];return b}function
iH(a,b){if(q.e===0){var
g=cu(a);throw g}var
e=q.h[3],c=q;c.k=b;var
d=[eL,c,c],f=cy();return Y()?fy(e)(a,d,c,f):_(e,[a,d,c,f])}function
aj(){if(!q.x)return function(a){throw a};var
a=q.x.h;q.x=q.x.t;return a}function
bH(a){q.x={h:a,t:q.x}}function
fH(a){var
b=cu(a);throw b}var
fR=undefined;function
h2(a){var
d={},c=-1;if(a)for(var
b=1;b<a.length;b++){var
e=a[b][2];c=Math.max(c,e);d[ct(a[b][1])]=e}d.next_idx=c+1;return d}function
X(a,b,c){if(c){var
d=c;if(fR)a=by(fR,[d]);else if(K.symbols){if(!K.symidx)K.symidx=h2(K.symbols);var
e=K.symidx[d];if(e>=0)a=e;else{var
a=K.symidx.next_idx++;K.symidx[d]=a}}}K[a+1]=b;if(c)K[c]=b}function
cA(a,b){fF[bb(a)]=b;return 0}var
e3="Effect.Continuation_already_resumed";function
cB(a,b,c){if(!a)fG(ay(e3));if(b===0){b=a;while(b.e!==0)b=b.e}q.k=c;b.e=q;q=a;return a.k}function
h8(a){var
b=a[1];a[1]=0;return b}function
iJ(a,b,c,d){if(q.e===0){var
h=cu(a),i=h8(b);cB(i,c,d);throw h}var
f=q.h[3],e=q;e.k=d;c.e=e;b[2]=e;var
g=cy();return Y()?fy(f)(a,b,e,g):_(f,[a,b,e,g])}var
cd="jsError";function
bO(a){{if(Array.isArray(a))return a;var
b;if(n.RangeError&&a
instanceof
n.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=K.Stack_overflow;else if(n.InternalError&&a
instanceof
n.InternalError&&a.message&&a.message.match(/too much recursion/i))b=K.Stack_overflow;else if(a
instanceof
n.Error&&ay(cd))b=[0,ay(cd),a];else
b=[0,K.Failure,Z(String(a))];if(a
instanceof
n.Error)b.js_error=a;return b}}function
fM(a,b,c,d){var
i=bK,h=q;try{q={k:0,x:0,h:0,e:0};var
f=cB(c,d,function(a){return a}),e={joo_tramp:a,joo_args:[b,f],joo_direct:0};do{bK=40;try{e=e.joo_direct?e.joo_tramp.apply(null,e.joo_args):aT(e.joo_tramp,e.joo_args)}catch(f){if(!q.x)throw f;var
g=q.x.h;q.x=q.x.t;e={joo_tramp:g,joo_args:[bO(f)],joo_direct:1}}}while(e?.joo_args);return e}finally{bK=i;q=h}}function
aA(a,b){a.t&6&&aU(a);b.t&6&&aU(b);return new
ai(0,a.c+b.c,a.l+b.l)}function
iL(){C(b6)}function
T(a,b){if(b>>>0>=O(a))iL();return bL(a,b)}function
Q(a){return a}var
cc="arm64",eG="amd64",fg=n.process?.arch===cc?cc:eG;function
iM(a){return fg===eG?1:0}function
iN(a){return fg===cc?1:0}function
iO(){return 0x7fffffff/4|0}function
iP(a){return cr}function
iy(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}var
eJ="_";function
ia(a){var
b=f;if(a[0]===0){b+=a[1][1];if(a.length===3&&a[2][0]===0&&iy(a[1]))var
g=a[2],h=1;else
var
h=2,g=a;b+="(";for(var
e=h;e<g.length;e++){if(e>h)b+=b8;var
c=g[e];if(typeof
c==="number")b+=c.toString();else{var
d='"';if(c
instanceof
ai)b+=d+c.toString()+d;else if(typeof
c==="string")b+=d+c.toString()+d;else
b+=eJ}}b+=")"}else if(a[0]===u)b+=a[1];return b}var
b_="Fatal error: exception ",eT="Pervasives.do_at_exit",et="Printexc.handle_uncaught_exception";function
fw(a){if(Array.isArray(a)&&(a[0]===0||a[0]===u)){var
c=ay(et);if(c)by(c,[a,false]);else{var
d=ia(a),b=ay(eT);if(b)by(b,[0]);console.error(b_+d);if(a.js_error)throw a.js_error}}else
throw a}function
iK(){var
c=n.process;if(c?.on)c.on("uncaughtException",function(a,b){fw(a);c.exit(2)});else if(n.addEventListener)n.addEventListener("error",function(a){if(a.error)fw(a.error)})}iK();function
h(a,b){return(a.l>=0?a.l:a.l=a.length)===1?a(b):ao(a,[b])}function
au(a,b){return Y()?a(b):_(a,[b],1)}function
z(a,b,c){return(a.l>=0?a.l:a.l=a.length)===2?a(b,c):ao(a,[b,c])}function
S(a,b,c){return Y()?a.cps?(a.cps.l>=0?a.cps.l:a.cps.l=a.cps.length)===2?a.cps.call(null,b,c):aT(a,[b,c]):c((a.l>=0?a.l:a.l=a.length)===1?a(b):ao(a,[b])):_(a,[b,c],0)}function
B(a,b,c){return Y()?a.cps?a.cps.call(null,b,c):c(a(b)):_(a,[b,c],0)}function
bo(a,b,c,d){return Y()?a.cps?(a.cps.l>=0?a.cps.l:a.cps.l=a.cps.length)===3?a.cps.call(null,b,c,d):aT(a,[b,c,d]):d((a.l>=0?a.l:a.l=a.length)===2?a(b,c):ao(a,[b,c])):_(a,[b,c,d],0)}function
d(a,b,c,d){return Y()?a.cps?a.cps.call(null,b,c,d):d(a(b,c)):_(a,[b,c,d],0)}function
j(a,b,c,d,e){return Y()?a.cps?a.cps.call(null,b,c,d,e):e(a(b,c,d)):_(a,[b,c,d,e],0)}function
b1(a,b,c,d,e,f){return(a.l>=0?a.l:a.l=a.length)===5?a(b,c,d,e,f):ao(a,[b,c,d,e,f])}function
U(a,b,c,d,e,f){return Y()?a.cps?a.cps.call(null,b,c,d,e,f):f(a(b,c,d,e)):_(a,[b,c,d,e,f],0)}function
b2(a,b,c,d,e,f,g){return Y()?a.cps?(a.cps.l>=0?a.cps.l:a.cps.l=a.cps.length)===6?a.cps.call(null,b,c,d,e,f,g):aT(a,[b,c,d,e,f,g]):g((a.l>=0?a.l:a.l=a.length)===5?a(b,c,d,e,f):ao(a,[b,c,d,e,f])):_(a,[b,c,d,e,f,g],0)}function
em(a,b,c,d,e,f,g){return Y()?a.cps?a.cps.call(null,b,c,d,e,f,g):g(a(b,c,d,e,f)):_(a,[b,c,d,e,f,g],0)}function
hR(a,b,c,d,e,f,g,h){return(a.l>=0?a.l:a.l=a.length)===7?a(b,c,d,e,f,g,h):ao(a,[b,c,d,e,f,g,h])}function
hS(a,b,c,d,e,f,g,h,i){return Y()?a.cps?(a.cps.l>=0?a.cps.l:a.cps.l=a.cps.length)===8?a.cps.call(null,b,c,d,e,f,g,h,i):aT(a,[b,c,d,e,f,g,h,i]):i((a.l>=0?a.l:a.l=a.length)===7?a(b,c,d,e,f,g,h):ao(a,[b,c,d,e,f,g,h])):_(a,[b,c,d,e,f,g,h,i],0)}ib();var
eu="Out_of_fibers";X(12,[u,c(eu),-13],eu);var
eX="Undefined_recursive_module",bT=[u,c(eX),-12];X(11,bT,eX);var
eD="Assert_failure",p=[u,c(eD),-11];X(10,p,eD);var
eQ="Sys_blocked_io";X(9,[u,c(eQ),-10],eQ);var
eA="Stack_overflow",bS=[u,c(eA),-9];X(8,bS,eA);var
fa="Match_failure",bR=[u,c(fa),-8];X(7,bR,fa);var
e4="Not_found";X(6,[u,c(e4),-7],e4);var
e2="Division_by_zero";X(5,[u,c(e2),-6],e2);var
ey="End_of_file";X(4,[u,c(ey),-5],ey);var
eB="Invalid_argument",cG=[u,c(eB),-4];X(3,cG,eB);var
cH=[u,c(b5),-3];X(2,cH,b5);var
eW="Sys_error",cI=[u,c(eW),-2];X(1,cI,eW);var
ev="Out_of_memory",aX=[u,c(ev),-1];X(0,aX,ev);function
t(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,t(a[1])];case
1:return[1,t(a[1])];case
2:return[2,t(a[1])];case
3:return[3,t(a[1])];case
4:return[4,t(a[1])];case
5:return[5,t(a[1])];case
6:return[6,t(a[1])];case
7:return[7,t(a[1])];case
8:var
c=a[1];return[8,c,t(a[2])];case
9:var
b=a[1];return[9,b,b,t(a[3])];case
10:return[10,t(a[1])];case
11:return[11,t(a[1])];case
12:return[12,t(a[1])];case
13:return[13,t(a[1])];default:return[14,t(a[1])]}}function
M(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,M(a[1],b)];case
1:return[1,M(a[1],b)];case
2:return[2,M(a[1],b)];case
3:return[3,M(a[1],b)];case
4:return[4,M(a[1],b)];case
5:return[5,M(a[1],b)];case
6:return[6,M(a[1],b)];case
7:return[7,M(a[1],b)];case
8:var
c=a[1];return[8,c,M(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,M(a[3],b)];case
10:return[10,M(a[1],b)];case
11:return[11,M(a[1],b)];case
12:return[12,M(a[1],b)];case
13:return[13,M(a[1],b)];default:return[14,M(a[1],b)]}}function
o(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,o(a[1],b)];case
1:return[1,o(a[1],b)];case
2:var
c=a[1];return[2,c,o(a[2],b)];case
3:var
d=a[1];return[3,d,o(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,o(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,o(a[4],b)];case
6:var
k=a[3],l=a[2],m=a[1];return[6,m,l,k,o(a[4],b)];case
7:var
n=a[3],p=a[2],q=a[1];return[7,q,p,n,o(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,o(a[4],b)];case
9:var
u=a[1];return[9,u,o(a[2],b)];case
10:return[10,o(a[1],b)];case
11:var
v=a[1];return[11,v,o(a[2],b)];case
12:var
w=a[1];return[12,w,o(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,o(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,o(a[3],b)];case
15:return[15,o(a[1],b)];case
16:return[16,o(a[1],b)];case
17:var
B=a[1];return[17,B,o(a[2],b)];case
18:var
C=a[1];return[18,C,o(a[2],b)];case
19:return[19,o(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,o(a[3],b)];case
21:var
F=a[1];return[21,F,o(a[2],b)];case
22:return[22,o(a[1],b)];case
23:var
G=a[1];return[23,G,o(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,o(a[3],b)]}}function
bQ(a){throw g([0,cH,a],0)}function
aB(a){throw g([0,cG,a],0)}function
aY(a){return 0<=a?a:-a|0}var
fU=c("true"),fV=c("false");function
cJ(a){return a?fU:fV}iB(0);fC(1);var
F=fC(2);function
al(a,b){fD(a,b,0,O(b))}function
bd(a){al(F,a);cw(F,10);return ac(F)}function
be(a){var
b=iC(0);for(;;){if(!b)return 0;var
c=b[2],e=b[1];try{ac(e);b=c}catch(f){var
d=bO(f);if(d[1]!==cI)throw g(d,0);b=c}}}cA(c(eT),be);var
aC=(4*iO(0)|0)-1|0;iP(0);var
cM=iN(0);if(iM(0)){if(cM)bQ(c("Cannot determine architecture: both amd64 and arm64 detected"))}else if(!cM)bQ(c("Cannot determine architecture: must be amd64 or arm64"));function
ap(a,b){var
c=E(a);h$(c,0,a,b);return c}var
fW=c("String.sub / Bytes.sub");function
bU(a,b,c){a:{if(0<=b&&0<=c&&(ab(a)-c|0)>=b){var
d=E(c);aw(a,b,d,0,c);var
e=d;break a}var
e=aB(fW)}return Q(e)}var
fX=c("Bytes.blit");function
cT(a,b,c,d,e){if(0<=e&&0<=b&&(ab(a)-e|0)>=b&&0<=d&&(ab(c)-e|0)>=d){aw(a,b,c,d,e);return}return aB(fX)}var
fY=c("String.blit / Bytes.blit_string");function
ag(a,b,c,d,e){if(0<=e&&0<=b&&(O(a)-e|0)>=b&&0<=d&&(ab(c)-e|0)>=d){a7(a,b,c,d,e);return}return aB(fY)}var
fZ=c("Buffer.add: cannot grow buffer");function
bV(a,b){var
d=a[2],c=[0,a[1][2]];for(;;){if(c[1]>=(d+b|0))break;c[1]=2*c[1]|0}if(aC<c[1])if((d+b|0)<=aC)c[1]=aC;else
bQ(fZ);var
e=E(c[1]);cT(a[1][1],0,e,0,a[2]);a[1]=[0,e,c[1]]}function
ah(a,b){var
c=O(b),d=a[2],e=a[1],f=d+c|0,g=e[1];if(e[2]<f){bV(a,c);ag(b,0,a[1][1],a[2],c)}else
a7(b,0,g,d,c);a[2]=f}function
aJ(a){return 5===a[2]?12:-6}function
bW(a){return[0,0,E(a)]}function
cU(a,b){var
c=ab(a[2]),d=a[1]+b|0;if(c<d){var
e=c*2|0,g=d<=e?e:d,f=E(g);cT(a[2],0,f,0,c);a[2]=f}}function
aK(a,b){cU(a,1);ax(a[2],a[1],b);a[1]=a[1]+1|0}function
G(a,b){var
c=O(b);cU(a,c);ag(b,0,a[2],a[1],c);a[1]=a[1]+c|0}function
bX(a){return bU(a[2],0,a[1])}var
f0=c("@]"),f1=c("@}"),f2=c("@?"),f3=c("@\n"),f4=c("@."),f5=c("@@"),f6=c("@%"),f7=c("@");function
bf(a){if(typeof
a==="number")switch(a){case
0:return f0;case
1:return f1;case
2:return f2;case
3:return f3;case
4:return f4;case
5:return f5;default:return f6}return 2===a[0]?aA(f7,Q(ap(1,a[1]))):a[1]}var
eE="%li",e_="%ni",eR="%Li",en="%i",f8=c("%c"),f9=c("%s"),f_=c(en),f$=c(eE),ga=c(e_),gb=c(eR),gc=c("%f"),gd=c("%B"),ge=c("%{"),gf=c("%}"),gg=c("%("),gh=c("%)"),gi=c("%a"),gj=c("%t"),gk=c("%?"),gl=c("%r"),gm=c("%_r");function
bg(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
d=c[1];G(a,f8);c=d;break;case
1:var
e=c[1];G(a,f9);c=e;break;case
2:var
f=c[1];G(a,f_);c=f;break;case
3:var
g=c[1];G(a,f$);c=g;break;case
4:var
h=c[1];G(a,ga);c=h;break;case
5:var
i=c[1];G(a,gb);c=i;break;case
6:var
j=c[1];G(a,gc);c=j;break;case
7:var
k=c[1];G(a,gd);c=k;break;case
8:var
l=c[2],m=c[1];G(a,ge);bg(a,m);G(a,gf);c=l;break;case
9:var
n=c[3],o=c[1];G(a,gg);bg(a,o);G(a,gh);c=n;break;case
10:var
p=c[1];G(a,gi);c=p;break;case
11:var
q=c[1];G(a,gj);c=q;break;case
12:var
r=c[1];G(a,gk);c=r;break;case
13:var
s=c[1];G(a,gl);c=s;break;default:var
t=c[1];G(a,gm);c=t}}}function
y(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,y(a[1])];case
1:return[1,y(a[1])];case
2:return[2,y(a[1])];case
3:return[3,y(a[1])];case
4:return[4,y(a[1])];case
5:return[5,y(a[1])];case
6:return[6,y(a[1])];case
7:return[7,y(a[1])];case
8:var
b=a[1];return[8,b,y(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,y(a[3])];case
10:return[10,y(a[1])];case
11:return[11,y(a[1])];case
12:return[12,y(a[1])];case
13:return[13,y(a[1])];default:return[14,y(a[1])]}}var
w=0;function
H(a){if(typeof
a==="number")return[0,,function(a){},,function(a){}];switch(a[0]){case
0:var
b=H(a[1]),s=b[2];return[0,,function(a){h(s,w)},,b[4]];case
1:var
c=H(a[1]),t=c[2];return[0,,function(a){h(t,w)},,c[4]];case
2:var
d=H(a[1]),u=d[2];return[0,,function(a){h(u,w)},,d[4]];case
3:var
e=H(a[1]),v=e[2];return[0,,function(a){h(v,w)},,e[4]];case
4:var
f=H(a[1]),x=f[2];return[0,,function(a){h(x,w)},,f[4]];case
5:var
g=H(a[1]),z=g[2];return[0,,function(a){h(z,w)},,g[4]];case
6:var
i=H(a[1]),B=i[2];return[0,,function(a){h(B,w)},,i[4]];case
7:var
j=H(a[1]),C=j[2];return[0,,function(a){h(C,w)},,j[4]];case
8:var
k=H(a[2]),D=k[2];return[0,,function(a){h(D,w)},,k[4]];case
9:var
E=a[2],F=a[1],l=H(a[3]),G=l[4],I=l[2],m=H(A(y(F),E)),J=m[4],K=m[2];return[0,,function(a){h(K,w);h(I,w)},,function(a){h(J,w);h(G,w)}];case
10:var
n=H(a[1]),L=n[2];return[0,,function(a){h(L,w)},,n[4]];case
11:var
o=H(a[1]),M=o[2];return[0,,function(a){h(M,w)},,o[4]];case
12:var
p=H(a[1]),N=p[2];return[0,,function(a){h(N,w)},,p[4]];case
13:var
q=H(a[1]),O=q[4],P=q[2];return[0,,function(a){h(P,w)},,function(a){h(O,w)}];default:var
r=H(a[1]),Q=r[4],R=r[2];return[0,,function(a){h(R,w)},,function(a){h(Q,w)}]}}var
b="camlinternalFormat.ml",gn=[0,c(b),857,23],gy=[0,c(b),821,21],gq=[0,c(b),822,21],gz=[0,c(b),825,21],gr=[0,c(b),826,21],gA=[0,c(b),829,19],gs=[0,c(b),830,19],gB=[0,c(b),833,22],gt=[0,c(b),834,22],gC=[0,c(b),838,30],gu=[0,c(b),839,30],gw=[0,c(b),843,26],go=[0,c(b),844,26],gx=[0,c(b),853,28],gp=[0,c(b),854,28],gv=[0,c(b),858,23];function
A(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:var
d=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,A(d,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
1:var
e=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,A(e,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
2:var
f=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,A(f,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
3:var
i=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,A(i,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
4:var
j=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,A(j,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
5:var
k=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,A(k,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
6:var
l=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,A(l,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
7:var
m=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,A(m,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
8:var
n=a[2],o=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
q=b[1],r=A(n,b[2]);return[8,A(o,q),r];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw g([0,p,gw],1);case
9:var
s=a[3],t=a[2],u=a[1];if(typeof
b!=="number")switch(b[0]){case
9:var
v=b[3],x=b[2],z=b[1],c=H(A(y(t),z)),B=c[4];h(c[2],w);h(B,w);return[9,u,x,A(s,v)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f}throw g([0,p,gx],1);case
10:var
C=a[1];if(typeof
b!=="number"&&10===b[0])return[10,A(C,b[1])];throw g([0,p,gy],1);case
11:var
D=a[1];if(typeof
b!=="number")switch(b[0]){case
11:return[11,A(D,b[1])];case
10:break a}throw g([0,p,gz],1);case
12:var
E=a[1];if(typeof
b!=="number")switch(b[0]){case
12:return[12,A(E,b[1])];case
10:break a;case
11:break b}throw g([0,p,gA],1);case
13:var
F=a[1];if(typeof
b!=="number")switch(b[0]){case
13:return[13,A(F,b[1])];case
10:break a;case
11:break b;case
12:break c}throw g([0,p,gB],1);default:var
G=a[1];if(typeof
b!=="number")switch(b[0]){case
14:return[14,A(G,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d}throw g([0,p,gC],1)}throw g([0,p,gv],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw g([0,p,gn],1)}}throw g([0,p,gp],1)}throw g([0,p,go],1)}throw g([0,p,gu],1)}throw g([0,p,gt],1)}throw g([0,p,gs],1)}throw g([0,p,gr],1)}throw g([0,p,gq],1)}var
D=[u,c("CamlinternalFormat.Type_mismatch"),aH(0)];function
bh(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw g(D,0)}function
aZ(a,b,c){var
d=bh(a,c);if(typeof
b!=="number")return[0,d[1],[0,b[1]],d[2]];if(!b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw g(D,0)}function
e(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){var
v=e(a[1],b[1]);return[0,[0,v[1]],v[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){var
w=e(a[1],b[1]);return[0,[1,w[1]],w[2]]}break;case
2:var
af=a[2],x=bh(a[1],b),f=x[2],ag=x[1];if(typeof
f!=="number"&&1===f[0]){var
y=e(af,f[1]);return[0,[2,ag,y[1]],y[2]]}throw g(D,0);case
3:var
ah=a[2],z=bh(a[1],b),h=z[2],ai=z[1];if(typeof
h!=="number"&&1===h[0]){var
A=e(ah,h[1]);return[0,[3,ai,A[1]],A[2]]}throw g(D,0);case
4:var
aj=a[4],ak=a[1],i=aZ(a[2],a[3],b),j=i[3],al=i[1];if(typeof
j!=="number"&&2===j[0]){var
am=i[2],B=e(aj,j[1]);return[0,[4,ak,al,am,B[1]],B[2]]}throw g(D,0);case
5:var
an=a[4],ao=a[1],k=aZ(a[2],a[3],b),l=k[3],ap=k[1];if(typeof
l!=="number"&&3===l[0]){var
aq=k[2],C=e(an,l[1]);return[0,[5,ao,ap,aq,C[1]],C[2]]}throw g(D,0);case
6:var
ar=a[4],as=a[1],m=aZ(a[2],a[3],b),n=m[3],at=m[1];if(typeof
n!=="number"&&4===n[0]){var
au=m[2],E=e(ar,n[1]);return[0,[6,as,at,au,E[1]],E[2]]}throw g(D,0);case
7:var
av=a[4],aw=a[1],o=aZ(a[2],a[3],b),p=o[3],ax=o[1];if(typeof
p!=="number"&&5===p[0]){var
ay=o[2],F=e(av,p[1]);return[0,[7,aw,ax,ay,F[1]],F[2]]}throw g(D,0);case
8:var
az=a[4],aA=a[1],q=aZ(a[2],a[3],b),r=q[3],aB=q[1];if(typeof
r!=="number"&&6===r[0]){var
aC=q[2],G=e(az,r[1]);return[0,[8,aA,aB,aC,G[1]],G[2]]}throw g(D,0);case
9:var
aD=a[2],H=bh(a[1],b),s=H[2],aE=H[1];if(typeof
s!=="number"&&7===s[0]){var
I=e(aD,s[1]);return[0,[9,aE,I[1]],I[2]]}throw g(D,0);case
10:var
J=e(a[1],b);return[0,[10,J[1]],J[2]];case
11:var
aF=a[1],K=e(a[2],b);return[0,[11,aF,K[1]],K[2]];case
12:var
aG=a[1],L=e(a[2],b);return[0,[12,aG,L[1]],L[2]];case
13:if(typeof
b!=="number"&&8===b[0]){var
M=b[1],aH=b[2],aI=a[3],aJ=a[1];if(bc([0,a[2]],[0,M]))throw g(D,0);var
N=e(aI,aH);return[0,[13,aJ,M,N[1]],N[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){var
O=b[1],aK=b[3],aL=a[3],aM=a[2],aN=a[1],aO=[0,t(O)];if(bc([0,t(aM)],aO))throw g(D,0);var
P=e(aL,t(aK));return[0,[14,aN,O,P[1]],P[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){var
Q=e(a[1],b[1]);return[0,[15,Q[1]],Q[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){var
S=e(a[1],b[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aP=a[1],T=e(a[2],b);return[0,[17,aP,T[1]],T[2]];case
18:var
U=a[2],u=a[1];if(0===u[0]){var
Y=u[1],aT=Y[2],Z=e(Y[1],b),aU=Z[1],_=e(U,Z[2]);return[0,[18,[0,[0,aU,aT]],_[1]],_[2]]}var
$=u[1],aV=$[2],aa=e($[1],b),aW=aa[1],ab=e(U,aa[2]);return[0,[18,[1,[0,aW,aV]],ab[1]],ab[2]];case
19:if(typeof
b!=="number"&&13===b[0]){var
V=e(a[1],b[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){var
aQ=a[2],aR=a[1],W=e(a[3],b[1]);return[0,[20,aR,aQ,W[1]],W[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){var
aS=a[1],X=e(a[2],b[1]);return[0,[21,aS,X[1]],X[2]]}break;case
23:var
d=a[2],c=a[1];if(typeof
c!=="number")switch(c[0]){case
8:return bY([8,c[1],c[2]],d,b);case
9:var
aX=c[1],ad=R(c[2],d,b),ae=ad[2];return[0,[23,[9,aX,ad[1]],ae[1]],ae[2]];default:return bY(c,d,b)}if(2!==c)return bY(c,d,b);if(typeof
b!=="number"&&14===b[0]){var
ac=e(d,b[1]);return[0,[23,2,ac[1]],ac[2]]}throw g(D,0)}throw g(D,0)}function
bY(a,b,c){var
d=e(b,c);return[0,[23,a,d[1]],d[2]]}function
R(a,b,c){if(typeof
a==="number")return[0,0,e(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
i=R(a[1],b,c[1]);return[0,[0,i[1]],i[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
j=R(a[1],b,c[1]);return[0,[1,j[1]],j[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
k=R(a[1],b,c[1]);return[0,[2,k[1]],k[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
l=R(a[1],b,c[1]);return[0,[3,l[1]],l[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
m=R(a[1],b,c[1]);return[0,[4,m[1]],m[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
n=R(a[1],b,c[1]);return[0,[5,n[1]],n[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
o=R(a[1],b,c[1]);return[0,[6,o[1]],o[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
p=R(a[1],b,c[1]);return[0,[7,p[1]],p[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
q=c[1],C=c[2],E=a[2];if(bc([0,a[1]],[0,q]))throw g(D,0);var
r=R(E,b,C);return[0,[8,q,r[1]],r[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],f=c[1],F=c[3],G=a[3],I=a[2],J=a[1],K=[0,t(f)];if(bc([0,t(J)],K))throw g(D,0);var
L=[0,t(d)];if(bc([0,t(I)],L))throw g(D,0);var
s=H(A(y(f),d)),M=s[4];h(s[2],w);h(M,w);var
u=R(t(G),b,F),N=u[2];return[0,[9,f,d,y(u[1])],N]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
v=R(a[1],b,c[1]);return[0,[10,v[1]],v[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
x=R(a[1],b,c[1]);return[0,[11,x[1]],x[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
z=R(a[1],b,c[1]);return[0,[13,z[1]],z[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
B=R(a[1],b,c[1]);return[0,[14,B[1]],B[2]]}break}throw g(D,0)}var
eC=120;function
l(a,b,c){var
d=O(c),g=0<=b?a:0,f=aY(b);if(f<=d)return c;var
h=2===g?48:32,e=ap(f,h);switch(g){case
0:ag(c,0,e,0,d);break;case
1:ag(c,0,e,f-d|0,d);break;default:a:if(0<d){if(T(c,0)!==43&&T(c,0)!==45&&T(c,0)!==32)break a;ax(e,0,T(c,0));ag(c,1,e,(f-d|0)+1|0,d-1|0);break}a:if(1<d&&T(c,0)===48){if(T(c,1)!==eC&&T(c,1)!==88)break a;ax(e,1,T(c,1));ag(c,2,e,(f-d|0)+2|0,d-2|0);break}ag(c,0,e,f-d|0,d)}return Q(e)}var
ew=-97;function
$(a,b){var
d=aY(a),c=O(b),e=T(b,0);a:{b:{if(58>e){if(32!==e){if(43>e)break a;switch(e-43|0){case
5:if(c>=(d+2|0))break b;if(1>=c)break b;if(T(b,1)!==eC&&T(b,1)!==88)break b;var
g=ap(d+2|0,48);ax(g,1,T(b,1));ag(b,2,g,(d-c|0)+4|0,c-2|0);return Q(g);case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(c>=(d+1|0))break a;var
f=ap(d+1|0,48);ax(f,0,e);ag(b,1,f,(d-c|0)+2|0,c-1|0);return Q(f)}if(71<=e){if(5<e+ew>>>0)break a}else if(65>e)break a}if(c<d){var
h=ap(d,48);ag(b,0,h,d-c|0,c);return Q(h)}}return b}var
ca=100;function
cV(a){var
e=aF(a),m=ab(e)-1|0,b=[0,0];if(m>=0){var
h=0;for(;;){var
f=bx(e,h);a:{b:{c:{if(32<=f){var
i=f-34|0;if(58<i>>>0){if(93<=i)break c}else if(56<i-1>>>0)break b;var
j=1;break a}if(11<=f){if(13===f)break b}else if(8<=f)break b}var
j=4;break a}var
j=2}b[1]=b[1]+j|0;var
s=h+1|0;if(m===h)break;h=s}}if(b[1]===ab(e))var
l=e;else{var
c=E(b[1]);b[1]=0;var
n=ab(e)-1|0;if(n<0)var
l=c;else{var
g=0;for(;;){var
d=bx(e,g);a:{b:{c:{if(35<=d){if(92!==d){if(a5<=d)break b;break c}}else{if(32>d){if(14<=d)break b;switch(d){case
8:k(c,b[1],92);b[1]++;k(c,b[1],98);break a;case
9:k(c,b[1],92);b[1]++;k(c,b[1],116);break a;case
10:k(c,b[1],92);b[1]++;k(c,b[1],110);break a;case
13:k(c,b[1],92);b[1]++;k(c,b[1],114);break a;default:break b}}if(34>d)break c}k(c,b[1],92);b[1]++;k(c,b[1],d);break a}k(c,b[1],d);break a}k(c,b[1],92);b[1]++;k(c,b[1],48+(d/ca|0)|0);b[1]++;k(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;k(c,b[1],48+(d%10|0)|0)}b[1]++;var
r=g+1|0;if(n===g){var
l=c;break}g=r}}}var
q=Q(l),o=O(q),p=ap(o+2|0,34);a7(q,0,p,1,o);return Q(p)}var
eV=103,hr=[0,eV];function
cW(a,b){var
h=aY(b),g=hr[1];switch(a[2]){case
0:var
d=102;break;case
1:var
d=101;break;case
2:var
d=69;break;case
3:var
d=eV;break;case
4:var
d=71;break;case
6:var
d=104;break;case
7:var
d=72;break;case
8:var
d=70;break;default:var
d=g}var
e=bW(16);aK(e,37);switch(a[1]){case
1:aK(e,43);break;case
2:aK(e,32);break}if(8<=a[2])aK(e,35);aK(e,46);G(e,c(f+h));aK(e,d);return bX(e)}function
bi(a,b){if(13>a)return b;var
i=O(b)-1|0,n=-48,h=[0,0];if(i>=0){var
d=0;for(;;){if(9>=bL(b,d)+n>>>0)h[1]++;var
p=d+1|0;if(i===d)break;d=p}}var
j=h[1],k=E(O(b)+((j-1|0)/3|0)|0),l=[0,0];function
e(a){ax(k,l[1],a);l[1]++}var
f=[0,((j-1|0)%3|0)+1|0],m=O(b)-1|0;if(m>=0){var
c=0;for(;;){var
g=bL(b,c);if(9<g+n>>>0)e(g);else{if(0===f[1]){e(95);f[1]=3}f[1]--;e(g)}var
o=c+1|0;if(m===c)break;c=o}}return Q(k)}var
eS="%u",gD=c(b9),gG=c(en),gP=c(eS),gE=c("%+d"),gF=c("% d"),gH=c("%+i"),gI=c("% i"),gJ=c("%x"),gK=c("%#x"),gL=c("%X"),gM=c("%#X"),gN=c("%o"),gO=c("%#o");function
cX(a,b){switch(a){case
1:var
c=gE;break;case
2:var
c=gF;break;case
4:var
c=gH;break;case
5:var
c=gI;break;case
6:var
c=gJ;break;case
7:var
c=gK;break;case
8:var
c=gL;break;case
9:var
c=gM;break;case
10:var
c=gN;break;case
11:var
c=gO;break;case
0:case
13:var
c=gD;break;case
3:case
14:var
c=gG;break;default:var
c=gP}return bi(a,a9(c,b))}var
g3=c("%ld"),g6=c(eE),hd=c("%lu"),g4=c("%+ld"),g5=c("% ld"),g7=c("%+li"),g8=c("% li"),g9=c("%lx"),g_=c("%#lx"),g$=c("%lX"),ha=c("%#lX"),hb=c("%lo"),hc=c("%#lo");function
cY(a,b){switch(a){case
1:var
c=g4;break;case
2:var
c=g5;break;case
4:var
c=g7;break;case
5:var
c=g8;break;case
6:var
c=g9;break;case
7:var
c=g_;break;case
8:var
c=g$;break;case
9:var
c=ha;break;case
10:var
c=hb;break;case
11:var
c=hc;break;case
0:case
13:var
c=g3;break;case
3:case
14:var
c=g6;break;default:var
c=hd}return bi(a,a9(c,b))}var
he=c("%nd"),hh=c(e_),hq=c("%nu"),hf=c("%+nd"),hg=c("% nd"),hi=c("%+ni"),hj=c("% ni"),hk=c("%nx"),hl=c("%#nx"),hm=c("%nX"),hn=c("%#nX"),ho=c("%no"),hp=c("%#no");function
cZ(a,b){switch(a){case
1:var
c=hf;break;case
2:var
c=hg;break;case
4:var
c=hi;break;case
5:var
c=hj;break;case
6:var
c=hk;break;case
7:var
c=hl;break;case
8:var
c=hm;break;case
9:var
c=hn;break;case
10:var
c=ho;break;case
11:var
c=hp;break;case
0:case
13:var
c=he;break;case
3:case
14:var
c=hh;break;default:var
c=hq}return bi(a,a9(c,b))}var
gQ=c("%Ld"),gT=c(eR),g2=c("%Lu"),gR=c("%+Ld"),gS=c("% Ld"),gU=c("%+Li"),gV=c("% Li"),gW=c("%Lx"),gX=c("%#Lx"),gY=c("%LX"),gZ=c("%#LX"),g0=c("%Lo"),g1=c("%#Lo");function
c0(a,b){switch(a){case
1:var
c=gR;break;case
2:var
c=gS;break;case
4:var
c=gU;break;case
5:var
c=gV;break;case
6:var
c=gW;break;case
7:var
c=gX;break;case
8:var
c=gY;break;case
9:var
c=gZ;break;case
10:var
c=g0;break;case
11:var
c=g1;break;case
0:case
13:var
c=gQ;break;case
3:case
14:var
c=gT;break;default:var
c=g2}return bi(a,il(c,b))}var
hv=c(cg),ht=c("neg_infinity"),hu=c(er),hs=c(aE);function
I(l,b,c){function
m(a){switch(l[1]){case
0:var
d=45;break;case
1:var
d=43;break;default:var
d=32}return ig(c,b,d)}function
q(a){var
b=h6(c);return 3===b?c<0.?ht:hu:4<=b?hv:a}switch(l[2]){case
5:var
e=bB(cW(l,b),c),d=0,t=O(e);for(;;){a:{if(d!==t){var
n=T(e,d)-46|0;b:{if(23<n>>>0){if(55!==n)break b}else if(21>=n-1>>>0)break b;var
p=1;break a}d=d+1|0;continue}var
p=0}var
u=p?e:aA(e,hs);return q(u)}case
6:return m();case
7:var
i=aF(m()),f=ab(i);if(0===f)var
j=i;else{var
g=E(f),o=f-1|0;if(o<0)var
j=g;else{var
a=0;for(;;){var
h=bx(i,a),r=25<h+ew>>>0?h:h-32|0;k(g,a,r);var
s=a+1|0;if(o===a){var
j=g;break}a=s}}}return Q(j);case
8:return q(m());default:return bB(cW(l,b),c)}}function
d1(d,e,c){return a(function(a){return i(e,[5,d,a],c)},function(a,b){return j(i,e,[5,d,a],c,b)})}var
c3=c(eS);function
d2(d,e,c){return a(function(a){return i(e,[4,d,a9(c3,a)],c)},function(a,b){return j(i,e,[4,d,a9(c3,a)],c,b)})}function
d3(d,e,c){return a(function(a){return i(d,c,e)},function(a,b){return j(i,d,c,e,b)})}function
d4(d,e,c){return a(function(a){return i(e,[1,d,[0,a]],c)},function(a,b){return j(i,e,[1,d,[0,a]],c,b)})}function
d5(d,e,c){return a(function(a){return i(e,[1,d,[1,a]],c)},function(a,b){return j(i,e,[1,d,[1,a]],c,b)})}function
d6(d,e,c){return a(function(a){return i(e,[6,d,a],c)},function(a,b){return j(i,e,[6,d,a],c,b)})}function
d7(c,d){return a(function(a){return z(d,a,c)},function(a,b){return bo(d,a,c,b)})}function
d8(d,e,f){return a(function(a,b){return i(e,[6,d,d7(b,a)],f)},function(a,b,c){return j(i,e,[6,d,d7(b,a)],f,c)})}function
d9(h,k,c,d){return a(function(a){var
f=a[1],b=e(f,t(y(d)));if(typeof
b[2]==="number")return i(k,h,o(b[1],c));throw g(D,0)},function(a,b){var
m=a[1],f=e(m,t(y(d)));if(typeof
f[2]==="number")return j(i,k,h,o(f[1],c),b);var
l=aj();return l(g(D,0))})}function
d_(e,f,c,d){return a(function(a){return i(c,[4,f,e],d)},function(a,b){return j(i,c,[4,f,e],d,b)})}function
d$(e,f,g,d){return a(function(a,b){return i(f,[4,e,I(d,a,b)],g)},function(a,b,c){return j(i,f,[4,e,I(d,a,b)],g,c)})}function
ea(e,f,c,d){return a(function(a){return i(f,[4,e,I(d,aJ(d),a)],c)},function(a,b){return j(i,f,[4,e,I(d,aJ(d),a)],c,b)})}function
eb(f,g,c,d,e){return a(function(a){return i(g,[4,f,I(d,e,a)],c)},function(a,b){return j(i,g,[4,f,I(d,e,a)],c,b)})}function
ec(g,h,k,d,e,f){return a(function(a,b){return i(h,[4,g,l(f,e,I(d,a,b))],k)},function(a,b,c){return j(i,h,[4,g,l(f,e,I(d,a,b))],k,c)})}function
ed(g,h,c,d,e,f){return a(function(a){return i(h,[4,g,l(f,e,I(d,aJ(d),a))],c)},function(a,b){return j(i,h,[4,g,l(f,e,I(d,aJ(d),a))],c,b)})}function
ee(h,k,c,d,e,f,g){return a(function(a){return i(k,[4,h,l(f,e,I(d,g,a))],c)},function(a,b){return j(i,k,[4,h,l(f,e,I(d,g,a))],c,b)})}function
ef(f,g,h,k,e){return a(function(a,b,c){return i(g,[4,f,l(e,a,I(k,b,c))],h)},function(a,b,c,d){return j(i,g,[4,f,l(e,a,I(k,b,c))],h,d)})}function
eg(f,g,h,d,e){return a(function(a,b){return i(g,[4,f,l(e,a,I(d,aJ(d),b))],h)},function(a,b,c){return j(i,g,[4,f,l(e,a,I(d,aJ(d),b))],h,c)})}function
eh(g,h,k,d,e,f){return a(function(a,b){return i(h,[4,g,l(e,a,I(d,f,b))],k)},function(a,b,c){return j(i,h,[4,g,l(e,a,I(d,f,b))],k,c)})}function
ei(){return function(a){return a}}var
cN=c("\\\\"),cO=c("\\'"),cP=c("\\b"),cQ=c("\\t"),cR=c("\\n"),cS=c("\\r");function
ej(l,m,c){return a(function(a){a:{b:{if(40<=a){if(92===a){var
b=cN;break a}if(a5<=a)break b}else{if(32>a){if(14<=a)break b;switch(a){case
8:var
b=cP;break a;case
9:var
b=cQ;break a;case
10:var
b=cR;break a;case
13:var
b=cS;break a;default:break b}}if(39<=a){var
b=cO;break a}}var
e=E(1);k(e,0,a);var
b=Q(e);break a}var
d=E(4);k(d,0,92);k(d,1,48+(a/ca|0)|0);k(d,2,48+((a/10|0)%10|0)|0);k(d,3,48+(a%10|0)|0);var
b=Q(d)}var
f=O(b),g=ap(f+2|0,39);a7(b,0,g,1,f);return i(m,[4,l,Q(g)],c)},function(a,b){a:{b:{if(40<=a){if(92===a){var
d=cN;break a}if(a5<=a)break b}else{if(32>a){if(14<=a)break b;switch(a){case
8:var
d=cP;break a;case
9:var
d=cQ;break a;case
10:var
d=cR;break a;case
13:var
d=cS;break a;default:break b}}if(39<=a){var
d=cO;break a}}var
h=E(1);k(h,0,a);var
d=Q(h);break a}var
e=E(4);k(e,0,92);k(e,1,48+(a/ca|0)|0);k(e,2,48+((a/10|0)%10|0)|0);k(e,3,48+(a%10|0)|0);var
d=Q(e)}var
f=O(d),g=ap(f+2|0,39);a7(d,0,g,1,f);return j(i,m,[4,l,Q(g)],c,b)})}function
ek(d,e,c){return a(function(a){return i(e,[5,d,a],c)},function(a,b){return j(i,e,[5,d,a],c,b)})}var
c1=[0,c(b),1565,4],c2=c("Printf: bad conversion %["),c4=[0,c(b),1633,39],i=a(function(a,b,c){var
f=a,e=b,d=c;a:for(;;){if(typeof
d==="number")return h(f,e);switch(d[0]){case
0:return ek(e,f,d[1]);case
1:return ej(e,f,d[1]);case
2:var
v=d[2],w=d[1];return aM(f,e,v,w,ei());case
3:return aM(f,e,d[2],d[1],cV);case
4:return aq(f,e,d[4],d[2],d[3],cX,d[1]);case
5:return aq(f,e,d[4],d[2],d[3],cY,d[1]);case
6:return aq(f,e,d[4],d[2],d[3],cZ,d[1]);case
7:return aq(f,e,d[4],d[2],d[3],c0,d[1]);case
8:break a;case
9:return aM(f,e,d[2],d[1],cJ);case
10:e=[7,e];d=d[1];break;case
11:e=[2,e,d[1]];d=d[2];break;case
12:e=[3,e,d[1]];d=d[2];break;case
13:var
x=d[3],y=d[2],u=bW(16);bg(u,y);return d_(bX(u),e,f,x);case
14:return d9(e,f,d[3],d[2]);case
15:return d8(e,f,d[1]);case
16:return d6(e,f,d[1]);case
17:e=[0,e,d[1]];d=d[2];break;case
18:var
o=d[1];if(0===o[0]){var
z=o[1][1];f=d4(e,f,d[2]);e=0;d=z}else{var
A=o[1][1];f=d5(e,f,d[2]);e=0;d=A}break;case
19:throw g([0,p,c1],1);case
20:return d3(f,d[3],[8,e,c2]);case
21:return d2(e,f,d[2]);case
22:return d1(e,f,d[1]);case
23:var
q=d[2],n=d[1];if(typeof
n!=="number")return 9===n[0]?m(f,e,n[2],q):aL(f,e,q);if(2===n)throw g([0,p,c4],1);return aL(f,e,q);default:var
B=d[3],C=d[1];return bj(f,e,B,C,h(d[2],0))}}var
i=d[4],j=d[3],l=d[2],k=d[1];if(typeof
l==="number")return typeof
j==="number"?j?d$(e,f,i,k):ea(e,f,i,k):eb(e,f,i,k,j[1]);if(0===l[0]){var
r=l[2],s=l[1];return typeof
j==="number"?j?ec(e,f,i,k,r,s):ed(e,f,i,k,r,s):ee(e,f,i,k,r,s,j[1])}var
t=l[1];return typeof
j==="number"?j?ef(e,f,i,k,t):eg(e,f,i,k,t):eh(e,f,i,k,t,j[1])},function(a,b,c,d){a:{var
e=c,f=b,h=a;b:for(;;){if(typeof
e==="number")return B(h,f,d);switch(e[0]){case
24:break a;case
23:var
q=e[2],o=e[1];if(typeof
o!=="number")return 9===o[0]?U(m,h,f,o[2],q,d):j(aL,h,f,q,d);if(2!==o)return j(aL,h,f,q,d);var
w=aj();return w(g([0,p,c4],1));case
22:return d(d1(f,h,e[1]));case
21:return d(d2(f,h,e[2]));case
20:return d(d3(h,e[3],[8,f,c2]));case
19:var
x=aj();return x(g([0,p,c1],1));case
18:var
r=e[1];if(0===r[0]){var
A=r[1][1],C=d4(f,h,e[2]);e=A;f=0;h=C}else{var
D=r[1][1],E=d5(f,h,e[2]);e=D;f=0;h=E}break;case
17:var
F=[0,f,e[1]];e=e[2];f=F;break;case
16:return d(d6(f,h,e[1]));case
15:return d(d8(f,h,e[1]));case
14:return d(d9(f,h,e[3],e[2]));case
13:var
G=e[3],H=e[2],v=bW(16);bg(v,H);return d(d_(bX(v),f,h,G));case
12:var
I=[3,f,e[1]];e=e[2];f=I;break;case
11:var
J=[2,f,e[1]];e=e[2];f=J;break;case
10:e=e[1];f=[7,f];break;case
9:return d(aM(h,f,e[2],e[1],cJ));case
8:break b;case
7:return d(aq(h,f,e[4],e[2],e[3],c0,e[1]));case
6:return d(aq(h,f,e[4],e[2],e[3],cZ,e[1]));case
5:return d(aq(h,f,e[4],e[2],e[3],cY,e[1]));case
4:return d(aq(h,f,e[4],e[2],e[3],cX,e[1]));case
3:return d(aM(h,f,e[2],e[1],cV));case
2:var
K=e[2],L=e[1];return d(aM(h,f,K,L,ei()));case
1:return d(ej(f,h,e[1]));default:return d(ek(f,h,e[1]))}}var
i=e[4],k=e[3],n=e[2],l=e[1];if(typeof
n==="number")return typeof
k==="number"?k?d(d$(f,h,i,l)):d(ea(f,h,i,l)):d(eb(f,h,i,l,k[1]));if(0===n[0]){var
s=n[2],t=n[1];return typeof
k==="number"?k?d(ec(f,h,i,l,s,t)):d(ed(f,h,i,l,s,t)):d(ee(f,h,i,l,s,t,k[1]))}var
u=n[1];return typeof
k==="number"?k?d(ef(f,h,i,l,u)):d(eg(f,h,i,l,u)):d(eh(f,h,i,l,u,k[1]))}var
y=e[3],z=e[1];return S(e[2],0,function(a){return em(bj,h,f,y,z,a,d)})});function
dO(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dP(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dQ(e,f,g,d){return a(function(a,b){return m(g,f,d,e)},function(a,b,c){return U(m,g,f,d,e,c)})}function
dR(f,g,c,d,e){return a(function(a){return m(c,g,M(e,d),f)},function(a,b){return U(m,c,g,M(e,d),f,b)})}function
dS(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dT(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dU(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dV(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dW(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dX(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dY(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
dZ(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}function
d0(e,f,c,d){return a(function(a){return m(c,f,d,e)},function(a,b){return U(m,c,f,d,e,b)})}var
c5=[0,c(b),1656,31],c6=[0,c(b),1657,31],m=a(function(a,b,c,d){if(typeof
c==="number")return aL(a,b,d);switch(c[0]){case
0:return d0(d,b,a,c[1]);case
1:return dZ(d,b,a,c[1]);case
2:return dY(d,b,a,c[1]);case
3:return dX(d,b,a,c[1]);case
4:return dW(d,b,a,c[1]);case
5:return dV(d,b,a,c[1]);case
6:return dU(d,b,a,c[1]);case
7:return dT(d,b,a,c[1]);case
8:return dS(d,b,a,c[2]);case
9:var
e=c[3],f=c[2];return dR(d,b,a,e,A(y(c[1]),f));case
10:return dQ(d,b,a,c[1]);case
11:return dP(d,b,a,c[1]);case
12:return dO(d,b,a,c[1]);case
13:throw g([0,p,c5],1);default:throw g([0,p,c6],1)}},function(a,b,c,d,e){if(typeof
c==="number")return j(aL,a,b,d,e);switch(c[0]){case
14:var
f=aj();return f(g([0,p,c6],1));case
13:var
h=aj();return h(g([0,p,c5],1));case
12:return e(dO(d,b,a,c[1]));case
11:return e(dP(d,b,a,c[1]));case
10:return e(dQ(d,b,a,c[1]));case
9:var
i=c[3],k=c[2];return e(dR(d,b,a,i,A(y(c[1]),k)));case
8:return e(dS(d,b,a,c[2]));case
7:return e(dT(d,b,a,c[1]));case
6:return e(dU(d,b,a,c[1]));case
5:return e(dV(d,b,a,c[1]));case
4:return e(dW(d,b,a,c[1]));case
3:return e(dX(d,b,a,c[1]));case
2:return e(dY(d,b,a,c[1]));case
1:return e(dZ(d,b,a,c[1]));default:return e(d0(d,b,a,c[1]))}}),c7=c("Printf: bad conversion %_"),aL=a(function(a,b,c){return i(a,[8,b,c7],c)},function(a,b,c,d){return j(i,a,[8,b,c7],c,d)});function
hO(e,f,c,d){return a(function(a){return i(d,[4,c,h(e,a)],f)},function(a,b){return j(i,d,[4,c,h(e,a)],f,b)})}function
hP(g,k,c,d,e,f){return a(function(a){return i(d,[4,c,l(f,e,h(g,a))],k)},function(a,b){return j(i,d,[4,c,l(f,e,h(g,a))],k,b)})}function
hQ(f,g,k,d,e){return a(function(a,b){return i(d,[4,k,l(e,a,h(f,b))],g)},function(a,b,c){return j(i,d,[4,k,l(e,a,h(f,b))],g,c)})}function
aM(a,b,c,d,e){return typeof
d==="number"?hO(e,c,b,a):0===d[0]?hP(e,c,b,a,d[2],d[1]):hQ(e,c,b,a,d[1])}function
hF(f,g,h,d,e){return a(function(a,b){return i(e,[4,d,$(a,z(g,f,b))],h)},function(a,b,c){return j(i,e,[4,d,$(a,z(g,f,b))],h,c)})}function
hG(f,g,c,d,e){return a(function(a){return i(e,[4,d,z(g,f,a)],c)},function(a,b){return j(i,e,[4,d,z(g,f,a)],c,b)})}function
hH(g,h,c,d,e,f){return a(function(a){return i(e,[4,d,$(f,z(h,g,a))],c)},function(a,b){return j(i,e,[4,d,$(f,z(h,g,a))],c,b)})}function
hI(h,k,m,d,e,f,g){return a(function(a,b){return i(e,[4,d,l(g,f,$(a,z(k,h,b)))],m)},function(a,b,c){return j(i,e,[4,d,l(g,f,$(a,z(k,h,b)))],m,c)})}function
hJ(h,k,c,d,e,f,g){return a(function(a){return i(e,[4,d,l(g,f,z(k,h,a))],c)},function(a,b){return j(i,e,[4,d,l(g,f,z(k,h,a))],c,b)})}function
hK(k,m,c,d,e,f,g,h){return a(function(a){return i(e,[4,d,l(g,f,$(h,z(m,k,a)))],c)},function(a,b){return j(i,e,[4,d,l(g,f,$(h,z(m,k,a)))],c,b)})}function
hL(g,h,k,m,e,f){return a(function(a,b,c){return i(e,[4,m,l(f,a,$(b,z(h,g,c)))],k)},function(a,b,c,d){return j(i,e,[4,m,l(f,a,$(b,z(h,g,c)))],k,d)})}function
hM(g,h,k,d,e,f){return a(function(a,b){return i(e,[4,d,l(f,a,z(h,g,b))],k)},function(a,b,c){return j(i,e,[4,d,l(f,a,z(h,g,b))],k,c)})}function
hN(h,k,m,d,e,f,g){return a(function(a,b){return i(e,[4,d,l(f,a,$(g,z(k,h,b)))],m)},function(a,b,c){return j(i,e,[4,d,l(f,a,$(g,z(k,h,b)))],m,c)})}function
aq(a,b,c,d,e,f,g){if(typeof
d==="number")return typeof
e==="number"?e?hF(g,f,c,b,a):hG(g,f,c,b,a):hH(g,f,c,b,a,e[1]);if(0===d[0]){var
h=d[2],i=d[1];return typeof
e==="number"?e?hI(g,f,c,b,a,h,i):hJ(g,f,c,b,a,h,i):hK(g,f,c,b,a,h,i,e[1])}var
j=d[1];return typeof
e==="number"?e?hL(g,f,c,b,a,j):hM(g,f,c,b,a,j):hN(g,f,c,b,a,j,e[1])}function
dN(f,g,c,d,e){return a(function(a){return bj(d,c,g,e,h(f,a))},function(a,b){return S(f,a,function(a){return em(bj,d,c,g,e,a,b)})})}var
bj=a(function(a,b,c,d,e){return d?dN(e,c,b,a,d[1]):i(a,[4,b,e],c)},function(a,b,c,d,e,f){return d?f(dN(e,c,b,a,d[1])):j(i,a,[4,b,e],c,f)}),ez="@[",e1="@{",c8=c(e1),c9=c(ez),J=a(function(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
f=c[1],g=bf(c[2]);J(a,f);return al(a,g);case
1:var
d=c[2],e=c[1];if(0===d[0]){var
i=d[1];J(a,e);al(a,c8);c=i}else{var
j=d[1];J(a,e);al(a,c9);c=j}break;case
6:var
m=c[2];J(a,c[1]);return h(m,a);case
7:J(a,c[1]);ac(a);return;case
8:var
n=c[2];J(a,c[1]);return aB(n);case
2:case
4:var
k=c[2];J(a,c[1]);return al(a,k);default:var
l=c[2];J(a,c[1]);cw(a,l);return}}},function(e,b,c){function
f(a){if(typeof
a==="number")return c();switch(a[0]){case
8:var
h=a[2];return d(J,e,a[1],function(a){return c(aB(h))});case
7:return d(J,e,a[1],function(a){ac(e);return c()});case
6:var
i=a[2];return d(J,e,a[1],function(a){return S(i,e,c)});case
1:var
b=a[2],g=a[1];if(0===b[0]){var
l=b[1];return d(J,e,g,function(a){al(e,c8);return au(f,l)})}var
m=b[1];return d(J,e,g,function(a){al(e,c9);return au(f,m)});case
0:var
n=a[1],o=bf(a[2]);return d(J,e,n,function(a){return c(al(e,o))});case
3:case
5:var
j=a[2];return d(J,e,a[1],function(a){cw(e,j);return c()});default:var
k=a[2];return d(J,e,a[1],function(a){return c(al(e,k))})}}return f(b)}),c_=c(e1),c$=c(ez),P=a(function(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
l=c[1],m=bf(c[2]);P(a,l);return ah(a,m);case
1:var
e=c[2],g=c[1];if(0===e[0]){var
n=e[1];P(a,g);ah(a,c_);c=n}else{var
o=e[1];P(a,g);ah(a,c$);c=o}break;case
6:var
q=c[2];P(a,c[1]);return ah(a,h(q,0));case
7:c=c[1];break;case
8:var
r=c[2];P(a,c[1]);return aB(r);case
2:case
4:var
p=c[2];P(a,c[1]);return ah(a,p);default:var
i=c[2];P(a,c[1]);var
d=a[2],f=a[1],j=f[1];if(f[2]<=d){bV(a,1);ax(a[1][1],a[2],i)}else
k(j,d,i);a[2]=d+1|0;return}}},function(e,b,c){function
f(a){if(typeof
a==="number")return c();switch(a[0]){case
8:var
i=a[2];return d(P,e,a[1],function(a){return c(aB(i))});case
7:return au(f,a[1]);case
6:var
j=a[2];return d(P,e,a[1],function(a){return S(j,0,function(a){return c(ah(e,a))})});case
1:var
b=a[2],h=a[1];if(0===b[0]){var
m=b[1];return d(P,e,h,function(a){ah(e,c_);return au(f,m)})}var
n=b[1];return d(P,e,h,function(a){ah(e,c$);return au(f,n)});case
0:var
o=a[1],p=bf(a[2]);return d(P,e,o,function(a){return c(ah(e,p))});case
3:case
5:var
g=a[2];return d(P,e,a[1],function(a){var
b=e[2],d=e[1],f=d[1];if(d[2]<=b){bV(e,1);ax(e[1][1],e[2],g)}else
k(f,b,g);e[2]=b+1|0;return c()});default:var
l=a[2];return d(P,e,a[1],function(a){return c(ah(e,l))})}}return f(b)});function
dM(c){return a(function(a){J(c,a);return 0},function(a,b){return d(J,c,a,function(a){return b(0)})})}var
ar=a(function(a,b){var
c=b[1];return i(dM(a),0,c)},function(a,b,c){var
d=b[1];return j(i,dM(a),0,d,c)});function
dL(){return a(function(a){var
c=aC<64?aC:64,b=[0,[0,E(c),c],0];P(b,a);return bU(b[1][1],0,b[2])},function(a,b){var
e=aC<64?aC:64,c=[0,[0,E(e),e],0];return d(P,c,a,function(a){return b(bU(c[1][1],0,c[2]))})})}var
r=a(function(a){var
b=a[1];return i(dL(),0,b)},function(a,b){var
c=a[1];return j(i,dL(),0,c,b)}),eZ=253,cL=c("%.12g"),cK=c(aE),dc=[0,[4,0,0,0,0],c(b9)],da=[0,[3,0,0],c("%S")],db=c(eJ),aO=a(function(a,b){var
c=a[b+1];if(!(1-(typeof
c==="number")))return h(r(dc),c);if(aI(c)===a1)return h(r(da),c);if(aI(c)!==eZ)return db;var
e=bB(cL,c),d=0,g=O(e);for(;;){if(g<=d)return aA(e,cK);var
f=T(e,d);a:{if(48<=f){if(58<=f)break a}else if(45!==f)break a;d=d+1|0;continue}return e}},function(a,b,c){var
d=a[b+1];if(!(1-(typeof
d==="number")))return B(r,dc,function(a){return S(a,d,c)});if(aI(d)===a1)return B(r,da,function(a){return S(a,d,c)});if(aI(d)!==eZ)return c(db);var
f=bB(cL,d),e=0,h=O(f);for(;;){if(h<=e)return c(aA(f,cK));var
g=T(f,e);a:{if(48<=g){if(58<=g)break a}else if(45!==g)break a;e=e+1|0;continue}return c(f)}}),dd=c(f),de=[0,[11,c(b8),[2,0,[2,0,0]]],c(", %s%s")],bl=a(function(a,b){if(a.length-1<=b)return dd;var
c=bl(a,b+1|0),d=aO(a,b);return z(r(de),d,c)},function(a,b,c){return a.length-1<=b?c(dd):d(bl,a,b+1|0,function(e){return d(aO,a,b,function(b){return B(r,de,function(a){return bo(a,b,e,c)})})})}),df=[0,[12,40,[2,0,[2,0,[12,41,0]]]],c("(%s%s)")],dg=c(f),dh=c(f),di=[0,[12,40,[2,0,[12,41,0]]],c("(%s)")],bm=a(function(a){if(0===aI(a)){var
d=a.length-1,k=a[1][1];if(2<d>>>0)var
g=bl(a,2),i=aO(a,1),b=z(r(df),i,g);else
switch(d){case
2:var
j=aO(a,1),b=h(r(di),j);break;case
0:var
b=dg;break;default:var
b=dh}var
c=[0,k,[0,b]]}else
var
c=[0,a[1],0];var
e=c[2],f=c[1];return e?aA(f,e[1]):f},function(a,b){function
e(a){var
c=a[2],d=a[1];return c?b(aA(d,c[1])):b(d)}if(0!==aI(a))return e([0,a[1],0]);var
f=a.length-1,g=a[1][1];function
c(a){return e([0,g,[0,a]])}if(2<f>>>0)return d(bl,a,2,function(e){return d(aO,a,1,function(b){return B(r,df,function(a){return bo(a,b,e,c)})})});switch(f){case
2:return d(aO,a,1,function(b){return B(r,di,function(a){return S(a,b,c)})});case
0:return c(dg);default:return c(dh)}}),e8=", characters ",dj=c("Out of memory"),dk=c("Stack overflow"),dl=c("Pattern matching failed"),dm=c("Assertion failed"),dn=c("Undefined recursive module"),aN=[0,[11,c('File "'),[2,0,[11,c('", line '),[4,0,0,0,[11,c(e8),[4,0,0,0,[12,45,[4,0,0,0,[11,c(eM),[2,0,0]]]]]]]]]],c('File "%s", line %d, characters %d-%d: %s')],bk=[0,0],as=a(function(a){a:{b:{var
b=bk[1];for(;;){if(!b)break;var
g=b[2],m=b[1];try{var
i=h(m,a)}catch(f){b=g;continue}if(i)break b;b=g}var
f=0;break a}var
f=[0,i[1]]}if(f)return f[1];if(a===aX)return dj;if(a===bS)return dk;if(a[1]===bR){var
c=a[2],j=c[3],n=c[2],o=c[1];return b1(r(aN),o,n,j,j+5|0,dl)}if(a[1]===p){var
d=a[2],k=d[3],q=d[2],s=d[1];return b1(r(aN),s,q,k,k+6|0,dm)}if(a[1]!==bT)return bm(a);var
e=a[2],l=e[3],t=e[2],u=e[1];return b1(r(aN),u,t,l,l+6|0,dn)},function(c,b){function
d(a){function
e(a){if(a)return b(a[1]);if(c===aX)return b(dj);if(c===bS)return b(dk);if(c[1]===bR){var
d=c[2],g=d[3],j=d[2],k=d[1],l=g+5|0;return B(r,aN,function(a){return b2(a,k,j,g,l,dl,b)})}if(c[1]===p){var
e=c[2],h=e[3],m=e[2],n=e[1],o=h+6|0;return B(r,aN,function(a){return b2(a,n,m,h,o,dm,b)})}if(c[1]!==bT)return B(bm,c,b);var
f=c[2],i=f[3],q=f[2],s=f[1],t=i+6|0;return B(r,aN,function(a){return b2(a,s,q,i,t,dn,b)})}if(!a)return e(0);var
f=a[2],g=a[1];bH(function(a){return au(d,f)});return S(g,c,function(a){aj();return a?e([0,a[1]]):au(d,f)})}return d(bk[1])}),hw=c("Raised at"),hx=c("Re-raised at"),hy=c("Raised by primitive operation at"),hz=c("Called from");function
dK(b){return function(a){return a?0===b?hw:hx:0===b?hy:hz}}var
dv=[0,[2,0,[12,10,0]],c("%s\n")],dp=[0,[12,32,[4,0,0,0,0]],c(" %d")],dt=[0,[11,c("s "),[4,0,0,0,[12,45,[4,0,0,0,0]]]],c("s %d-%d")],dq=c(" (inlined)"),ds=c(f),dr=[0,[2,0,[12,32,[2,0,[11,c(' in file "'),[2,0,[12,34,[2,0,[11,c(", line"),[2,0,[11,c(e8),[4,0,0,0,[12,45,[4,0,0,0,0]]]]]]]]]]]]],c('%s %s in file "%s"%s, line%s, characters %d-%d')],du=[0,[2,0,[11,c(" unknown location"),0]],c("%s unknown location")],aP=a(function(a,b){var
f=fu(b),j=f.length-2|0;if(j>=0){var
d=0;for(;;){var
c=bz(f,d)[d+1],g=dK(d);if(0===c[0]){if(c[3]===c[6])var
k=c[3],i=h(r(dp),k);else
var
s=c[6],t=c[3],i=z(r(dt),t,s);var
l=c[5],m=c[4],n=c[8]?dq:ds,o=c[2],p=c[9],q=g(c[1]),e=[0,hR(r(dr),q,p,o,n,i,m,l)]}else if(c[1])var
e=0;else
var
u=g(0),e=[0,h(r(du),u)];if(e){var
v=e[1];h(ar(a,dv),v)}var
w=d+1|0;if(j===d)break;d=w}}},function(o,b,c){var
i=fu(b),j=i.length-2|0;function
g(){return c()}function
f(b){var
a=bz(i,b)[b+1],h=dK(b);function
c(a){function
c(a){var
c=b+1|0;return j!==b?au(f,c):g()}if(!a)return c(0);var
e=a[1];return d(ar,o,dv,function(a){return S(a,e,c)})}if(0!==a[0]){if(a[1])return c(0);var
n=h(0);return B(r,du,function(a){return S(a,n,function(a){return c([0,a])})})}function
e(j){var
g=a[5],i=a[4],b=a[8]?dq:ds,d=a[2],e=a[9],f=h(a[1]);return B(r,dr,function(a){return hS(a,f,e,d,b,j,i,g,function(a){return c([0,a])})})}if(a[3]===a[6]){var
k=a[3];return B(r,dp,function(a){return S(a,k,e)})}var
l=a[6],m=a[3];return B(r,dt,function(a){return bo(a,m,l,e)})}return j<0?g():f(0)});function
dw(a){for(;;){var
b=bk[1],c=1-hZ(bk,0,b,[0,a,b]);if(!c)return c}}var
ep="Fatal error: exception %s\n",dB=[0,[11,c(b_),[2,0,[12,10,0]]],c(ep)],dC=[0,[11,c("Fatal error in uncaught exception handler: exception "),[2,0,[12,10,0]]],c("Fatal error in uncaught exception handler: exception %s\n")],dA=c("Fatal error: out of memory in uncaught exception handler"),dy=[0,[11,c(b_),[2,0,[12,10,0]]],c(ep)],dx=[0,c(f),c("(Cannot print locations:\n bytecode executable program file not found)"),c("(Cannot print locations:\n bytecode executable program file appears to be corrupt)"),c("(Cannot print locations:\n bytecode executable program file has wrong magic number)"),c("(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)")],dz=[0];cA(c(et),a(function(a,b){try{try{var
i=b?dz:bC(0);try{be()}catch(f){}try{var
f=as(a);h(ar(F,dy),f);aP(F,i);var
c=fB(0);if(c<0){var
d=aY(c);bd(bz(dx,d)[d+1])}var
o=ac(F),j=o}catch(f){var
l=bO(f),m=as(a);h(ar(F,dB),m);aP(F,i);var
n=as(l);h(ar(F,dC),n);aP(F,bC(0));var
j=ac(F)}var
k=j}catch(f){var
e=bO(f);if(e!==aX)throw g(e,0);var
k=bd(dA)}return k}catch(f){return 0}},function(a,b,c){bH(function(a){return c(0)});function
e(a){aj();return c(a)}bH(function(a){if(a===aX)return e(bd(dA));var
b=aj();return b(g(a,0))});var
h=b?dz:bC(0);try{be()}catch(f){}function
f(a){aj();return e(a)}bH(function(e){var
b=bC(0);return B(as,a,function(c){return d(ar,F,dB,function(a){return S(a,c,function(a){return d(aP,F,h,function(a){return B(as,e,function(c){return d(ar,F,dC,function(a){return S(a,c,function(a){return d(aP,F,b,function(a){return f(ac(F))})})})})})})})})});return B(as,a,function(b){return d(ar,F,dy,function(a){return S(a,b,function(a){return d(aP,F,h,function(a){var
c=fB(0);if(c<0){var
b=aY(c);bd(bz(dx,b)[b+1])}var
d=ac(F);aj();return f(d)})})})})}));function
bZ(a,b){var
c=aI(b)===u?b:b[1];cA(a,c)}var
b0=[u,c("Stdlib__Effect.Unhandled"),aH(0)],dD=[0,[11,c("Stdlib.Effect.Unhandled("),[2,0,[12,41,0]]],c("Stdlib.Effect.Unhandled(%s)")];dw(a(function(a){if(a[1]!==b0)return 0;var
b=bm(a[2]);return[0,h(r(dD),b)]},function(a,b){return a[1]===b0?B(bm,a[2],function(c){return B(r,dD,function(a){return S(a,c,function(a){return b([0,a])})})}):b(0)}));bZ(c(ch),[0,b0,[u,c("Stdlib__Effect.Should_not_see_this__"),aH(0)]]);bZ(c(e3),[u,c("Stdlib__Effect.Continuation_already_resumed"),aH(0)]);var
dE=[u,c("Jsoo_runtime.Error.Exn"),aH(0)];bZ(c(cd),[0,dE,[0]]);var
at=n;at.String;at.RegExp;at.Object;at.Array;at.Date;at.Math;function
dF(a){return Z(a.toString())}at.JSON;var
hA=at.Error;dw(function(a){return a
instanceof
hA?[0,dF(a)]:a[1]===dE?[0,dF(a[2])]:0});var
bn=[u,c("Repro.Await"),aH(0)];function
a0(a){console.log(ct(a));return 0}var
dG=c("exception: "),hB=a(function(a){return a0(aA(dG,as(a)))},function(a,b){return B(as,a,function(a){return b(a0(aA(dG,a)))})});function
dI(){return function(a){return a}}function
hE(c){return a(function(a){return fM(dI(),0,c,c)},function(a,b){var
d=dI();return B(d,0,cB(c,c,b))})}function
dJ(){return function(a){setTimeout(fA(hE(a)),0.);return 0}}var
dH=c("continued"),hD=a(function(a){fH(bn);return a0(dH)},function(a,b){return iH(bn,function(a){return b(a0(dH))})}),hC=c("returned"),el=hW(function(a){return a0(hC)},hB,a(function(a,b,c){var
d=a===bn?1:0,e=d?[0,dJ()]:d;if(!e)return fH(a);var
f=e[1];b[2]=c;return h(f,b)},function(a,b,c,d){var
f=a===bn?1:0,e=f?[0,dJ()]:f;if(!e)return iJ(a,b,c,d);var
g=e[1];b[2]=c;return d(g(b))}));fM(hD,0,el,el);be();return}(globalThis));
