// Generated by js_of_ocaml
//# buildInfo:effects=cps, kind=exe, use-js-string=true, version=6.3.2
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(c){"use strict";function
ak(f,e){var
g=f.l>=0?f.l:f.l=f.length,d=e.length,a=g-d;if(a===0)return f(...e);else if(a<0){var
h=e.slice(g-1),c=e[d-1];e=e.slice(0,g);e[g-1]=function(a){if(typeof
a!=="function")return c(a);var
b=h.slice();b[b.length-1]=c;return ak(a,b)};return f(...e)}else{d--;var
c=e[d];switch(a){case
1:{var
b=function(a,b){var
g=new
Array(d+2);for(var
c=0;c<d;c++)g[c]=e[c];g[d]=a;g[d+1]=b;return f(...g)};break}case
2:{var
b=function(a,b,c){var
g=new
Array(d+3);for(var
h=0;h<d;h++)g[h]=e[h];g[d]=a;g[d+1]=b;g[d+2]=c;return f(...g)};break}default:{e.length=d;var
b=function(...a){if(a.length===0)a=[undefined];return ak(f,e.concat(a))}}}b.l=a+1;return c(b)}}var
e7=ak,j={k:0,x:0,h:0,e:0};function
b6(){var
a=j.e;j.e=0;j=a;return a.k}var
bi=0;function
O(){return--bi>0}function
R(a,b,c){return{joo_tramp:a,joo_args:b,joo_direct:c}}function
dw(a,b){var
c=[b,b6()];return O()?e7(a,c):R(a,c,0)}function
eZ(a){var
b=j.h[1];return dw(b,a)}function
eY(a){var
b=j.h[2];return dw(b,a)}function
eX(a,b,c){var
d=[0,a,b,c];return{k:eZ,x:{h:eY,t:0},h:d,e:0}}function
e0(a,b,c,d){if(a[b+1]===c){a[b+1]=d;return 1}return 0}var
cU=4096,f="",ao=1024;function
bk(a,b,c){var
d=String.fromCharCode;if(b===0&&c<=cU&&c===a.length)return d.apply(null,a);var
e=f;for(;0<c;b+=ao,c-=ao)e+=d.apply(null,a.subarray(b,b+Math.min(c,ao)));return e}function
a$(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aj(a,b,c,d,e){if(e===0)return 0;if(d===0&&(e>=c.l||c.t===2&&e>=c.c.length)){c.c=a.t===4?bk(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else if(c.t===2&&d===c.c.length){c.c+=a.t===4?bk(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else{if(c.t!==4)a$(c);var
g=a.c,h=c.c;if(a.t===4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}var
d5=new
TextDecoder();function
b_(a){if(a.t!==4)a$(a);return a.c}function
am(a,b){return b.repeat(a)}function
ba(a){if(a.t===2)a.c+=am(a.l-a.c.length,"\0");else
a.c=bk(a.c,0,a.c.length);a.t=0}var
a6=127;function
ca(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>a6)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}class
ar{constructor(a,b,c){this.t=a;this.c=b;this.l=c}toString(){switch(this.t){case
9:case
8:return this.c;case
4:case
2:ba(this);case
0:if(ca(this.c))this.t=9;else
this.t=8;return this.c}}toUtf16(){if(this.t===9)return this.c;var
a=b_(this);return d5.decode(a)}slice(){var
a=this.t===4?this.c.slice():this.c;return new
ar(this.t,a,this.l)}}function
dD(a){return new
ar(0,a,a.length)}function
aD(a){return a}function
as(a){return dD(aD(a))}function
a_(a,b,c,d,e){aj(as(a),b,c,d,e);return 0}var
d4={};function
fT(a){if(d4[a])return d4[a];var
b=c.process;if(b&&b.env&&b.env[a]!==undefined)return b.env[a];if(c.jsoo_env&&typeof
c.jsoo_env[a]==="string")return c.jsoo_env[a]}var
bg=0;(function(){var
c=fT("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]==="b"){bg=1;break}else if(b[a].startsWith("b="))bg=+b[a].slice(2);else
continue}}());var
fK=bg,z=[0],o=248;function
fa(a,b){if(!a.js_error||b||a[0]===o)a.js_error=new
c.Error("Js exception containing backtrace");return a}function
g(a,b){return bg&&fK?fa(a,b):a}function
dX(a,b){throw g([0,a,b])}function
_(a){return a}function
dZ(a,b){dX(a,_(b))}function
u(a){dZ(z.Invalid_argument,a)}var
bE="index out of bounds";function
e4(){u(bE)}var
S=0xff;function
r(a,b,c){c&=S;if(a.t!==4){if(b===a.c.length){a.c+=String.fromCharCode(c);if(b+1===a.l)a.t=0;return 0}a$(a)}a.c[b]=c;return 0}function
at(a,b,c){if(b>>>0>=a.l)e4();return r(a,b,c)}function
bS(a,b){switch(a.t&6){case
0:return a.c.charCodeAt(b);case
2:if(b>=a.c.length)return 0;return a.c.charCodeAt(b);case
4:return a.c[b]}}var
fU=new
TextEncoder();function
fP(a,b,c){var
d=String.fromCharCode;if(b===0&&c<=cU&&c===a.length)return d.apply(null,a);var
e=f;for(;0<c;b+=ao,c-=ao)e+=d.apply(null,a.slice(b,b+Math.min(c,ao)));return e}function
fO(a){return _(fP(a,0,a.length))}function
Q(a){if(ca(a))return _(a);var
b=fU.encode(a);return fO(b)}var
dU={};function
al(a){return dU[a]}var
bL="jsError";function
d2(a){{if(Array.isArray(a))return a;var
b;if(c.RangeError&&a
instanceof
c.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=z.Stack_overflow;else if(c.InternalError&&a
instanceof
c.InternalError&&a.message&&a.message.match(/too much recursion/i))b=z.Stack_overflow;else if(a
instanceof
c.Error&&al(bL))b=[0,al(bL),a];else
b=[0,z.Failure,Q(String(a))];if(a
instanceof
c.Error)b.js_error=a;return b}}function
aC(a,b){var
f=bi,e=j;try{j={k:0,x:0,h:0,e:0};var
c={joo_tramp:a,joo_args:b.concat(function(a){return a})};do{bi=40;try{c=ak(c.joo_tramp,c.joo_args)}catch(f){if(!j.x)throw f;var
d=j.x.h;j.x=j.x.t;c={joo_tramp:d,joo_args:[d2(f)]}}}while(c?.joo_args)}finally{bi=f;j=e}return c}function
a9(){u(bE)}function
dF(a,b){if(b>>>0>=a.length-1)a9();return a}function
e8(a){if(Number.isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!==0)return 1;return 2}return Number.isNaN(a)?4:3}function
dI(a){var
b=a[1];a[1]=0;return b}function
e_(){return[0]}function
C(a){if(a<0)u("Bytes.create");return new
ar(a?2:9,f,a)}function
fb(a,b,c,d){if(c>0)if(b===0&&(c>=a.l||a.t===2&&c>=a.c.length))if(d===0){a.c=f;a.t=2}else{a.c=am(c,String.fromCharCode(d));a.t=c===a.l?0:2}else{if(a.t!==4)a$(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}var
ap="-",aB="+",ac=" ",K="0";function
b5(a){a=aD(a);var
e=a.length;if(e>31)u("format_int: format too long");var
b={justify:aB,signstyle:ap,filler:ac,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=ap;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=K;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;break;case"d":case"i":b.signedconv=true;b.base=10;break;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}var
cW="0x";function
bU(a,b){if(a.uppercase)b=b.toUpperCase();var
e=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!==ap))e++;if(a.alternate){if(a.base===8)e+=1;if(a.base===16)e+=2}var
c=f;if(a.justify===aB&&a.filler===ac)for(var
d=e;d<a.width;d++)c+=ac;if(a.signedconv)if(a.sign<0)c+=ap;else if(a.signstyle!==ap)c+=a.signstyle;if(a.alternate&&a.base===8)c+=K;if(a.alternate&&a.base===16)c+=a.uppercase?"0X":cW;if(a.justify===aB&&a.filler===K)for(var
d=e;d<a.width;d++)c+=K;c+=b;if(a.justify===ap)for(var
d=e;d<a.width;d++)c+=ac;return _(c)}var
aq=".",bO="nan";function
bV(a,b){function
k(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=Number.parseInt(a.toString().split(aB)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=am(c,K);if(b>0)a=a+aq+am(b,K);return a}else
return a.toFixed(b)}}var
c,f=b5(a),e=f.prec<0?6:f.prec;if(b<0||b===0&&1/b===Number.NEGATIVE_INFINITY){f.sign=-1;b=-b}if(Number.isNaN(b)){c=bO;f.filler=ac}else if(!Number.isFinite(b)){c="inf";f.filler=ac}else{var
h="e";switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+K+c.slice(d-1);break;case"f":c=k(b,e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
j=c.indexOf(h),i=+c.slice(j+1);if(i<-4||b>=1e21||b.toFixed(0).length>e){var
d=j-1;while(c.charAt(d)===K)d--;if(c.charAt(d)===aq)d--;c=c.slice(0,d+1)+c.slice(j);d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+K+c.slice(d-1);break}else{var
g=e;if(i<0){g-=i+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)===K)d--;if(c.charAt(d)===aq)d--;c=c.slice(0,d+1)}}break}}return bU(f,c)}var
bH="%d";function
bb(a,b){if(aD(a)===bH)return _(f+b);var
c=b5(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
d=b.toString(c.base);if(c.prec>=0){c.filler=ac;var
e=c.prec-d.length;if(e>0)d=am(e,K)+d}return bU(c,d)}var
fI=0;function
av(){return fI++}var
bD="Failure";function
au(a){if(!z.Failure)z.Failure=[o,_(bD),-3];dZ(z.Failure,a)}var
d6=new
ArrayBuffer(ao);function
b3(a){if(ca(a))return a;var
c=a.length<=d6.length?new
Uint8Array(d6,0,a.length):new
Uint8Array(a.length);for(var
b=0;b<a.length;b++)c[b]=a.charCodeAt(b);return d5.decode(c)}var
cb=c.Deno?.build?.os==="windows"||c.process?.platform==="win32";function
bm(){return c.process?.versions?.node!==undefined}var
V="/";function
fV(){function
a(a){if(a.charAt(0)===V)return[f,a.slice(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||f,e=c.length>0&&c.charAt(1)!==":";if(b[2]||e){var
d=b[1]||f,g=b[2]||f;return[d,a.slice(d.length+g.length)]}return}return cb?b:a}var
cd=fV();function
d1(a){return a.slice(-1)!==V?a+V:a}if(bm()&&c.process&&c.process.cwd)var
aO=c.process.cwd().replace(/\\/g,V);else
var
aO="/static";aO=d1(aO);function
fz(a){a=b3(a);if(!cd(a))a=aO+a;var
e=cd(a),d=e[1].split(/[/\\]/),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
A(a){dX(z.Sys_error,Q(a))}function
dY(a,b){throw g([0,a].concat(b))}var
az="EINVAL",bF="EISDIR",bK="ESPIPE",aA="EBADF",c9="ENOTEMPTY",a5="ENOTDIR",aK="ENOENT",bN="EEXIST",fW=["E2BIG","EACCES","EAGAIN",aA,"EBUSY","ECHILD","EDEADLK","EDOM",bN,"EFAULT","EFBIG","EINTR",az,"EIO",bF,"EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",aK,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",a5,c9,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS",bK,"ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
d8(a,b,c,d){var
e=fW.indexOf(a);if(e<0){if(d==null)d=-9999;e=[0,-d]}var
g=[e,Q(b||f),Q(c||f)];return g}var
dd="Unix.Unix_error",c1=": ",bG=", ";function
p(a,b,c,d,e){var
f=al(dd);if(a&&f)dY(f,d8(b,c,e));else{var
d=b+c1+d+bG+c;if(e!==undefined)d+=" '"+e+"'";A(d)}}function
b1(a){return a
instanceof
ar}function
b2(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
e6(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
ar(4,a,a.length)}var
a3="no such file or directory";function
b7(a,b){p(b,aK,a3,a)}function
dE(a){return new
ar(4,a,a.length)}function
Y(a){return a.l}function
dt(){}class
ai
extends
dt{constructor(a){super();this.data=a}truncate(a){var
b=this.data,c=Y(b);this.data=C(a|0);aj(b,0,this.data,0,Math.min(a,c))}length(){return Y(this.data)}write(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=C(a+d),g=this.data;this.data=f;aj(g,0,this.data,0,e)}aj(dE(b),c,this.data,a,d);return d}read(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d>0){var
f=C(d|0);aj(this.data,a,f,0,d);b.set(b_(f),c);return d}return 0}}var
aL="bad file descriptor",dp="write",cM="read",a4="lseek",aN="invalid argument";class
eU{constructor(a,b,c){this.file=b;this.name=a;this.flags=c;this.offset=0;this.seeked=false}err_closed(a,b){p(b,aA,a,aL)}length(){if(this.file)return this.file.length();this.err_closed("length")}truncate(a,b){var
c="truncate";if(this.file){if(!(this.flags.wronly||this.flags.rdwr))p(b,az,c,aN);return this.file.truncate(a)}this.err_closed(c,b)}write(a,b,c,d){if(this.file&&(this.flags.wronly||this.flags.rdwr)){var
e=this.offset;c=this.file.write(e,a,b,c);this.offset+=c;return c}this.err_closed(dp,d)}read(a,b,c,d){if(this.file&&!this.flags.wronly){var
e=this.offset;c=this.file.read(e,a,b,c);this.offset+=c;return c}this.err_closed(cM,d)}seek(a,b,c){switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)p(c,az,a4,aN);this.offset=a;this.seeked=true;return a}pos(){return this.offset}close(){if(!this.file)this.err_closed("close");this.file=undefined}check_stream_semantics(a){if(!this.file)return this.err_closed(a,1)}}var
cV="illegal operation on a directory",c2="file already exists",bM="open",cE="not a directory";class
ds{constructor(a,b){this.content={};this.root=a;this.lookupFun=b}nm(a){return this.root+a}create_dir_if_needed(a){var
d=a.split(V),c=f;for(var
b=0;b<d.length-1;b++){c+=d[b]+V;if(this.content[c])continue;this.content[c]=Symbol("directory")}}slash(a){return/\/$/.test(a)?a:a+V}lookup(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(Q(this.root),Q(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
ai(as(b[1]))}}}exists(a,b){if(a===f)return 1;var
c=this.slash(a);if(this.content[c])return 1;if(!b)this.lookup(a);return this.content[a]?1:0}isFile(a){return this.exists(a)&&!this.is_dir(a)?1:0}rename_dir(a,b){if(this.exists(b)){if(!this.is_dir(b))A(this.nm(b)+" : file already exists and is not a directory");if(this.readdir(b).length>0)A(this.nm(b)+" : directory not empty")}var
d=this.slash(a),c=this.slash(b);this.create_dir_if_needed(c);for(const
b
of
this.readdir(a))this.rename(d+b,c+b);delete
this.content[d]}rename(a,b){if(!this.exists(a))A(this.nm(a)+" : no such file or directory");if(this.is_dir(a))this.rename_dir(a,b);else{if(this.exists(b)&&this.is_dir(b))A(this.nm(b)+" : file already exists and is a directory");this.content[b]=this.content[a];delete
this.content[a]}}mkdir(a,b,c){var
e="mkdir";if(this.exists(a))p(c,bN,e,c2,this.nm(a));var
d=/^(.*)\/[^/]+/.exec(a);d=d?.[1]||f;if(!this.exists(d))p(c,aK,e,a3,this.nm(a));if(!this.is_dir(d))p(c,a5,e,cE,this.nm(a));this.create_dir_if_needed(this.slash(a))}rmdir(a,b){var
d=a===f?f:this.slash(a),c="rmdir";if(!this.exists(a))p(b,aK,c,a3,this.nm(a));if(!this.is_dir(a))p(b,a5,c,cE,this.nm(a));for(var
e
in
this.content)if(e.startsWith(d)&&e!==d)p(b,c9,c,"directory not empty",this.nm(a));delete
this.content[d]}readdir(a){var
d=a===f?f:this.slash(a);if(!this.exists(a))A(a+": No such file or directory");if(!this.is_dir(a))A(a+": Not a directory");var
h={},g=[];for(var
c
in
this.content)if(c.startsWith(d)&&c!==d){var
e=c.indexOf(V,d.length);if(e<0)e=undefined;var
b=c.slice(d.length,e);if(b&&!h[b]){h[b]=true;g.push(b)}}return g}opendir(a,b){var
c=this.readdir(a),d=false,e=0,f="readdir";return{readSync:function(){if(d)p(b,aA,f,aL);if(e===c.length)return null;var
a=c[e];e++;return{name:a}},closeSync:function(){if(d)p(b,aA,f,aL);d=true;c=[]}}}is_dir(a){if(a===f)return true;var
b=this.slash(a);return this.content[b]?1:0}unlink(a,b){if(!this.exists(a,true))p(b,aK,"unlink",a3,a);delete
this.content[a];return 0}access(a,b,c){this.lookup(a);if(this.content[a]){if(this.is_dir(a))p(c,"EACCESS","access","permission denied,",this.nm(a))}else
b7(this.nm(a),c);return 0}open(a,b,c,d){var
e;this.lookup(a);if(this.content[a]){if(this.is_dir(a))p(d,bF,bM,cV,this.nm(a));if(b.create&&b.excl)p(d,bN,bM,c2,this.nm(a));e=this.content[a];if(b.truncate)e.truncate(0)}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
ai(C(0));e=this.content[a]}else
b7(this.nm(a),d);return new
eU(this.nm(a),e,b)}truncate(a,b,c){var
d;this.lookup(a);if(this.content[a]){if(this.is_dir(a))p(c,bF,bM,cV,this.nm(a));d=this.content[a];d.truncate(b)}else
b7(this.nm(a),c)}register(a,b){var
c;if(this.content[a])A(this.nm(a)+" : file already exists");if(b1(b))c=new
ai(b);if(b2(b))c=new
ai(as(b));else if(Array.isArray(b))c=new
ai(e6(b));else if(typeof
b==="string")c=new
ai(dD(b));else if(b.toString){var
d=as(Q(b.toString()));c=new
ai(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
A(this.nm(a)+" : registering file with invalid content type")}}function
m(a,b,c){var
d=al(dd);if(b&&d){var
e=d8(a.code,c||a.syscall,a.path,a.errno);dY(d,e)}else
A(a.toString())}var
aQ=Math.pow(2,-24);function
dW(a){throw a}function
d0(){dW(z.Division_by_zero)}var
N=0xffff,W=0x8000,B=0xffffff,c4=0x000000;class
d{constructor(a,b,c){this.lo=a&B;this.mi=b&B;this.hi=c&N;this.caml_custom="_j"}static
UNSIGNED_MAX=new
d(B,B,N);static
SIGNED_MAX=new
d(B,B,0x7fff);static
SIGNED_MIN=new
d(c4,c4,W);slice(){return new
d(this.lo,this.mi,this.hi)}ucompare(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}compare(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}neg(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
d(a,b,c)}add(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),e=this.hi+a.hi+(c>>24);return new
d(b,c,e)}sub(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),e=this.hi-a.hi+(c>>24);return new
d(b,c,e)}mul(a){var
b=this.lo*a.lo,c=(b*aQ|0)+this.mi*a.lo+this.lo*a.mi,e=(c*aQ|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
d(b,c,e)}isZero(){return(this.lo|this.mi|this.hi)===0}isNeg(){return this.hi<<16<0}and(a){return new
d(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)}or(a){return new
d(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)}xor(a){return new
d(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)}shift_left(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
d(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
d(0,0,this.lo<<a-48)}shift_right_unsigned(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
d(this.hi>>a-48,0,0)}shift_right(a){a=a&63;if(a===0)return this;var
c=this.hi<<16>>16;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,b&N);return new
d(this.hi<<16>>a-32,b,b)}lsl1(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&B;this.lo=this.lo<<1&B}lsr1(){this.lo=(this.lo>>>1|this.mi<<23)&B;this.mi=(this.mi>>>1|this.hi<<23)&B;this.hi=this.hi>>>1}udivmod(a){var
e=0,c=this.slice(),b=a.slice(),f=new
d(0,0,0);while(c.ucompare(b)>0){e++;b.lsl1()}while(e>=0){e--;f.lsl1();if(c.ucompare(b)>=0){f.lo++;c=c.sub(b)}b.lsr1()}return{quotient:f,modulus:c}}div(a){var
b=this;if(a.isZero())d0();var
d=b.hi^a.hi;if(b.hi&W)b=b.neg();if(a.hi&W)a=a.neg();var
c=b.udivmod(a).quotient;if(d&W)c=c.neg();return c}mod(a){var
b=this;if(a.isZero())d0();var
d=b.hi;if(b.hi&W)b=b.neg();if(a.hi&W)a=a.neg();var
c=b.udivmod(a).modulus;if(d&W)c=c.neg();return c}toInt(){return this.lo|this.mi<<24}toFloat(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo}toArray(){return[this.hi>>8,this.hi&S,this.mi>>16,this.mi>>8&S,this.mi&S,this.lo>>16,this.lo>>8&S,this.lo&S]}lo32(){return this.lo|(this.mi&S)<<24}hi32(){return this.mi>>>8&N|this.hi<<16}}function
fs(a){if(a<0)a=Math.ceil(a);return new
d(a&B,Math.floor(a*aQ)&B,Math.floor(a*aQ*aQ)&N)}var
ad=1000;function
cc(a,b){var
c;if(a.isFile())c=0;else if(a.isDirectory())c=1;else if(a.isCharacterDevice())c=2;else if(a.isBlockDevice())c=3;else if(a.isSymbolicLink())c=4;else if(a.isFIFO())c=5;else if(a.isSocket())c=6;return[0,a.dev,a.ino|0,c,a.mode,a.nlink,a.uid,a.gid,a.rdev,b?fs(a.size):a.size|0,a.atimeMs/ad,a.mtimeMs/ad,a.ctimeMs/ad]}function
E(a){return a.length}function
bj(a,b){return a.charCodeAt(b)}function
fZ(a){var
d=E(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=bj(a,b);return c}var
cX="illegal seek",bJ="node:fs";class
bQ
extends
dt{constructor(a,b){super();this.fs=require(bJ);this.fd=a;this.flags=b;try{var
c=this.fs.fstatSync(a);b.noSeek=c.isCharacterDevice()||c.isFIFO()||c.isSocket();this.offset=this.flags.append?c.size:0}catch(f){b.noSeek=true;this.offset=0}this.seeked=false}truncate(a,b){try{this.fs.ftruncateSync(this.fd,a|0);if(this.offset>a)this.offset=a}catch(f){m(f,b)}}isatty(){var
a=require("node:tty");return a.isatty(this.fd)?1:0}length(){try{return this.fs.fstatSync(this.fd).size}catch(f){A(f.toString())}}write(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.writeSync(this.fd,a,b,c);else
var
e=this.fs.writeSync(this.fd,a,b,c,this.offset);this.offset+=e}catch(f){m(f,d)}return e}read(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.readSync(this.fd,a,b,c);else
var
e=this.fs.readSync(this.fd,a,b,c,this.offset);this.offset+=e;return e}catch(f){m(f,d)}}seek(a,b,c){if(this.flags.noSeek)p(c,bK,a4,cX);switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)p(c,az,a4,aN);this.offset=a;this.seeked=true;return this.offset}pos(){return this.offset}stat(a){try{var
b=this.fs.fstatSync(this.fd);return cc(b,a)}catch(f){m(f,1)}}chmod(a){try{this.fs.fchmodSync(this.fd,a);return 0}catch(f){m(f,1)}}sync(){try{this.fs.fsyncSync(this.fd);return 0}catch(f){m(f,1)}}close(a){try{this.fs.closeSync(this.fd);return 0}catch(f){m(f,a)}}check_stream_semantics(a){try{var
b=this.fs.fstatSync(this.fd)}catch(f){m(f,1,a)}if(!(b.isFile()||b.isCharacterDevice()||b.isFIFO()||b.isSocket()))p(1,az,a,aN)}}class
du{constructor(a){this.fs=require(bJ);this.root=a}nm(a){return this.root+a}exists(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}}isFile(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){A(f.toString())}}mkdir(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){m(f,c)}}rmdir(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){m(f,b)}}readdir(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){m(f,b)}}is_dir(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){A(f.toString())}}unlink(a,b){try{this.fs.unlinkSync(this.nm(a));return 0}catch(f){m(f,b)}}utimes(a,b,c,d){try{if(b===0&&c===0){b=new
Date().getTime()/ad;c=b}this.fs.utimesSync(this.nm(a),b,c);return 0}catch(f){m(f,d)}}truncate(a,b,c){try{this.fs.truncateSync(this.nm(a),b|0);return 0}catch(f){m(f,c)}}access(a,b,c){var
d=this.fs.constants,e=0;for(var
f
in
b)switch(f){case"r":e|=d.R_OK;break;case"w":e|=d.W_OK;break;case"x":e|=cb?d.R_OK:d.X_OK;break;case"f":e|=d.F_OK;break}try{this.fs.accessSync(this.nm(a),e);return 0}catch(f){m(f,c)}}open(a,b,c,d){var
f=this.fs.constants,e=0;for(var
h
in
b)switch(h){case"rdonly":e|=f.O_RDONLY;break;case"wronly":e|=f.O_WRONLY;break;case"rdwr":e|=f.O_RDWR;break;case"append":e|=f.O_APPEND;break;case"create":e|=f.O_CREAT;break;case"truncate":e|=f.O_TRUNC;break;case"excl":e|=f.O_EXCL;break;case"binary":e|=f.O_BINARY;break;case"text":e|=f.O_TEXT;break;case"nonblock":e|=f.O_NONBLOCK;break;case"noctty":e|=f.O_NOCTTY;break;case"dsync":e|=f.O_DSYNC;break;case"sync":e|=f.O_SYNC;break}try{var
g=this.fs.openSync(this.nm(a),e,c);return new
bQ(g,b)}catch(f){m(f,d)}}slash(a){return/\/$/.test(a)?a:a+V}rename(a,b,c){if(cb)try{var
d=this.nm(b),e=this.nm(a),h,g;if((h=this.fs.statSync(d,{throwIfNoEntry:false}))&&(g=this.fs.statSync(e,{throwIfNoEntry:false}))&&g.isDirectory())if(h.isDirectory()){if(!this.slash(d).startsWith(this.slash(e)))try{this.fs.rmdirSync(d)}catch{}}else{var
f=new
Error(`ENOTDIR: not a directory, rename '${e}' -> '${d}'`);throw Object.assign(f,{errno:-20,code:a5,syscall:"rename",path:d})}this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){m(f,c)}else
try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){m(f,c)}}stat(a,b,c){try{var
d=this.fs.statSync(this.nm(a));return cc(d,b)}catch(f){m(f,c)}}lstat(a,b,c){try{var
d=this.fs.lstatSync(this.nm(a));return cc(d,b)}catch(f){m(f,c)}}chmod(a,b,c){try{this.fs.chmodSync(this.nm(a),b);return 0}catch(f){m(f,c)}}link(a,b,c){try{this.fs.linkSync(this.nm(a),this.nm(b));return 0}catch(f){m(f,c)}}symlink(a,b,c,d){try{this.fs.symlinkSync(b,this.nm(c),a===0?null:a[1]?"dir":"file");return 0}catch(f){m(f,d)}}readlink(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return Q(c)}catch(f){m(f,b)}}opendir(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){m(f,b)}}}function
dN(a){var
b=cd(a);if(!b)return;return b[0]+V}var
bh=dN(aO)||au("unable to compute caml_root"),aF=[];if(bm())aF.push({path:bh,device:new
du(bh)});else
aF.push({path:bh,device:new
ds(bh)});var
cI="/static/";aF.push({path:cI,device:new
ds(cI)});function
d9(a){var
g=fz(a),a=g.join(V),f=d1(a),c;for(var
d=0;d<aF.length;d++){var
b=aF[d];if(f.search(b.path)===0&&(!c||c.path.length<b.path.length))c={path:b.path,device:b.device,rest:a.slice(b.path.length,a.length)}}if(!c&&bm()){var
e=dN(a);if(e?.match(/^[a-zA-Z]:\/$/)){var
b={path:e,device:new
du(e)};aF.push(b);c={path:b.path,device:b.device,rest:a.slice(b.path.length,a.length)}}}if(c)return c;A("no device found for "+f)}function
e$(a,b){var
c=d9(a);if(!c.device.register)au("cannot register file");c.device.register(c.rest,b);return 0}function
d3(a,b){var
a=Q(a),b=_(b);return e$(a,b)}function
fd(){var
b=c.jsoo_fs_tmp;if(b)for(var
a=0;a<b.length;a++)d3(b[a].name,b[a].content);c.jsoo_create_file=d3;c.jsoo_fs_tmp=[];return 0}function
dM(a){return[0]}var
cH="infinity";function
fh(a,b,c){if(!Number.isFinite(a)){if(Number.isNaN(a))return Q(bO);return Q(a>0?cH:"-infinity")}var
k=a===0&&1/a===Number.NEGATIVE_INFINITY?1:a>=0?0:1;if(k)a=-a;var
e=0;if(a===0);else if(a<1)while(a<1&&e>-1022){a*=2;e--}else
while(a>=2){a/=2;e++}var
l=e<0?f:aB,g=f;if(k)g=ap;else
switch(c){case
43:g=aB;break;case
32:g=ac;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(aq);if(j<0)d+=aq+am(b,K);else{var
h=j+1+b;if(d.length<h)d+=am(h-d.length,K);else
d=d.slice(0,h)}}return Q(g+cW+d+"p"+l+e.toString(10))}function
fp(a){return+a.isZero()}function
ft(a){return new
d(a&B,a>>24&B,a>>31&N)}function
fu(a){return a.toInt()}function
fo(a){return+a.isNeg()}function
fr(a){return a.neg()}function
fm(a,b){var
c=b5(a);if(c.signedconv&&fo(b)){c.sign=-1;b=fr(b)}var
d=f,i=ft(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(fu(g.modulus))+d}while(!fp(b));if(c.prec>=0){c.filler=ac;var
e=c.prec-d.length;if(e>0)d=am(e,K)+d}return bU(c,d)}function
dO(c){return function(...a){if(a.length===0)a=[undefined];var
b=aC(c,a);return b
instanceof
Function?dO(b):b}}function
fB(){return 0}function
dr(a){this.id=a}class
fA{constructor(){this.map=new
c.WeakMap();this.opened=new
c.Set()}close(a){this.opened.delete(a)}get(a){return this.map.get(a)}set(a,b){if(b.opened)this.opened.add(a);return this.map.set(a,b)}all(){return this.opened.values()}}var
be=new
fA();function
b4(a){return be.get(a)}function
ae(a){var
b=b4(a);if(!b.opened)A("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr===0)return 0;if(b.output)b.output(bk(b.buffer,0,b.buffer_curr));else
for(var
c=0;c<b.buffer_curr;)c+=b.file.write(b.buffer,c,b.buffer_curr-c,false);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}var
b0=65536;function
fS(a,b){if(b.altname)try{var
d=require(bJ),c=d.openSync(b.altname,"rs");return new
bQ(c,b)}catch(f){}return new
bQ(a,b)}var
aE=new
Array(3);class
eV
extends
ai{constructor(a,b){super(C(0));this.log=function(a){return 0};if(a===1&&typeof
console.log==="function")this.log=console.log;else if(a===2&&typeof
console.error==="function")this.log=console.error;else if(typeof
console.log==="function")this.log=console.log;this.flags=b}length(){return 0}truncate(a,b){p(b,az,"ftruncate",aN)}write(a,b,c,d){var
f=c;if(this.log){if(c>0&&b>=0&&b+c<=a.length&&a[b+c-1]===10)c--;var
e=C(c);aj(dE(a),b,e,0,c);this.log(e.toUtf16());return f}p(d,aA,dp,aL)}read(a,b,c,d){p(d,aA,cM,aL)}seek(a,b,c){p(c,bK,a4,cX)}pos(){return-1}close(){this.log=undefined}check_stream_semantics(a){}}function
bl(a,b){var
c;if(b===undefined){b=aE.length;c=new
dr(b)}else if(aE[b])c=aE[b].chanid;else
c=new
dr(b);aE[b]={file:a,chanid:c};return b|0}function
fY(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;d.writeonly=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
e=d9(a),f=e.device.open(e.rest,d,c);return bl(f,undefined)}(function(){var
c=bm();function
a(a,b){return c?fS(a,b):new
eV(a,b)}bl(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);bl(a(1,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),1);bl(a(2,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),2)}());var
dk=" doesn't exist",cG="fd ";function
fC(a){var
b=aE[a];if(b===undefined)A(cG+a+dk);var
d=b.file,c=b.chanid,f=null,e={file:d,offset:d.pos(),fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(b0),refill:f};be.set(c,e);return c}function
dQ(a){var
c=aE[a];if(c===undefined)A(cG+a+dk);var
b=c.file,d=c.chanid,e=b.flags.buffered!==undefined?b.flags.buffered:1,f={file:b,offset:b.pos(),fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(b0),buffered:e};be.set(d,f);return d}function
fD(){var
a=0,d=be.all();for(var
c
of
d){var
b=b4(c);if(b.opened&&b.out)a=[0,c,a]}return a}function
fF(a,b,c,d){var
e=b4(a);if(!e.opened)A("Cannot output to a closed channel");b=b.subarray(c,c+d);if(e.buffer_curr+b.length>e.buffer.length){var
g=new
Uint8Array(e.buffer_curr+b.length);g.set(e.buffer);e.buffer=g}switch(e.buffered){case
0:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;ae(a);break;case
1:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)ae(a);break;case
2:var
f=b.lastIndexOf(10);if(f<0){e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)ae(a)}else{e.buffer.set(b.subarray(0,f+1),e.buffer_curr);e.buffer_curr+=f+1;ae(a);e.buffer.set(b.subarray(f+1),e.buffer_curr);e.buffer_curr+=b.length-f-1}break}return 0}function
fE(a,b,c,d){var
b=b_(b);return fF(a,b,c,d)}function
dR(a,b,c,d){return fE(a,as(b),c,d)}function
dS(a,b){var
c=_(String.fromCharCode(b));dR(a,c,0,1);return 0}var
c0=245;function
fx(a){return a===c0?1:0}var
a8=0x7c00,aM=128,bC=256,c3=0.0009765625,dV=function(){const
e=1/Number.EPSILON;function
o(a){return a+e-e}const
j=6.103515625e-5,m=65504,h=c3,i=h*j,l=h*e;function
p(a){const
b=+a;if(!Number.isFinite(b)||b===0)return b;const
e=b>0?1:-1,c=Math.abs(b);if(c<j)return e*o(c/i)*i;const
f=(1+l)*c,d=f-(f-c);if(d>m||Number.isNaN(d))return e*Number.POSITIVE_INFINITY;return e*d}var
a=512;const
b=new
Uint16Array(a),c=new
Uint8Array(a);for(let
a=0;a<bC;++a){const
e=a-a6;var
d=0x100;if(e<-24){b[a]=0x0000;b[a|d]=W;c[a]=24;c[a|d]=24}else if(e<-14){var
f=0x0400;b[a]=f>>-e-14;b[a|d]=f>>-e-14|W;c[a]=-e-1;c[a|d]=-e-1}else if(e<=15){b[a]=e+15<<10;b[a|d]=e+15<<10|W;c[a]=13;c[a|d]=13}else{var
g=0xfc00;if(e<aM){b[a]=a8;b[a|d]=g;c[a]=24;c[a|d]=24}else{b[a]=a8;b[a|d]=g;c[a]=13;c[a|d]=13}}}const
k=new
ArrayBuffer(4),n=new
Float32Array(k),q=new
Uint32Array(k);return function(a){n[0]=p(a);const
e=q[0],d=e>>23&0x1ff;return b[d]+((e&0x007fffff)>>c[d])}}(),$=new
DataView(new
ArrayBuffer(8));function
bc(a){$.setFloat32(0,a,true);return $.getUint32(0,true)|0}function
fl(a,b,c){return new
d(a,b,c)}var
dm=0xf,dj=0x7ff8,di=0x7ff0;function
bd(a){$.setFloat64(0,a,true);var
e=$.getUint32(0,true),c=$.getUint32(4,true),d=e&B,f=e>>>24|c<<8&B,b=c>>>16&N;if((b&dj)===di&&(f|d|b&dm)!==0)b|=8;return fl(d,f,b)}function
aR(a){return a.toArray()}var
a2="_bigarr02";function
dC(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom===a2)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<N)a.write(16,b.dims[d]);else{a.write(16,N);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=aR(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=aR(bd(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
13:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
0:for(var
d=0;d<b.data.length;d++){var
f=bc(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,bc(e[1]));a.write(32,bc(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=aR(bd(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=aR(bd(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}var
b$=function(){var
h=Math.pow,e=31,i=1023,f=h(2,-24),g=c3;return function(a){var
d=a>>>15,c=a>>>10&e,b=a&i;if(c===e)return b===0?d===0?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:Number.NaN;if(c===0)return b*(d===0?f:-f);var
j=h(2,c-15)*(d===0?1+b*g:-1-b*g);return j}}();function
dA(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
e1(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break;case
13:c=Uint16Array;break}if(!c)u("Bigarray.create: unsupported kind");var
d=new
c(b*dA(a));return d}function
bW(a){$.setUint32(0,a,true);return $.getFloat32(0,true)}function
aP(a){return new
d(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
bX(a){var
d=a.lo,c=a.mi,b=a.hi;if((b&dj)===di&&(c|d|b&dm)!==0)b|=8;$.setUint32(0,d|c<<24,true);$.setUint32(4,c>>>8|b<<16,true);return $.getFloat64(0,true)}function
bR(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)u("Bigarray.create: negative dimension");c=c*a[b]}return c}function
fk(a,b){return new
d(a&B,a>>>24&S|(b&N)<<8,b>>>16&N)}function
bY(a){return a.hi32()}function
bZ(a){return a.lo32()}var
e2=a2,a7=254;class
dv{constructor(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d;this.caml_custom=e2}offset(a){var
c=0;if(typeof
a==="number")a=[a];if(!Array.isArray(a))u("bigarray.js: invalid offset");if(this.dims.length!==a.length)u("Bigarray.get/set: bad number of dimensions");if(this.layout===0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])a9();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])a9();c=c*this.dims[b]+(a[b]-1)}return c}get(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return fk(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[a7,e,c];case
13:return b$(this.data[a]);default:return this.data[a]}}set(a,b){switch(this.kind){case
7:this.data[a*2+0]=bZ(b);this.data[a*2+1]=bY(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;case
13:this.data[a]=dV(b);break;default:this.data[a]=b;break}return 0}fill(a){switch(this.kind){case
7:var
c=bZ(a),e=bY(a);if(c===e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d===f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?d:f;break;case
13:this.data.fill(dV(a));break;default:this.data.fill(a);break}}compare(a,b){if(this.layout!==a.layout||this.kind!==a.kind){var
h=this.kind|this.layout<<8,i=a.kind|a.layout<<8;return i-h}if(this.dims.length!==a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!==a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!==e){if(!b)return Number.NaN;if(!Number.isNaN(d))return 1;if(!Number.isNaN(e))return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
13:for(var
c=0;c<this.data.length;c++){var
f=b$(this.data[c]),g=b$(a.data[c]);if(f<g)return-1;if(f>g)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0}}class
eW
extends
dv{offset(a){if(typeof
a!=="number")if(Array.isArray(a)&&a.length===1)a=a[0];else
u("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])a9();return a}get(a){return this.data[a]}set(a,b){this.data[a]=b;return 0}fill(a){this.data.fill(a);return 0}}function
dy(a,b,c,d){var
e=dA(a);if(bR(c)*e!==d.length)u("length doesn't match dims");if(b===0&&c.length===1&&e===1&&a!==13)return new
eW(a,b,c,d);return new
dv(a,b,c,d)}function
dz(a,b,c){var
k=a.read32s();if(k<0||k>16)au("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&S,q=r>>8&1,j=[];if(c===a2)for(var
d=0;d<k;d++){var
p=a.read16u();if(p===N){var
u=a.read32u(),v=a.read32u();if(u!==0)au("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=bR(j),h=e1(l,f),i=dy(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)au("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=aP(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=bX(aP(g));i.set(d,m)}break;case
13:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
0:for(var
d=0;d<f;d++){var
m=bW(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=bW(a.read32s()),n=bW(a.read32s());i.set(d,[a7,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=bX(aP(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=bX(aP(g));i.set(d,[a7,o,n])}break}b[0]=(4+k)*4;return dy(l,q,j,h)}function
dx(a,b,c){return a.compare(b,c)}function
dT(a,b){return Math.imul(a,b)}function
X(a,b){b=dT(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=dT(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
ff(a,b){if((b&a8)===a8&&(b&0x03ff)!==0)b=0x7c01;else if(b===W)b=0;return X(a,b)}var
dc=0x80000000;function
fg(a,b){var
c=bc(b),d=0x7f800000;if((c&d)===d&&(c&0x7fffff)!==0)c=0x7f800001;else if(c===(dc|0))c=0;a=X(a,c);return a}function
fe(a,b){var
f=bd(b),d=bZ(f),c=bY(f),e=0x7ff00000;if((c&e)===e&&(d|c&0xfffff)!==0){c=e;d=0x00000001}else if(c===(dc|0)&&d===0)c=0;a=X(a,d);a=X(a,c);return a}function
dB(a){var
c=bR(a.dims),d=0;switch(a.kind){case
2:case
3:case
12:if(c>bC)c=bC;var
e=0,b=0;for(b=0;b+4<=c;b+=4){e=a.data[b+0]&S|(a.data[b+1]&S)<<8|(a.data[b+2]&S)<<16|a.data[b+3]<<24;d=X(d,e)}e=0;switch(c&3){case
3:e=a.data[b+2]<<16;case
2:e|=a.data[b+1]<<8;case
1:e|=a.data[b+0];d=X(d,e)}break;case
4:case
5:if(c>aM)c=aM;var
e=0,b=0;for(b=0;b+2<=c;b+=2){e=a.data[b+0]&N|a.data[b+1]<<16;d=X(d,e)}if((c&1)!==0)d=X(d,a.data[b]);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=X(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=X(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=X(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=fg(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=fe(d,a.data[b]);break;case
13:if(c>aM)c=aM;for(var
b=0;b<c;b++)d=ff(d,a.data[b]);break}return d}function
fi(a,b){b[0]=4;return a.read32s()}function
fG(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:au("input_value: native integer value too large");break;default:au("input_value: ill-formed native integer")}}function
fv(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return aP(d)}function
fq(a,b,c){var
e=aR(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
fj(a,b,c){return a.compare(b)}function
fn(a){return a.lo32()^a.hi32()}var
dJ={_j:{deserialize:fv,serialize:fq,fixed_length:8,compare:fj,hash:fn},_i:{deserialize:fi,fixed_length:4},_n:{deserialize:fG,fixed_length:4},_bigarray:{deserialize:function(a,b){return dz(a,b,"_bigarray")},serialize:dC,compare:dx,hash:dB},_bigarr02:{deserialize:function(a,b){return dz(a,b,a2)},serialize:dC,compare:dx,hash:dB}};function
bT(a){return dJ[a.caml_custom]&&dJ[a.caml_custom].compare}function
dG(a,b,c,d){var
f=bT(b);if(f){var
e=c>0?f(b,a,d):f(a,b,d);if(d&&Number.isNaN(e))return c;if(Number.isNaN(+e))return+e;if((e|0)!==0)return e|0}return c}var
cZ=255,a1=252,bB=1255;function
dH(a){if(typeof
a==="number")return ad;else if(b1(a))return a1;else if(b2(a))return 1252;else if(Array.isArray(a)&&a[0]===a[0]>>>0&&a[0]<=cZ){var
c=a[0]|0;return c===a7?0:c}else{var
b=12520;if(a
instanceof
String)return b;else if(typeof
a==="string")return b;else if(a
instanceof
Number)return ad;else if(a?.caml_custom)return bB;else if(a?.compare)return 1256;else if(typeof
a==="function")return 1247;else if(typeof
a==="symbol")return 1251}return 1001}function
fw(a,b){if(a<b)return-1;if(a===b)return 0;return 1}function
fX(a,b){return a<b?-1:a>b?1:0}function
e5(a,b){a.t&6&&ba(a);b.t&6&&ba(b);return a.c<b.c?-1:a.c>b.c?1:0}function
e9(a,b,c){var
f=[];for(;;){if(!(c&&a===b)){var
e=dH(a),k=250;if(e===k){a=a[1];continue}var
g=dH(b);if(g===k){b=b[1];continue}if(e!==g){if(e===ad){if(g===bB)return dG(a,b,-1,c);return-1}if(g===ad){if(e===bB)return dG(b,a,1,c);return 1}return e<g?-1:1}var
i="compare: functional value";switch(e){case
247:u(i);break;case
248:var
d=fw(a[2],b[2])|0;if(d!==0)return d;break;case
249:u(i);break;case
250:u("equal: got Forward_tag, should not happen");break;case
251:u("equal: abstract value");break;case
252:if(a!==b){var
d=e5(a,b)|0;if(d!==0)return d}break;case
253:u("equal: got Double_tag, should not happen");break;case
254:u("equal: got Double_array_tag, should not happen");break;case
255:u("equal: got Custom_tag, should not happen");break;case
1247:u(i);break;case
1255:var
j=bT(a);if(j!==bT(b))return a.caml_custom<b.caml_custom?-1:1;if(!j)u("compare: abstract value");var
d=j(a,b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1256:var
d=a.compare(b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!==b){if(!c)return Number.NaN;if(!Number.isNaN(a))return 1;if(!Number.isNaN(b))return-1}break;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!==b)return c?1:Number.NaN;break;case
1251:if(a!==b)return c?1:Number.NaN;break;case
1252:var
a=aD(a),b=aD(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;default:if(fx(e)){u("compare: continuation value");break}if(a.length!==b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1);break}}if(f.length===0)return 0;var
h=f.pop();b=f.pop();a=f.pop();if(h+1<a.length)f.push(a,b,h+1);a=a[h];b=b[h]}}function
aS(a,b){return+(e9(a,b,false)!==0)}function
fH(a){return typeof
a==="number"?a:a.slice()}function
bf(a){if(Array.isArray(a)&&a[0]===a[0]>>>0)return a[0];else if(b1(a))return a1;else if(b2(a))return a1;else if(a
instanceof
Function||typeof
a==="function")return 247;else if(a?.caml_custom)return cZ;else
return ad}function
dL(a){return a}var
bP="Effect.Unhandled";function
dP(a){var
b=al(bP);if(b)b=[0,b,a];else
b=[o,_(bP),av(0)];return b}function
fJ(a,b){if(j.e===0){var
g=dP(a);throw g}var
e=j.h[3],c=j;c.k=b;var
d=[c0,c,c],f=b6();return O()?dL(e)(a,d,c,f):R(e,[a,d,c,f])}function
T(){if(!j.x)return function(a){throw a};var
a=j.x.h;j.x=j.x.t;return a}function
aT(a){j.x={h:a,t:j.x}}var
d7=undefined;function
e3(a){var
d={},c=-1;if(a)for(var
b=1;b<a.length;b++){var
e=a[b][2];c=Math.max(c,e);d[b3(a[b][1])]=e}d.next_idx=c+1;return d}function
b(a,b,c){if(c){var
d=c;if(d7)a=aC(d7,[d]);else if(z.symbols){if(!z.symidx)z.symidx=e3(z.symbols);var
e=z.symidx[d];if(e>=0)a=e;else{var
a=z.symidx.next_idx++;z.symidx[d]=a}}}z[a+1]=b;if(c)z[c]=b}function
b8(a,b){dU[aD(a)]=b;return 0}var
dg="Effect.Continuation_already_resumed";function
b9(a,b,c){if(!a)dW(al(dg));if(b===0){b=a;while(b.e!==0)b=b.e}j.k=c;b.e=j;j=a;return a.k}function
fL(a,b,c,d){if(j.e===0){var
h=dP(a),i=dI(b);b9(i,c,d);throw h}var
f=j.h[3],e=j;e.k=d;c.e=e;b[2]=e;var
g=b6();return O()?dL(f)(a,b,e,g):R(f,[a,b,e,g])}function
fN(){u(bE)}function
L(a,b){if(b>>>0>=E(a))fN();return bj(a,b)}function
P(a){a.t&6&&ba(a);return _(a.c)}function
fQ(){return 0x7fffffff/4|0}function
fR(a){return b0}function
fy(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}var
cY="_";function
fc(a){var
b=f;if(a[0]===0){b+=a[1][1];if(a.length===3&&a[2][0]===0&&fy(a[1]))var
g=a[2],h=1;else
var
h=2,g=a;b+="(";for(var
e=h;e<g.length;e++){if(e>h)b+=bG;var
c=g[e];if(typeof
c==="number")b+=c.toString();else{var
d='"';if(c
instanceof
ar)b+=d+c.toString()+d;else if(typeof
c==="string")b+=d+c.toString()+d;else
b+=cY}}b+=")"}else if(a[0]===o)b+=a[1];return b}var
bI="Fatal error: exception ",c8="Pervasives.do_at_exit",cJ="Printexc.handle_uncaught_exception";function
dK(a){if(Array.isArray(a)&&(a[0]===0||a[0]===o)){var
c=al(cJ);if(c)aC(c,[a,false]);else{var
d=fc(a),b=al(c8);if(b)aC(b,[0]);console.error(bI+d);if(a.js_error)throw a.js_error}}else
throw a}function
fM(){var
d=c.process;if(d?.on)d.on("uncaughtException",function(a,b){dK(a);d.exit(2)});else if(c.addEventListener)c.addEventListener("error",function(a){if(a.error)dK(a.error)})}fM();function
ah(a,b){return O()?a(b):R(a,[b],1)}function
G(a,b,c){return O()?(a.l>=0?a.l:a.l=a.length)===2?a(b,c):ak(a,[b,c]):R(a,[b,c],0)}function
q(a,b,c){return O()?a(b,c):R(a,[b,c],0)}function
a0(a,b,c,d){return O()?(a.l>=0?a.l:a.l=a.length)===3?a(b,c,d):ak(a,[b,c,d]):R(a,[b,c,d],0)}function
e(a,b,c,d){return O()?a(b,c,d):R(a,[b,c,d],0)}function
h(a,b,c,d,e){return O()?a(b,c,d,e):R(a,[b,c,d,e],0)}function
J(a,b,c,d,e,f){return O()?a(b,c,d,e,f):R(a,[b,c,d,e,f],0)}function
bA(a,b,c,d,e,f,g){return O()?(a.l>=0?a.l:a.l=a.length)===6?a(b,c,d,e,f,g):ak(a,[b,c,d,e,f,g]):R(a,[b,c,d,e,f,g],0)}function
cC(a,b,c,d,e,f,g){return O()?a(b,c,d,e,f,g):R(a,[b,c,d,e,f,g],0)}function
eT(a,b,c,d,e,f,g,h,i){return O()?(a.l>=0?a.l:a.l=a.length)===8?a(b,c,d,e,f,g,h,i):ak(a,[b,c,d,e,f,g,h,i]):R(a,[b,c,d,e,f,g,h,i],0)}fd();var
db="Undefined_recursive_module",cj=[o,db,-12];b(11,cj,db);var
cS="Assert_failure",s=[o,cS,-11];b(10,s,cS);var
c5="Sys_blocked_io";b(9,[o,c5,-10],c5);var
cP="Stack_overflow",ch=[o,cP,-9];b(8,ch,cP);var
dq="Match_failure",cg=[o,dq,-8];b(7,cg,dq);var
dh="Not_found";b(6,[o,dh,-7],dh);var
df="Division_by_zero";b(5,[o,df,-6],df);var
cN="End_of_file";b(4,[o,cN,-5],cN);var
cQ="Invalid_argument",ce=[o,cQ,-4];b(3,ce,cQ);var
cf=[o,bD,-3];b(2,cf,bD);var
da="Sys_error",ci=[o,da,-2];b(1,ci,da);var
cK="Out_of_memory",bn=[o,cK,-1];b(0,bn,cK);function
n(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,n(a[1])];case
1:return[1,n(a[1])];case
2:return[2,n(a[1])];case
3:return[3,n(a[1])];case
4:return[4,n(a[1])];case
5:return[5,n(a[1])];case
6:return[6,n(a[1])];case
7:return[7,n(a[1])];case
8:var
c=a[1];return[8,c,n(a[2])];case
9:var
b=a[1];return[9,b,b,n(a[3])];case
10:return[10,n(a[1])];case
11:return[11,n(a[1])];case
12:return[12,n(a[1])];case
13:return[13,n(a[1])];default:return[14,n(a[1])]}}function
D(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,D(a[1],b)];case
1:return[1,D(a[1],b)];case
2:return[2,D(a[1],b)];case
3:return[3,D(a[1],b)];case
4:return[4,D(a[1],b)];case
5:return[5,D(a[1],b)];case
6:return[6,D(a[1],b)];case
7:return[7,D(a[1],b)];case
8:var
c=a[1];return[8,c,D(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,D(a[3],b)];case
10:return[10,D(a[1],b)];case
11:return[11,D(a[1],b)];case
12:return[12,D(a[1],b)];case
13:return[13,D(a[1],b)];default:return[14,D(a[1],b)]}}function
l(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,l(a[1],b)];case
1:return[1,l(a[1],b)];case
2:var
c=a[1];return[2,c,l(a[2],b)];case
3:var
d=a[1];return[3,d,l(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,l(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,l(a[4],b)];case
6:var
k=a[3],m=a[2],n=a[1];return[6,n,m,k,l(a[4],b)];case
7:var
o=a[3],p=a[2],q=a[1];return[7,q,p,o,l(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,l(a[4],b)];case
9:var
u=a[1];return[9,u,l(a[2],b)];case
10:return[10,l(a[1],b)];case
11:var
v=a[1];return[11,v,l(a[2],b)];case
12:var
w=a[1];return[12,w,l(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,l(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,l(a[3],b)];case
15:return[15,l(a[1],b)];case
16:return[16,l(a[1],b)];case
17:var
B=a[1];return[17,B,l(a[2],b)];case
18:var
C=a[1];return[18,C,l(a[2],b)];case
19:return[19,l(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,l(a[3],b)];case
21:var
F=a[1];return[21,F,l(a[2],b)];case
22:return[22,l(a[1],b)];case
23:var
G=a[1];return[23,G,l(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,l(a[3],b)]}}function
aw(a){throw g([0,ce,a],1)}function
aU(a){return 0<=a?a:-a|0}fC(0);dQ(1);var
U=dQ(2);function
aG(a,b){dR(a,b,0,E(b))}function
ck(a){aG(U,a);dS(U,10);return ae(U)}function
bo(a,b){var
c=fD(0);for(;;){if(!c)return b(0);var
d=c[2],f=c[1];try{ae(f);c=d}catch(f){var
e=d2(f);if(e[1]!==ci){var
h=T();return h(g(e,0))}c=d}}}b8(c8,bo);var
aH=(4*fQ(0)|0)-1|0;fR(0);function
an(a,b){var
c=C(a);fb(c,0,a,b);return c}function
cl(a,b,c){a:{if(0<=b&&0<=c&&(Y(a)-c|0)>=b){var
d=C(c);aj(a,b,d,0,c);var
e=d;break a}var
e=aw("String.sub / Bytes.sub")}return P(e)}function
cm(a,b,c,d,e){if(0<=e&&0<=b&&(Y(a)-e|0)>=b&&0<=d&&(Y(c)-e|0)>=d){aj(a,b,c,d,e);return}return aw("Bytes.blit")}function
Z(a,b,c,d,e){if(0<=e&&0<=b&&(E(a)-e|0)>=b&&0<=d&&(Y(c)-e|0)>=d){a_(a,b,c,d,e);return}return aw("String.blit / Bytes.blit_string")}function
cn(a,b){var
e=a[2],c=a[1][2];for(;;){if(c>=(e+b|0))break;c=2*c|0}if(aH<c){if((e+b|0)>aH)throw g([0,cf,"Buffer.add: cannot grow buffer"],1);var
d=aH}else
var
d=c;var
f=C(d);cm(a[1][1],0,f,0,a[2]);a[1]=[0,f,d]}function
aI(a,b){var
c=E(b),i=c<0,g=i||(E(b)-c|0)<0;if(g)aw("Buffer.add_substring");var
d=a[2],e=a[1],f=d+c|0,h=e[1];if(e[2]<f){cn(a,c);Z(b,0,a[1][1],a[2],c)}else
a_(b,0,h,d,c);a[2]=f}function
bq(a){return 5===a[2]?12:-6}function
co(a){return[0,0,C(a)]}function
cp(a,b){var
c=Y(a[2]),d=a[1]+b|0;if(c<d){var
e=c*2|0,g=d<=e?e:d,f=C(g);cm(a[2],0,f,0,c);a[2]=f}}function
ax(a,b){cp(a,1);at(a[2],a[1],b);a[1]=a[1]+1|0}function
x(a,b){var
c=E(b);cp(a,c);Z(b,0,a[2],a[1],c);a[1]=a[1]+c|0}function
cq(a){return cl(a[2],0,a[1])}function
cr(a){if(typeof
a==="number")switch(a){case
0:return"@]";case
1:return"@}";case
2:return"@?";case
3:return"@\n";case
4:return"@.";case
5:return"@@";default:return"@%"}return 2===a[0]?"@"+P(an(1,a[1])):a[1]}var
cT="%li",dn="%ni",c6="%Li",cD="%i";function
br(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
d=c[1];x(a,"%c");c=d;break;case
1:var
e=c[1];x(a,"%s");c=e;break;case
2:var
f=c[1];x(a,cD);c=f;break;case
3:var
g=c[1];x(a,cT);c=g;break;case
4:var
h=c[1];x(a,dn);c=h;break;case
5:var
i=c[1];x(a,c6);c=i;break;case
6:var
j=c[1];x(a,"%f");c=j;break;case
7:var
k=c[1];x(a,"%B");c=k;break;case
8:var
l=c[2],m=c[1];x(a,"%{");br(a,m);x(a,"%}");c=l;break;case
9:var
n=c[3],o=c[1];x(a,"%(");br(a,o);x(a,"%)");c=n;break;case
10:var
p=c[1];x(a,"%a");c=p;break;case
11:var
q=c[1];x(a,"%t");c=q;break;case
12:var
r=c[1];x(a,"%?");c=r;break;case
13:var
s=c[1];x(a,"%r");c=s;break;default:var
t=c[1];x(a,"%_r");c=t}}}function
t(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,t(a[1])];case
1:return[1,t(a[1])];case
2:return[2,t(a[1])];case
3:return[3,t(a[1])];case
4:return[4,t(a[1])];case
5:return[5,t(a[1])];case
6:return[6,t(a[1])];case
7:return[7,t(a[1])];case
8:var
b=a[1];return[8,b,t(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,t(a[3])];case
10:return[10,t(a[1])];case
11:return[11,t(a[1])];case
12:return[12,t(a[1])];case
13:return[13,t(a[1])];default:return[14,t(a[1])]}}function
y(a){if(typeof
a==="number")return[0,,function(a){},,function(a){}];switch(a[0]){case
0:var
b=y(a[1]),r=b[2];return[0,,function(a){r()},,b[4]];case
1:var
c=y(a[1]),s=c[2];return[0,,function(a){s()},,c[4]];case
2:var
d=y(a[1]),u=d[2];return[0,,function(a){u()},,d[4]];case
3:var
e=y(a[1]),w=e[2];return[0,,function(a){w()},,e[4]];case
4:var
f=y(a[1]),x=f[2];return[0,,function(a){x()},,f[4]];case
5:var
g=y(a[1]),z=g[2];return[0,,function(a){z()},,g[4]];case
6:var
h=y(a[1]),A=h[2];return[0,,function(a){A()},,h[4]];case
7:var
i=y(a[1]),B=i[2];return[0,,function(a){B()},,i[4]];case
8:var
j=y(a[2]),C=j[2];return[0,,function(a){C()},,j[4]];case
9:var
D=a[2],E=a[1],k=y(a[3]),F=k[4],G=k[2],l=y(v(t(E),D)),H=l[4],I=l[2];return[0,,function(a){I();G()},,function(a){H();F()}];case
10:var
m=y(a[1]),J=m[2];return[0,,function(a){J()},,m[4]];case
11:var
n=y(a[1]),K=n[2];return[0,,function(a){K()},,n[4]];case
12:var
o=y(a[1]),L=o[2];return[0,,function(a){L()},,o[4]];case
13:var
p=y(a[1]),M=p[4],N=p[2];return[0,,function(a){N()},,function(a){M()}];default:var
q=y(a[1]),O=q[4],P=q[2];return[0,,function(a){P()},,function(a){O()}]}}var
a="camlinternalFormat.ml",d$=[0,a,850,23],ea=[0,a,837,26],eb=[0,a,847,28],ec=[0,a,815,21],ed=[0,a,819,21],ee=[0,a,823,19],ef=[0,a,827,22],eg=[0,a,832,30],eh=[0,a,851,23],ei=[0,a,836,26],ej=[0,a,846,28],ek=[0,a,814,21],el=[0,a,818,21],em=[0,a,822,19],en=[0,a,826,22],eo=[0,a,831,30];function
v(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:var
d=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,v(d,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
1:var
e=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,v(e,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
2:var
f=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,v(f,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
3:var
h=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,v(h,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
4:var
i=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,v(i,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
5:var
j=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,v(j,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
6:var
k=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,v(k,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
7:var
l=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,v(l,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
8:var
m=a[2],n=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
o=b[1],p=v(m,b[2]);return[8,v(n,o),p];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw g([0,s,ei],1);case
9:var
q=a[3],r=a[2],u=a[1];if(typeof
b!=="number")switch(b[0]){case
9:var
w=b[3],x=b[2],z=b[1],c=y(v(t(r),z)),A=c[4];c[2].call(null);A();return[9,u,x,v(q,w)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f}throw g([0,s,ej],1);case
10:var
B=a[1];if(typeof
b!=="number"&&10===b[0])return[10,v(B,b[1])];throw g([0,s,ek],1);case
11:var
C=a[1];if(typeof
b!=="number")switch(b[0]){case
11:return[11,v(C,b[1])];case
10:break a}throw g([0,s,el],1);case
12:var
D=a[1];if(typeof
b!=="number")switch(b[0]){case
12:return[12,v(D,b[1])];case
10:break a;case
11:break b}throw g([0,s,em],1);case
13:var
E=a[1];if(typeof
b!=="number")switch(b[0]){case
13:return[13,v(E,b[1])];case
10:break a;case
11:break b;case
12:break c}throw g([0,s,en],1);default:var
F=a[1];if(typeof
b!=="number")switch(b[0]){case
14:return[14,v(F,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d}throw g([0,s,eo],1)}throw g([0,s,eh],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw g([0,s,d$],1)}}throw g([0,s,eb],1)}throw g([0,s,ea],1)}throw g([0,s,eg],1)}throw g([0,s,ef],1)}throw g([0,s,ee],1)}throw g([0,s,ed],1)}throw g([0,s,ec],1)}var
w=[o,"CamlinternalFormat.Type_mismatch",av(0)];function
d_(a){return a?"true":"false"}function
aV(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw g(w,1)}function
aJ(a,b,c){var
d=aV(a,c);if(typeof
b!=="number")return[0,d[1],[0,b[1]],d[2]];if(!b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw g(w,1)}function
k(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){var
v=k(a[1],b[1]);return[0,[0,v[1]],v[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){var
x=k(a[1],b[1]);return[0,[1,x[1]],x[2]]}break;case
2:var
af=a[2],y=aV(a[1],b),e=y[2],ag=y[1];if(typeof
e!=="number"&&1===e[0]){var
z=k(af,e[1]);return[0,[2,ag,z[1]],z[2]]}throw g(w,1);case
3:var
ah=a[2],A=aV(a[1],b),f=A[2],ai=A[1];if(typeof
f!=="number"&&1===f[0]){var
B=k(ah,f[1]);return[0,[3,ai,B[1]],B[2]]}throw g(w,1);case
4:var
aj=a[4],ak=a[1],h=aJ(a[2],a[3],b),i=h[3],al=h[1];if(typeof
i!=="number"&&2===i[0]){var
am=h[2],C=k(aj,i[1]);return[0,[4,ak,al,am,C[1]],C[2]]}throw g(w,1);case
5:var
an=a[4],ao=a[1],j=aJ(a[2],a[3],b),l=j[3],ap=j[1];if(typeof
l!=="number"&&3===l[0]){var
aq=j[2],D=k(an,l[1]);return[0,[5,ao,ap,aq,D[1]],D[2]]}throw g(w,1);case
6:var
ar=a[4],as=a[1],m=aJ(a[2],a[3],b),o=m[3],at=m[1];if(typeof
o!=="number"&&4===o[0]){var
au=m[2],E=k(ar,o[1]);return[0,[6,as,at,au,E[1]],E[2]]}throw g(w,1);case
7:var
av=a[4],aw=a[1],p=aJ(a[2],a[3],b),q=p[3],ax=p[1];if(typeof
q!=="number"&&5===q[0]){var
ay=p[2],G=k(av,q[1]);return[0,[7,aw,ax,ay,G[1]],G[2]]}throw g(w,1);case
8:var
az=a[4],aA=a[1],r=aJ(a[2],a[3],b),s=r[3],aB=r[1];if(typeof
s!=="number"&&6===s[0]){var
aC=r[2],H=k(az,s[1]);return[0,[8,aA,aB,aC,H[1]],H[2]]}throw g(w,1);case
9:var
aD=a[2],I=aV(a[1],b),t=I[2],aE=I[1];if(typeof
t!=="number"&&7===t[0]){var
J=k(aD,t[1]);return[0,[9,aE,J[1]],J[2]]}throw g(w,1);case
10:var
K=k(a[1],b);return[0,[10,K[1]],K[2]];case
11:var
aF=a[1],L=k(a[2],b);return[0,[11,aF,L[1]],L[2]];case
12:var
aG=a[1],M=k(a[2],b);return[0,[12,aG,M[1]],M[2]];case
13:if(typeof
b!=="number"&&8===b[0]){var
N=b[1],aH=b[2],aI=a[3],aK=a[1];if(aS([0,a[2]],[0,N]))throw g(w,1);var
O=k(aI,aH);return[0,[13,aK,N,O[1]],O[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){var
P=b[1],aL=b[3],aM=a[3],aN=a[2],aO=a[1],aP=[0,n(P)];if(aS([0,n(aN)],aP))throw g(w,1);var
Q=k(aM,n(aL));return[0,[14,aO,P,Q[1]],Q[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){var
R=k(a[1],b[1]);return[0,[15,R[1]],R[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){var
S=k(a[1],b[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aQ=a[1],T=k(a[2],b);return[0,[17,aQ,T[1]],T[2]];case
18:var
U=a[2],u=a[1];if(0===u[0]){var
Y=u[1],aW=Y[2],Z=k(Y[1],b),aX=Z[1],_=k(U,Z[2]);return[0,[18,[0,[0,aX,aW]],_[1]],_[2]]}var
$=u[1],aY=$[2],aa=k($[1],b),aZ=aa[1],ab=k(U,aa[2]);return[0,[18,[1,[0,aZ,aY]],ab[1]],ab[2]];case
19:if(typeof
b!=="number"&&13===b[0]){var
V=k(a[1],b[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){var
aR=a[2],aT=a[1],W=k(a[3],b[1]);return[0,[20,aT,aR,W[1]],W[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){var
aU=a[1],X=k(a[2],b[1]);return[0,[21,aU,X[1]],X[2]]}break;case
23:var
d=a[2],c=a[1];if(typeof
c!=="number")switch(c[0]){case
8:return bs([8,c[1],c[2]],d,b);case
9:var
a0=c[1],ad=F(c[2],d,b),ae=ad[2];return[0,[23,[9,a0,ad[1]],ae[1]],ae[2]];default:return bs(c,d,b)}if(2!==c)return bs(c,d,b);if(typeof
b!=="number"&&14===b[0]){var
ac=k(d,b[1]);return[0,[23,2,ac[1]],ac[2]]}throw g(w,1)}throw g(w,1)}function
bs(a,b,c){var
d=k(b,c);return[0,[23,a,d[1]],d[2]]}function
F(a,b,c){if(typeof
a==="number")return[0,0,k(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=F(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
h=F(a[1],b,c[1]);return[0,[1,h[1]],h[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
i=F(a[1],b,c[1]);return[0,[2,i[1]],i[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
j=F(a[1],b,c[1]);return[0,[3,j[1]],j[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
l=F(a[1],b,c[1]);return[0,[4,l[1]],l[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
m=F(a[1],b,c[1]);return[0,[5,m[1]],m[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
o=F(a[1],b,c[1]);return[0,[6,o[1]],o[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
p=F(a[1],b,c[1]);return[0,[7,p[1]],p[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
q=c[1],C=c[2],D=a[2];if(aS([0,a[1]],[0,q]))throw g(w,1);var
r=F(D,b,C);return[0,[8,q,r[1]],r[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],E=c[3],G=a[3],H=a[2],I=a[1],J=[0,n(e)];if(aS([0,n(I)],J))throw g(w,1);var
K=[0,n(d)];if(aS([0,n(H)],K))throw g(w,1);var
s=y(v(t(e),d)),L=s[4];s[2].call(null);L();var
u=F(n(G),b,E),M=u[2];return[0,[9,e,d,t(u[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
x=F(a[1],b,c[1]);return[0,[10,x[1]],x[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
z=F(a[1],b,c[1]);return[0,[11,z[1]],z[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
A=F(a[1],b,c[1]);return[0,[13,A[1]],A[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
B=F(a[1],b,c[1]);return[0,[14,B[1]],B[2]]}break}throw g(w,1)}var
cR=120;function
H(a,b,c){var
d=E(c),g=0<=b?a:0,f=aU(b);if(f<=d)return c;var
h=2===g?48:32,e=an(f,h);switch(g){case
0:Z(c,0,e,0,d);break;case
1:Z(c,0,e,f-d|0,d);break;default:a:if(0<d){if(43!==L(c,0)&&45!==L(c,0)&&32!==L(c,0))break a;at(e,0,L(c,0));Z(c,1,e,(f-d|0)+1|0,d-1|0);break}a:if(1<d&&48===L(c,0)){if(cR!==L(c,1)&&88!==L(c,1))break a;at(e,1,L(c,1));Z(c,2,e,(f-d|0)+2|0,d-2|0);break}Z(c,0,e,f-d|0,d)}return P(e)}var
cL=-97;function
ay(a,b){var
d=aU(a),c=E(b),e=L(b,0);a:{b:{if(58>e){if(32!==e){if(43>e)break a;switch(e-43|0){case
5:if(c>=(d+2|0))break b;if(1>=c)break b;if(cR!==L(b,1)&&88!==L(b,1))break b;var
g=an(d+2|0,48);at(g,1,L(b,1));Z(b,2,g,(d-c|0)+4|0,c-2|0);return P(g);case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(c>=(d+1|0))break a;var
f=an(d+1|0,48);at(f,0,e);Z(b,1,f,(d-c|0)+2|0,c-1|0);return P(f)}if(71<=e){if(5<e+cL>>>0)break a}else if(65>e)break a}if(c<d){var
h=an(d,48);Z(b,0,h,d-c|0,c);return P(h)}}return b}var
c_=100;function
ep(a){var
e=as(a),o=Y(e)-1|0,n=0;if(o<0)var
m=n;else{var
v=n,i=0;for(;;){var
g=bS(e,i);a:{b:{c:{if(32<=g){var
k=g-34|0;if(58<k>>>0){if(93<=k)break c}else if(56<k-1>>>0)break b;var
l=1;break a}if(11<=g){if(13===g)break b}else if(8<=g)break b}var
l=4;break a}var
l=2}var
q=v+l|0,H=i+1|0;if(o===i){var
m=q;break}v=q;i=H}}if(m===Y(e))var
j=e;else{var
b=C(m),p=Y(e)-1|0;if(p<0)var
j=b;else{var
c=0,h=0;for(;;){var
d=bS(e,h);a:{b:{c:{if(35<=d){if(92!==d){if(a6<=d)break b;break c}}else{if(32>d){if(14<=d)break b;switch(d){case
8:r(b,c,92);var
w=c+1|0;r(b,w,98);var
f=w;break a;case
9:r(b,c,92);var
x=c+1|0;r(b,x,116);var
f=x;break a;case
10:r(b,c,92);var
y=c+1|0;r(b,y,110);var
f=y;break a;case
13:r(b,c,92);var
z=c+1|0;r(b,z,114);var
f=z;break a;default:break b}}if(34>d)break c}r(b,c,92);var
F=c+1|0;r(b,F,d);var
f=F;break a}r(b,c,d);var
f=c;break a}r(b,c,92);var
A=c+1|0;r(b,A,48+(d/c_|0)|0);var
B=A+1|0;r(b,B,48+((d/10|0)%10|0)|0);var
D=B+1|0;r(b,D,48+(d%10|0)|0);var
f=D}var
I=f+1|0,G=h+1|0;if(p===h){var
j=b;break}c=I;h=G}}}var
s=e===j?a:P(j),t=E(s),u=an(t+2|0,34);a_(s,0,u,1,t);return P(u)}var
c$=103,eq=[0,c$];function
cs(a,b){var
g=aU(b),e=eq[1];switch(a[2]){case
0:var
c=102;break;case
1:var
c=101;break;case
2:var
c=69;break;case
3:var
c=c$;break;case
4:var
c=71;break;case
6:var
c=104;break;case
7:var
c=72;break;case
8:var
c=70;break;default:var
c=e}var
d=co(16);ax(d,37);switch(a[1]){case
1:ax(d,43);break;case
2:ax(d,32);break}if(8<=a[2])ax(d,35);ax(d,46);x(d,f+g);ax(d,c);return cq(d)}function
aW(a,b){if(13>a)return b;var
k=E(b)-1|0,q=-48,j=0;if(k<0)var
i=j;else{var
h=j,d=0;for(;;){var
o=9<bj(b,d)+q>>>0?h:h+1|0,t=d+1|0;if(k===d){var
i=o;break}h=o;d=t}}var
l=C(E(b)+((i-1|0)/3|0)|0),m=[0,0];function
f(a){at(l,m[1],a);m[1]++}var
n=E(b)-1|0,r=((i-1|0)%3|0)+1|0;if(n>=0){var
e=r,c=0;for(;;){var
g=bj(b,c);if(9<g+q>>>0){f(g);var
p=e}else{var
u=0===e?(f(95),3):e;f(g);var
p=u-1|0}var
s=c+1|0;if(n===c)break;e=p;c=s}}return P(l)}var
c7="%u";function
er(a,b){switch(a){case
1:var
c="%+d";break;case
2:var
c="% d";break;case
4:var
c="%+i";break;case
5:var
c="% i";break;case
6:var
c="%x";break;case
7:var
c="%#x";break;case
8:var
c="%X";break;case
9:var
c="%#X";break;case
10:var
c="%o";break;case
11:var
c="%#o";break;case
0:case
13:var
c=bH;break;case
3:case
14:var
c=cD;break;default:var
c=c7}return aW(a,bb(c,b))}function
es(a,b){switch(a){case
1:var
c="%+ld";break;case
2:var
c="% ld";break;case
4:var
c="%+li";break;case
5:var
c="% li";break;case
6:var
c="%lx";break;case
7:var
c="%#lx";break;case
8:var
c="%lX";break;case
9:var
c="%#lX";break;case
10:var
c="%lo";break;case
11:var
c="%#lo";break;case
0:case
13:var
c="%ld";break;case
3:case
14:var
c=cT;break;default:var
c="%lu"}return aW(a,bb(c,b))}function
et(a,b){switch(a){case
1:var
c="%+nd";break;case
2:var
c="% nd";break;case
4:var
c="%+ni";break;case
5:var
c="% ni";break;case
6:var
c="%nx";break;case
7:var
c="%#nx";break;case
8:var
c="%nX";break;case
9:var
c="%#nX";break;case
10:var
c="%no";break;case
11:var
c="%#no";break;case
0:case
13:var
c="%nd";break;case
3:case
14:var
c=dn;break;default:var
c="%nu"}return aW(a,bb(c,b))}function
eu(a,b){switch(a){case
1:var
c="%+Ld";break;case
2:var
c="% Ld";break;case
4:var
c="%+Li";break;case
5:var
c="% Li";break;case
6:var
c="%Lx";break;case
7:var
c="%#Lx";break;case
8:var
c="%LX";break;case
9:var
c="%#LX";break;case
10:var
c="%Lo";break;case
11:var
c="%#Lo";break;case
0:case
13:var
c="%Ld";break;case
3:case
14:var
c=c6;break;default:var
c="%Lu"}return aW(a,fm(c,b))}function
aa(k,b,c){function
l(a){switch(k[1]){case
0:var
d=45;break;case
1:var
d=43;break;default:var
d=32}return fh(c,b,d)}function
p(a){var
b=e8(c);return 3===b?c<0.?"neg_infinity":cH:4<=b?bO:a}switch(k[2]){case
5:var
e=bV(cs(k,b),c),d=0,t=E(e);for(;;){a:{if(d!==t){var
m=L(e,d)-46|0;b:{if(23<m>>>0){if(55!==m)break b}else if(21>=m-1>>>0)break b;var
o=1;break a}d=d+1|0;continue}var
o=0}var
u=o?e:e+aq;return p(u)}case
6:return l();case
7:var
i=as(l()),f=Y(i);if(0===f)var
j=i;else{var
g=C(f),n=f-1|0;if(n<0)var
j=g;else{var
a=0;for(;;){var
h=bS(i,a),q=25<h+cL>>>0?h:h-32|0;r(g,a,q);var
s=a+1|0;if(n===a){var
j=g;break}a=s}}}return P(j);case
8:return p(l());default:return bV(cs(k,b),c)}}var
ev=[0,a,1558,4],ew=[0,a,1626,39];function
i(a,b,c,d){a:{b:{c:{d:{e:{f:{g:{h:{i:{j:{k:{var
j=a,f=b,e=c;l:for(;;){if(typeof
e==="number")return q(j,f,d);switch(e[0]){case
0:break a;case
1:break b;case
2:break c;case
3:return d(bu(j,f,e[2],e[1],ep));case
4:return d(aX(j,f,e[4],e[2],e[3],er,e[1]));case
5:return d(aX(j,f,e[4],e[2],e[3],es,e[1]));case
6:return d(aX(j,f,e[4],e[2],e[3],et,e[1]));case
7:return d(aX(j,f,e[4],e[2],e[3],eu,e[1]));case
8:break d;case
9:return d(bu(j,f,e[2],e[1],d_));case
10:f=[7,f];e=e[1];break;case
11:f=[2,f,e[1]];e=e[2];break;case
12:f=[3,f,e[1]];e=e[2];break;case
13:break e;case
14:break f;case
15:break g;case
16:break h;case
17:f=[0,f,e[1]];e=e[2];break;case
18:var
x=e[1];if(0===x[0]){let
c=f,d=j,g=e[2];j=function(a,b){return h(i,d,[1,c,[0,a]],g,b)};f=0;e=x[1][1]}else{let
c=f,d=j,g=e[2];j=function(a,b){return h(i,d,[1,c,[1,a]],g,b)};f=0;e=x[1][1]}break;case
19:var
ad=T();return ad(g([0,s,ev],1));case
20:break i;case
21:break j;case
22:break k;case
23:var
y=e[2],v=e[1];if(typeof
v!=="number")return 9===v[0]?J(I,j,f,v[2],y,d):h(bt,j,f,y,d);if(2!==v)return h(bt,j,f,y,d);var
ac=T();return ac(g([0,s,ew],1));default:break l}}var
Y=e[3],Z=e[1];return G(e[2],0,function(a){return cC(ct,j,f,Y,Z,a,d)})}var
X=e[1];return d(function(a,b){return h(i,j,[5,f,a],X,b)})}var
W=e[2];return d(function(a,b){return h(i,j,[4,f,bb(c7,a)],W,b)})}var
U=e[3],V=[8,f,"Printf: bad conversion %["];return d(function(a,b){return h(i,j,V,U,b)})}var
S=e[1];return d(function(a,b){return h(i,j,[6,f,a],S,b)})}var
R=e[1];return d(function(e,d,c){return h(i,j,[6,f,function(a,b){return a0(e,a,d,b)}],R,c)})}var
O=e[3],Q=e[2];return d(function(a,b){var
d=a[1],c=k(d,n(t(Q)));if(typeof
c[2]==="number")return h(i,j,f,l(c[1],O),b);var
e=T();return e(g(w,1))})}var
M=e[3],N=e[2],D=co(16);br(D,N);var
F=cq(D);return d(function(a,b){return h(i,j,[4,f,F],M,b)})}var
o=e[4],p=e[3],u=e[2],m=e[1];if(typeof
u==="number"){if(typeof
p==="number")return p?d(function(a,b,c){return h(i,j,[4,f,aa(m,a,b)],o,c)}):d(function(a,b){return h(i,j,[4,f,aa(m,bq(m),a)],o,b)});var
_=p[1];return d(function(a,b){return h(i,j,[4,f,aa(m,_,a)],o,b)})}if(0===u[0]){var
z=u[2],A=u[1];if(typeof
p==="number")return p?d(function(a,b,c){return h(i,j,[4,f,H(A,z,aa(m,a,b))],o,c)}):d(function(a,b){return h(i,j,[4,f,H(A,z,aa(m,bq(m),a))],o,b)});var
$=p[1];return d(function(a,b){return h(i,j,[4,f,H(A,z,aa(m,$,a))],o,b)})}var
B=u[1];if(typeof
p==="number")return p?d(function(a,b,c,d){return h(i,j,[4,f,H(B,a,aa(m,b,c))],o,d)}):d(function(a,b,c){return h(i,j,[4,f,H(B,a,aa(m,bq(m),b))],o,c)});var
ab=p[1];return d(function(a,b,c){return h(i,j,[4,f,H(B,a,aa(m,ab,b))],o,c)})}return d(bu(j,f,e[2],e[1],function(a){return a}))}var
L=e[1];return d(function(a,b){a:{b:{if(40<=a){if(92===a){var
c="\\\\";break a}if(a6<=a)break b}else{if(32>a){if(14<=a)break b;switch(a){case
8:var
c="\\b";break a;case
9:var
c="\\t";break a;case
10:var
c="\\n";break a;case
13:var
c="\\r";break a;default:break b}}if(39<=a){var
c="\\'";break a}}var
e=C(1);r(e,0,a);var
c=P(e);break a}var
d=C(4);r(d,0,92);r(d,1,48+(a/c_|0)|0);r(d,2,48+((a/10|0)%10|0)|0);r(d,3,48+(a%10|0)|0);var
c=P(d)}var
g=E(c),k=an(g+2|0,39);a_(c,0,k,1,g);return h(i,j,[4,f,P(k)],L,b)})}var
K=e[1];return d(function(a,b){return h(i,j,[5,f,a],K,b)})}var
ex=[0,a,1649,31],ey=[0,a,1650,31];function
I(i,f,c,d,e){if(typeof
c==="number")return h(bt,i,f,d,e);switch(c[0]){case
0:var
j=c[1];return e(function(a,b){return J(I,i,f,j,d,b)});case
1:var
k=c[1];return e(function(a,b){return J(I,i,f,k,d,b)});case
2:var
l=c[1];return e(function(a,b){return J(I,i,f,l,d,b)});case
3:var
m=c[1];return e(function(a,b){return J(I,i,f,m,d,b)});case
4:var
n=c[1];return e(function(a,b){return J(I,i,f,n,d,b)});case
5:var
o=c[1];return e(function(a,b){return J(I,i,f,o,d,b)});case
6:var
p=c[1];return e(function(a,b){return J(I,i,f,p,d,b)});case
7:var
q=c[1];return e(function(a,b){return J(I,i,f,q,d,b)});case
8:var
r=c[2];return e(function(a,b){return J(I,i,f,r,d,b)});case
9:var
u=c[3],a=c[2],w=v(t(c[1]),a);return e(function(a,b){return J(I,i,f,D(w,u),d,b)});case
10:var
x=c[1];return e(function(a,b,c){return J(I,i,f,x,d,c)});case
11:var
y=c[1];return e(function(a,b){return J(I,i,f,y,d,b)});case
12:var
z=c[1];return e(function(a,b){return J(I,i,f,z,d,b)});case
13:var
A=T();return A(g([0,s,ex],1));default:var
b=T();return b(g([0,s,ey],1))}}function
bt(a,b,c,d){return h(i,a,[8,b,"Printf: bad conversion %_"],c,d)}function
bu(j,g,f,d,e){if(typeof
d==="number")return function(a,b){return h(i,j,[4,g,e(a)],f,b)};if(0===d[0]){var
c=d[2],k=d[1];return function(a,b){return h(i,j,[4,g,H(k,c,e(a))],f,b)}}var
l=d[1];return function(a,b,c){return h(i,j,[4,g,H(l,a,e(b))],f,c)}}function
aX(l,k,j,d,e,f,g){if(typeof
d==="number"){if(typeof
e==="number")return e?function(a,b,c){return h(i,l,[4,k,ay(a,f(g,b))],j,c)}:function(a,b){return h(i,l,[4,k,f(g,a)],j,b)};var
c=e[1];return function(a,b){return h(i,l,[4,k,ay(c,f(g,a))],j,b)}}if(0===d[0]){var
m=d[2],n=d[1];if(typeof
e==="number")return e?function(a,b,c){return h(i,l,[4,k,H(n,m,ay(a,f(g,b)))],j,c)}:function(a,b){return h(i,l,[4,k,H(n,m,f(g,a))],j,b)};var
p=e[1];return function(a,b){return h(i,l,[4,k,H(n,m,ay(p,f(g,a)))],j,b)}}var
o=d[1];if(typeof
e==="number")return e?function(a,b,c,d){return h(i,l,[4,k,H(o,a,ay(b,f(g,c)))],j,d)}:function(a,b,c){return h(i,l,[4,k,H(o,a,f(g,b))],j,c)};var
q=e[1];return function(a,b,c){return h(i,l,[4,k,H(o,a,ay(q,f(g,b)))],j,c)}}function
ct(j,g,c,d,e,f){if(!d)return h(i,j,[4,g,e],c,f);var
k=d[1];return f(function(a,b){return G(e,a,function(a){return cC(ct,j,g,c,k,a,b)})})}var
cO="@[",de="@{";function
ab(d,b,c){function
f(a){if(typeof
a==="number")return c();switch(a[0]){case
0:var
h=a[1],i=cr(a[2]);return e(ab,d,h,function(a){return c(aG(d,i))});case
1:var
b=a[2],g=a[1];if(0===b[0]){var
j=b[1];return e(ab,d,g,function(a){aG(d,de);return ah(f,j)})}var
k=b[1];return e(ab,d,g,function(a){aG(d,cO);return ah(f,k)});case
6:var
n=a[2];return e(ab,d,a[1],function(a){return G(n,d,c)});case
7:return e(ab,d,a[1],function(a){ae(d);return c()});case
8:var
o=a[2];return e(ab,d,a[1],function(a){return c(aw(o))});case
2:case
4:var
l=a[2];return e(ab,d,a[1],function(a){return c(aG(d,l))});default:var
m=a[2];return e(ab,d,a[1],function(a){dS(d,m);return c()})}}return f(b)}function
af(d,b,c){function
f(a){if(typeof
a==="number")return c();switch(a[0]){case
0:var
i=a[1],j=cr(a[2]);return e(af,d,i,function(a){return c(aI(d,j))});case
1:var
b=a[2],g=a[1];if(0===b[0]){var
k=b[1];return e(af,d,g,function(a){aI(d,de);return ah(f,k)})}var
l=b[1];return e(af,d,g,function(a){aI(d,cO);return ah(f,l)});case
6:var
n=a[2];return e(af,d,a[1],function(a){return G(n,0,function(a){return c(aI(d,a))})});case
7:return ah(f,a[1]);case
8:var
o=a[2];return e(af,d,a[1],function(a){return c(aw(o))});case
2:case
4:var
m=a[2];return e(af,d,a[1],function(a){return c(aI(d,m))});default:var
h=a[2];return e(af,d,a[1],function(a){var
b=d[2],e=d[1],f=e[1];if(e[2]<=b){cn(d,1);at(d[1][1],d[2],h)}else
r(f,b,h);d[2]=b+1|0;return c()})}}return f(b)}function
aY(d,b,c){return h(i,function(a,b){return e(ab,d,a,function(a){return b(0)})},0,b[1],c)}function
M(a,b){return h(i,function(a,b){var
d=aH<64?aH:64,c=[0,[0,C(d),d],0];return e(af,c,a,function(a){return b(cl(c[1][1],0,c[2]))})},0,a[1],b)}var
ez=[0,[3,0,0],"%S"],eA=[0,[4,0,0,0,0],bH];function
bw(a,b,c){var
d=a[b+1];if(!(1-(typeof
d==="number")))return q(M,eA,function(a){return G(a,d,c)});if(bf(d)===a1)return q(M,ez,function(a){return G(a,d,c)});if(bf(d)!==253)return c(cY);var
f=bV("%.12g",d),e=0,h=E(f);for(;;){if(h<=e)return c(f+aq);var
g=L(f,e);a:{if(48<=g){if(58<=g)break a}else if(45!==g)break a;e=e+1|0;continue}return c(f)}}var
eB=[0,[11,bG,[2,0,[2,0,0]]],", %s%s"];function
cu(a,b,c){return a.length-1<=b?c(f):e(cu,a,b+1|0,function(d){return e(bw,a,b,function(b){return q(M,eB,function(a){return a0(a,b,d,c)})})})}var
eC=[0,[12,40,[2,0,[2,0,[12,41,0]]]],"(%s%s)"],eD=[0,[12,40,[2,0,[12,41,0]]],"(%s)"];function
cv(a,b){function
g(a){var
c=a[2],d=a[1];return c?b(d+c[1]):b(d)}if(0!==bf(a))return g([0,a[1],0]);var
d=a.length-1,h=a[1][1];function
c(a){return g([0,h,[0,a]])}if(2<d>>>0)return e(cu,a,2,function(b){return e(bw,a,1,function(d){return q(M,eC,function(a){return a0(a,d,b,c)})})});switch(d){case
2:return e(bw,a,1,function(b){return q(M,eD,function(a){return G(a,b,c)})});case
0:return c(f);default:return c(f)}}var
dl=", characters ",bv=[0,[11,'File "',[2,0,[11,'", line ',[4,0,0,0,[11,dl,[4,0,0,0,[12,45,[4,0,0,0,[11,c1,[2,0,0]]]]]]]]]],'File "%s", line %d, characters %d-%d: %s'],bp=[0,0];function
aZ(c,b){function
d(a){function
f(a){if(a)return b(a[1]);if(c===bn)return b("Out of memory");if(c===ch)return b("Stack overflow");if(c[1]===cg){var
d=c[2],g=d[3],j=d[2],k=d[1],l=g+5|0;return q(M,bv,function(a){return bA(a,k,j,g,l,"Pattern matching failed",b)})}if(c[1]===s){var
e=c[2],h=e[3],m=e[2],n=e[1],o=h+6|0;return q(M,bv,function(a){return bA(a,n,m,h,o,"Assertion failed",b)})}if(c[1]!==cj)return q(cv,c,b);var
f=c[2],i=f[3],p=f[2],r=f[1],t=i+6|0;return q(M,bv,function(a){return bA(a,r,p,i,t,"Undefined recursive module",b)})}if(!a)return f(0);var
e=a[2],g=a[1];aT(function(a){return ah(d,e)});return G(g,c,function(a){T();return a?f([0,a[1]]):ah(d,e)})}return d(bp[1])}var
eE=[0,[12,32,[4,0,0,0,0]]," %d"],eF=[0,[2,0,[12,32,[2,0,[11,' in file "',[2,0,[12,34,[2,0,[11,", line",[2,0,[11,dl,[4,0,0,0,[12,45,[4,0,0,0,0]]]]]]]]]]]]],'%s %s in file "%s"%s, line%s, characters %d-%d'],eG=[0,[11,"s ",[4,0,0,0,[12,45,[4,0,0,0,0]]]],"s %d-%d"],eH=[0,[2,0,[11," unknown location",0]],"%s unknown location"],eI=[0,[2,0,[12,10,0]],"%s\n"];function
bx(p,b,c){var
d=e_(b),h=d.length-2|0;function
k(){return c()}function
j(b){var
a=dF(d,b)[b+1];function
g(a){return a?0===b?"Raised at":"Re-raised at":0===b?"Raised by primitive operation at":"Called from"}function
c(a){function
c(a){var
c=b+1|0;return h!==b?ah(j,c):k()}if(!a)return c(0);var
d=a[1];return e(aY,p,eI,function(a){return G(a,d,c)})}if(0!==a[0]){if(a[1])return c(0);var
o=g(0);return q(M,eH,function(a){return G(a,o,function(a){return c([0,a])})})}function
i(k){var
b=a[7],d=a[4],e=a[8]?" (inlined)":f,h=a[2],i=a[9],j=g(a[1]);return q(M,eF,function(a){return eT(a,j,i,h,e,k,d,b,function(a){return c([0,a])})})}if(a[3]===a[6]){var
l=a[3];return q(M,eE,function(a){return G(a,l,i)})}var
m=a[6],n=a[3];return q(M,eG,function(a){return a0(a,n,m,i)})}return h<0?k():j(0)}function
cw(a){for(;;){var
b=bp[1],c=1-e0(bp,0,b,[0,a,b]);if(!c)return c}}var
eJ=fH([0,f,"(Cannot print locations:\n bytecode executable program file not found)","(Cannot print locations:\n bytecode executable program file appears to be corrupt)","(Cannot print locations:\n bytecode executable program file has wrong magic number)","(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)"]),cF="Fatal error: exception %s\n",cB=0,eK=[0,[11,bI,[2,0,[12,10,0]]],cF],eL=[0],eM=[0,[11,bI,[2,0,[12,10,0]]],cF],eN=[0,[11,"Fatal error in uncaught exception handler: exception ",[2,0,[12,10,0]]],"Fatal error in uncaught exception handler: exception %s\n"];b8(cJ,function(i,b,c){aT(function(a){return c(0)});function
h(a){T();return c(a)}aT(function(a){if(a===bn)return h(ck("Fatal error: out of memory in uncaught exception handler"));var
b=T();return b(g(a,0))});var
d=b?eL:dM(0);function
f(a){function
f(a){T();return h(a)}aT(function(c){var
b=dM(0);return q(aZ,i,function(g){return e(aY,U,eM,function(a){return G(a,g,function(a){return e(bx,U,d,function(a){return q(aZ,c,function(c){return e(aY,U,eN,function(a){return G(a,c,function(a){return e(bx,U,b,function(a){return f(ae(U))})})})})})})})})});return q(aZ,i,function(b){return e(aY,U,eK,function(a){return G(a,b,function(a){return e(bx,U,d,function(a){var
b=fB(0);if(b<0){var
c=aU(b);ck(dF(eJ,c)[c+1])}var
d=ae(U);T();return f(d)})})})})}aT(f);return q(bo,cB,function(a){T();return f(0)})});function
by(a,b){var
c=bf(b)===o?b:b[1];b8(a,c)}var
cx=[o,"Stdlib.Effect.Unhandled",av(0)],eO=[0,[11,"Stdlib.Effect.Unhandled(",[2,0,[12,41,0]]],"Stdlib.Effect.Unhandled(%s)"];cw(function(a,b){return a[1]===cx?q(cv,a[2],function(c){return q(M,eO,function(a){return G(a,c,function(a){return b([0,a])})})}):b(0)});by(bP,[0,cx,[o,"Stdlib.Effect.Should_not_see_this__",av(0)]]);by(dg,[o,"Stdlib.Effect.Continuation_already_resumed",av(0)]);var
cy=[o,"Jsoo_runtime.Error.Exn",av(0)];by(bL,[0,cy,[0]]);var
ag=c;ag.String;ag.RegExp;ag.Object;ag.Array;ag.Date;ag.Math;function
cz(a){return Q(a.toString())}ag.JSON;var
eR=ag.Error;cw(function(a,b){return a
instanceof
eR?b([0,cz(a)]):a[1]===cy?b([0,cz(a[2])]):b(0)});var
cA=[o,"Repro.Await",av(0)];function
bz(a){console.log(b3(a));return 0}function
eP(a,b,c){var
d=a[2];return q(function(a,b){return b(a)},b,b9(dI(a),d,c))}var
eQ=eX(function(a,b){return b(bz("returned"))},function(a,b){return q(aZ,a,function(a){return b(bz("exception: "+a))})},function(a,b,c,d){var
f=a===cA?1:0,g=f?[0,function(c){setTimeout(dO(function(a,b){return e(eP,c,0,b)}),0.);return 0}]:f;return g?d(g[1].call(null,b)):fL(a,b,c,d)});function
eS(a,b){return fJ(cA,function(a){return b(bz("continued"))})}aC(function(a){return q(eS,0,b9(eQ,0,a))},[]);aC(bo,[cB]);return}(globalThis));
