receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  file:
    path: ${env:ETA_R_T3_TRACE_FILE}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
