(test
 (name test_eta_crux_core)
 (modules test_eta_crux_core)
 (libraries eta eta_crux eta_crux_json eta_eio eta_test alcotest eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name test_eta_crux_test_surface)
 (modules test_eta_crux_test_surface)
 (libraries eta eta_crux eta_crux_test eta_eio eta_test alcotest eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name test_eta_crux_time_driver)
 (modules test_eta_crux_time_driver)
 (libraries eta eta_crux eta_eio eta_test alcotest eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name test_eta_crux_observer)
 (modules test_eta_crux_observer)
 (libraries eta eta_crux eta_crux_test eta_eio eta_test alcotest eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name test_eta_crux_reset)
 (modules test_eta_crux_reset)
 (libraries eta eta_crux eta_crux_test eta_eio eta_test alcotest eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))

(test
 (name test_eta_crux_poll)
 (modules test_eta_crux_poll)
 (libraries eta eta_crux eta_crux_test eta_eio eta_test alcotest eio_main)
 (action
  (setenv EIO_BACKEND posix
   (run %{test}))))
